// ═══════════════════════════════════════════════════════════════════════
//  O CATÁLOGO ÚNICO DAS FERRAMENTAS — dados puros (§7 do relatório do hub)
//  ---------------------------------------------------------------------
//  Uma ferramenta nova entra AQUI e passa a existir em todo o lado: hub
//  público, painel, navegação, contagens, pesquisa, sitemap, relacionados
//  e percursos. Não há segunda lista para atualizar — e é por não haver
//  que o inventário deixa de poder ficar «correto» e incompleto ao mesmo
//  tempo, que era o defeito P0-04.
//
//  REGRAS DESTE FICHEIRO
//   · Sem `use client`, sem React, sem `fiscal-data.ts`, sem motores.
//     O hub é Server Component e não pode pagar bundle por metadados.
//   · O ícone é uma CHAVE (`icon-map.tsx` resolve-a).
//   · Toda a ferramenta tem destino canónico em `/ferramentas/<slug>`.
//     Um cartão do hub nunca aponta para `/?modo=…` nem para o painel —
//     era o defeito P0-02, que mandava a pessoa para o topo da homepage.
//   · `validar.ts` corre no build e nos testes: ids/slugs/URLs únicos,
//     relacionados existentes, páginas existentes, datas não expiradas.
//
//  A CONTAGEM APRESENTADA AO UTILIZADOR DERIVA DAQUI (§2.3). Nunca se
//  escreve «14 ferramentas» à mão; conta-se `FERRAMENTAS_ATIVAS.length`.
//  Guias e Quiz não entram — não são ferramentas e não inflacionam nada.
// ═══════════════════════════════════════════════════════════════════════

import type { ToolDefinition, ToolPathway } from "./tipos";

/** Data material da última revisão fiscal. Espelha `DATA_LAST_REVIEW`. */
const REVISTO = "2026-08-07";

/** Acesso por omissão: calcular é grátis, sem conta; exportar é Plus. */
const ACESSO_PADRAO = {
  core: "free",
  account: "none",
  export: "plus",
  fizHandoff: "optional-free",
} as const;

/** Sem handoff FIZ: ferramentas que não produzem nada para a FIZ executar. */
const ACESSO_SEM_FIZ = {
  core: "free",
  account: "none",
  export: "plus",
  fizHandoff: "none",
} as const;

/** Ferramentas de resposta curta: exportar também é grátis. */
const ACESSO_TUDO_GRATIS = {
  core: "free",
  account: "none",
  export: "free",
  fizHandoff: "none",
} as const;

const TODAS_AS_SUPERFICIES = ["hub", "search", "sitemap"] as const;

export const CATALOGO_FERRAMENTAS: ToolDefinition[] = [
  // ── Calcular o que recebo ou pago ──────────────────────────────────
  {
    id: "recibos-verdes",
    slug: "recibos-verdes",
    canonicalHref: "/ferramentas/recibos-verdes",
    title: "Simulador de recibos verdes",
    shortOutcome: "Quanto de cada recibo fica mesmo para ti, depois de IRS, Segurança Social e IVA.",
    description:
      "A calculadora central de quem passa recibos verdes: do valor faturado ao líquido disponível, com o que reservar para impostos e o que sobra para a conta. IRS, retenção na fonte, Segurança Social e IVA em camadas separadas, com os coeficientes e taxas oficiais de 2026.",
    kind: "simulator",
    profiles: ["independente"],
    intents: ["calcular"],
    topics: ["irs", "seguranca-social", "iva", "recibos-verdes"],
    aliases: [
      "recibos verdes", "recibo verde", "quanto recebo", "líquido", "trabalhador independente",
      "freelancer", "quanto guardar", "tesouraria", "calculadora recibos verdes", "categoria b",
    ],
    icon: "Receipt",
    layout: "split",
    estimatedMinutes: 3,
    requiredInputs: ["Valor que vais faturar", "A tua atividade"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    featuredRank: 1,
    highlight: "O núcleo do ReciboCerto",
    status: "novo",
    dashboardHref: "/dashboard/recibos-verdes",
    cta: "Calcular líquido",
    relatedToolIds: ["seguranca-social", "regime-simplificado", "comparar-regimes", "classificar-atividade"],
    relatedGuideSlugs: ["regime-simplificado", "seguranca-social", "iva-recibos-verdes"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 97,
    searchGroup: "Simuladores",
  },
  {
    id: "simulador-irs",
    slug: "simulador-irs",
    canonicalHref: "/ferramentas/simulador-irs",
    title: "Simulador de IRS anual",
    shortOutcome: "Se vais receber reembolso ou pagar — e porquê, passo a passo.",
    description:
      "O IRS de 2026 completo: todas as categorias e anexos (A, B, E, F, G, H e J), tributação conjunta e memória de cálculo — do rendimento ao reembolso.",
    kind: "simulator",
    profiles: ["independente", "dependente", "familia"],
    intents: ["calcular"],
    topics: ["irs", "deducoes", "declaracao"],
    aliases: [
      "irs", "simulador irs", "irs anual", "reembolso irs", "acerto de irs",
      "declaração de irs", "englobamento", "modelo 3",
    ],
    icon: "Calculator",
    layout: "wide",
    estimatedMinutes: 8,
    requiredInputs: ["Rendimentos do ano", "Agregado familiar", "Despesas dedutíveis"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    featuredRank: 2,
    highlight: "O mais completo",
    dashboardHref: "/dashboard/simulador",
    cta: "Simular o IRS",
    relatedToolIds: ["irs-jovem", "recibos-verdes", "recibo-vencimento", "regime-simplificado"],
    relatedGuideSlugs: ["escaloes-irs", "deducoes-coleta", "tributacao-conjunta"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 95,
    searchGroup: "Simuladores",
  },
  {
    id: "recibo-vencimento",
    slug: "recibo-vencimento",
    canonicalHref: "/ferramentas/recibo-vencimento",
    title: "Simulador de salário líquido",
    shortOutcome: "O teu líquido mensal e anual, e como o recibo lá chega.",
    description:
      "Por conta de outrem? Do salário bruto ao líquido — IRS retido, Segurança Social e subsídio de refeição, com as tabelas oficiais de 2026.",
    kind: "simulator",
    profiles: ["dependente"],
    intents: ["calcular"],
    topics: ["salario", "irs", "seguranca-social"],
    aliases: [
      "recibo de vencimento", "salário líquido", "bruto para líquido", "ordenado",
      "conta de outrem", "subsídio de refeição", "categoria a", "vencimento",
    ],
    icon: "User",
    layout: "split",
    estimatedMinutes: 3,
    requiredInputs: ["Salário bruto mensal", "Situação familiar"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    featuredRank: 3,
    dashboardHref: "/dashboard/recibo-vencimento",
    cta: "Calcular líquido",
    relatedToolIds: ["auditoria-recibo", "comparar-regimes", "simulador-irs"],
    relatedGuideSlugs: ["recibo-vencimento", "subsidios-ferias-natal"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 92,
    searchGroup: "Simuladores",
  },
  {
    id: "regime-simplificado",
    slug: "regime-simplificado",
    canonicalHref: "/ferramentas/regime-simplificado",
    title: "Calculadora de regime simplificado",
    shortOutcome: "Que parte da tua faturação é tributável, e o imposto estimado.",
    description:
      "Insere a tua faturação e atividade. Calcula coeficiente, rendimento tributável, IRS estimado e taxa efetiva.",
    kind: "calculator",
    profiles: ["independente"],
    intents: ["calcular"],
    topics: ["irs", "coeficiente", "recibos-verdes"],
    aliases: [
      "regime simplificado", "coeficiente", "rendimento tributável", "taxa efetiva",
      "75%", "coeficiente 0,75",
    ],
    icon: "Gauge",
    layout: "compact",
    estimatedMinutes: 2,
    requiredInputs: ["Faturação anual", "Tipo de atividade"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/regime-simplificado",
    cta: "Calcular tributável",
    relatedToolIds: ["recibos-verdes", "classificar-atividade", "simulador-irs"],
    relatedGuideSlugs: ["regime-simplificado", "contabilidade-organizada"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 85,
    searchGroup: "Simuladores",
  },
  {
    id: "seguranca-social",
    slug: "seguranca-social",
    canonicalHref: "/ferramentas/seguranca-social",
    title: "Calculadora de Segurança Social trimestral",
    shortOutcome: "Quanto declarar e quanto pagar por mês, no próximo trimestre.",
    description:
      "A declaração trimestral de quem trabalha por conta própria: média dos três meses, coeficiente por tipo de atividade, ajuste de ±25%, mínimos e máximos — e o calendário de declaração e pagamento.",
    kind: "calculator",
    profiles: ["independente"],
    intents: ["calcular", "cumprir"],
    topics: ["seguranca-social", "recibos-verdes", "prazos"],
    aliases: [
      "segurança social", "ss", "declaração trimestral", "contribuição", "quanto pago à segurança social",
      "trimestral", "coeficiente segurança social", "escalão segurança social",
    ],
    icon: "ShieldCheck",
    layout: "compact",
    estimatedMinutes: 2,
    requiredInputs: ["Faturação dos três meses do trimestre"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    status: "novo",
    guiaEmbedHref: "/guias/seguranca-social",
    cta: "Calcular contribuição",
    relatedToolIds: ["recibos-verdes", "regime-simplificado", "classificar-atividade"],
    relatedGuideSlugs: ["seguranca-social", "acumulacao-emprego"],
    surfaces: ["hub", "search", "sitemap"],
    searchPriority: 88,
    searchGroup: "Simuladores",
  },
  {
    id: "irs-jovem",
    slug: "irs-jovem",
    canonicalHref: "/ferramentas/irs-jovem",
    title: "Simulador de IRS Jovem",
    shortOutcome: "Se és elegível e quanto o benefício muda no teu IRS.",
    description:
      "Triagem de elegibilidade e cálculo do IRS Jovem de 2026: ano de benefício, percentagem de isenção, teto em IAS traduzido para euros e comparação lado a lado com e sem o benefício.",
    kind: "calculator",
    profiles: ["independente", "dependente"],
    intents: ["calcular"],
    topics: ["irs", "beneficios", "jovens"],
    aliases: [
      "irs jovem", "isenção jovem", "jovem", "benefício jovem", "irs para jovens",
      "primeiro emprego irs", "ifici",
    ],
    icon: "Sparkle",
    layout: "compact",
    estimatedMinutes: 2,
    requiredInputs: ["Idade", "Ano de benefício", "Rendimento anual"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    status: "novo",
    guiaEmbedHref: "/guias/irs-jovem",
    cta: "Ver se sou elegível",
    relatedToolIds: ["simulador-irs", "recibo-vencimento", "recibos-verdes"],
    relatedGuideSlugs: ["irs-jovem", "escaloes-irs"],
    surfaces: ["hub", "search", "sitemap"],
    searchPriority: 84,
    searchGroup: "Simuladores",
  },

  // ── Comparar e decidir ─────────────────────────────────────────────
  {
    id: "comparar-regimes",
    slug: "comparar-regimes",
    canonicalHref: "/ferramentas/comparar-regimes",
    title: "Recibos verdes, contrato ou empresa?",
    shortOutcome: "Qual dos três te deixa mais líquido — e a que custo de obrigações.",
    description:
      "Para o mesmo rendimento anual, compara o líquido como trabalhador por conta de outrem, em recibos verdes ou através de uma empresa (IRC + dividendos), com o ponto de viragem, os benefícios por região e o custo de contabilista.",
    kind: "simulator",
    profiles: ["independente", "dependente", "empresa"],
    intents: ["comparar"],
    topics: ["irs", "irc", "seguranca-social", "empresa", "salario"],
    aliases: [
      "comparar", "comparador", "recibos verdes ou contrato", "compensa abrir empresa",
      "ponto de viragem", "contrato vs recibos verdes", "recibos verdes vs empresa",
    ],
    icon: "Scale",
    layout: "wide",
    estimatedMinutes: 4,
    requiredInputs: ["Rendimento anual", "Situação familiar"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    featuredRank: 4,
    status: "novo",
    dashboardHref: "/dashboard/comparar",
    cta: "Comparar regimes",
    relatedToolIds: ["recibos-verdes", "recibo-vencimento", "simulador-empresa"],
    relatedGuideSlugs: ["unipessoal-vs-eni", "falsos-recibos-verdes"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 93,
    searchGroup: "Simuladores",
  },
  {
    id: "simulador-empresa",
    slug: "simulador-empresa",
    canonicalHref: "/ferramentas/simulador-empresa",
    title: "Simulador de empresa (Lda)",
    shortOutcome: "O que sobra para ti através de uma sociedade, e a partir de que rendimento compensa.",
    description:
      "Simula o resultado líquido de abrir uma sociedade: IRC, dividendos, custos de operação e passos para constituição. Guiado e completo.",
    kind: "simulator",
    profiles: ["empresa", "independente"],
    intents: ["comparar"],
    topics: ["irc", "empresa", "dividendos"],
    aliases: [
      "abrir empresa", "sociedade", "lda", "unipessoal", "irc", "dividendos",
      "derrama", "tributação autónoma", "gerente",
    ],
    icon: "Building",
    layout: "wide",
    estimatedMinutes: 6,
    requiredInputs: ["Faturação prevista", "Custos fixos", "Salário do gerente"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/empresa",
    cta: "Simular empresa",
    relatedToolIds: ["comparar-regimes", "recibos-verdes", "mapa-contabilistas"],
    relatedGuideSlugs: ["abrir-empresa", "unipessoal-vs-eni", "tributacao-autonoma"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 88,
    searchGroup: "Simuladores",
  },
  {
    id: "ato-isolado",
    slug: "ato-isolado",
    canonicalHref: "/ferramentas/ato-isolado",
    title: "Ato isolado ou abrir atividade?",
    shortOutcome: "Uma recomendação explicada, com o caminho que lá levou.",
    description:
      "Responde a 4 perguntas simples e fica a saber se deves emitir um ato isolado ou abrir atividade nas Finanças.",
    kind: "decider",
    profiles: ["independente"],
    intents: ["comparar", "cumprir"],
    topics: ["recibos-verdes", "atividade", "irs"],
    aliases: [
      "ato isolado", "acto isolado", "abrir atividade ou não", "recibo único",
      "trabalho pontual", "trabalho esporádico",
    ],
    icon: "Swap",
    layout: "compact",
    estimatedMinutes: 2,
    requiredInputs: ["Quanto vais receber", "Se é trabalho pontual ou recorrente"],
    access: ACESSO_TUDO_GRATIS,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/ato-isolado",
    cta: "Descobrir o que fazer",
    relatedToolIds: ["recibos-verdes", "classificar-atividade", "regime-simplificado"],
    relatedGuideSlugs: ["ato-isolado", "abrir-atividade"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 72,
    searchGroup: "Decisores",
  },
  {
    id: "simulador-herancas",
    slug: "simulador-herancas",
    canonicalHref: "/ferramentas/simulador-herancas",
    title: "Simulador de heranças e sucessões",
    shortOutcome: "Quem herda o quê, e que imposto se aplica a cada um.",
    description:
      "Quem herda o quê e quanto se paga de Imposto do Selo — a família direta é isenta. Meação, legítima e quota disponível, partilha e comparação herança vs doação. Guiado e completo.",
    kind: "simulator",
    profiles: ["familia"],
    intents: ["comparar"],
    topics: ["patrimonio", "imposto-selo", "heranca"],
    aliases: [
      "heranças", "herança", "doações", "doação", "imposto do selo", "partilha",
      "legítima", "meação", "herdar casa", "sucessões",
    ],
    icon: "Scale",
    layout: "wide",
    estimatedMinutes: 6,
    requiredInputs: ["Relação familiar dos herdeiros", "Valor do património"],
    access: ACESSO_SEM_FIZ,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/herancas",
    cta: "Simular partilha",
    relatedToolIds: ["mapa-contabilistas", "simulador-irs"],
    relatedGuideSlugs: ["herancas-imposto-selo", "doacoes"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 74,
    searchGroup: "Simuladores",
  },

  // ── Verificar se está certo ────────────────────────────────────────
  {
    id: "auditoria-recibo",
    slug: "auditoria-recibo",
    canonicalHref: "/ferramentas/auditoria-recibo",
    title: "Auditoria do recibo de vencimento",
    shortOutcome: "Se há alguma diferença no teu recibo que devas confirmar.",
    description:
      "Introduz os valores do teu recibo e descobre se a entidade aplicou bem o IRS e a Segurança Social de 2026. Deteta erros a teu favor.",
    kind: "validator",
    profiles: ["dependente"],
    intents: ["verificar"],
    topics: ["salario", "irs", "seguranca-social"],
    aliases: [
      "auditar recibo", "erro no recibo", "recibo errado", "desconto errado",
      "verificar recibo de vencimento", "confirmar recibo",
    ],
    icon: "ShieldCheck",
    layout: "split",
    estimatedMinutes: 4,
    requiredInputs: ["O teu recibo de vencimento (PDF ou valores)"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/auditoria-recibo",
    cta: "Verificar recibo",
    relatedToolIds: ["recibo-vencimento", "simulador-irs"],
    relatedGuideSlugs: ["recibo-vencimento", "subsidios-ferias-natal"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 78,
    searchGroup: "Ferramentas",
  },
  {
    id: "classificar-atividade",
    slug: "classificar-atividade",
    canonicalHref: "/ferramentas/classificar-atividade",
    title: "Classificar atividade fiscal",
    shortOutcome: "O código e o tratamento fiscal que correspondem ao que fazes.",
    description:
      "Pesquisa a tua profissão e descobre a retenção na fonte, o coeficiente e a base de Segurança Social aplicável.",
    kind: "validator",
    profiles: ["independente"],
    intents: ["verificar", "cumprir"],
    topics: ["atividade", "retencao", "coeficiente"],
    aliases: [
      "classificar atividade", "código de atividade", "cae", "art 151", "artigo 151",
      "profissão", "retenção por profissão", "tabela de atividades",
    ],
    icon: "Search",
    layout: "compact",
    estimatedMinutes: 1,
    requiredInputs: ["A tua profissão ou o que fazes"],
    access: ACESSO_TUDO_GRATIS,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/classificar-atividade",
    cta: "Classificar atividade",
    relatedToolIds: ["recibos-verdes", "regime-simplificado", "ato-isolado"],
    relatedGuideSlugs: ["abrir-atividade", "retencao-na-fonte"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 80,
    searchGroup: "Ferramentas",
  },

  // ── Preparar uma obrigação · Encontrar apoio ───────────────────────
  {
    id: "payout-mor",
    slug: "payout-mor",
    canonicalHref: "/ferramentas/payout-mor",
    title: "Recibo de Merchant of Record",
    shortOutcome: "O recibo verde do teu payout, com os campos certos para copiar.",
    description:
      "Configura o recibo verde para payout do Paddle ou Lemon Squeezy em 5 passos. IVA, retenção e NIF preenchidos.",
    kind: "wizard",
    profiles: ["independente"],
    intents: ["cumprir"],
    topics: ["iva", "recibos-verdes", "plataformas"],
    aliases: [
      "merchant of record", "mor", "paddle", "lemon squeezy", "payout",
      "recibo para plataforma", "gumroad", "stripe",
    ],
    icon: "ShoppingBag",
    layout: "compact",
    estimatedMinutes: 4,
    requiredInputs: ["Plataforma", "Valor do payout"],
    access: ACESSO_PADRAO,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/payout",
    cta: "Configurar recibo",
    relatedToolIds: ["recibos-verdes", "classificar-atividade"],
    relatedGuideSlugs: ["iva-recibos-verdes", "clientes-estrangeiros"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 60,
    searchGroup: "Ferramentas",
  },
  {
    id: "mapa-contabilistas",
    slug: "mapa-contabilistas",
    canonicalHref: "/ferramentas/mapa-contabilistas",
    title: "Mapa de preços por região",
    shortOutcome: "Quanto custa apoio profissional na tua região, e quão fiável é a estimativa.",
    description:
      "Contabilistas, notários e advogados: quanto custam na tua região, num único mapa com filtros — incluindo os benefícios fiscais de cada zona do país.",
    kind: "map",
    profiles: ["independente", "empresa", "dependente", "familia"],
    intents: ["cumprir"],
    topics: ["contabilista", "custos", "regioes"],
    aliases: [
      "contabilista", "quanto custa um contabilista", "avença", "notário",
      "advogado", "honorários", "escritura", "procuração", "preços por região",
    ],
    icon: "MapPin",
    layout: "map",
    estimatedMinutes: 2,
    requiredInputs: ["A tua região"],
    access: ACESSO_TUDO_GRATIS,
    privacy: "local-only",
    fiscalYear: 2026,
    reviewedAt: REVISTO,
    dashboardHref: "/dashboard/mapa-contabilistas",
    cta: "Ver preços na minha região",
    relatedToolIds: ["simulador-empresa", "regime-simplificado"],
    relatedGuideSlugs: ["contabilidade-organizada", "abrir-empresa"],
    surfaces: ["hub", "homepage", "dashboard", "search", "sitemap"],
    searchPriority: 70,
    searchGroup: "Ferramentas",
  },
];

/**
 * Percursos (§6) — sequências com um resultado, não mais uma grelha.
 *
 * São dados: não duplicam motores nem persistem nada fora do dispositivo.
 * Os `toolId` são validados contra o catálogo em `validar.ts`.
 */
export const PERCURSOS: ToolPathway[] = [
  {
    id: "comecar-por-conta-propria",
    title: "Começar a trabalhar por conta própria",
    outcome: "Sabes o que abrir, quanto vais receber e quanto reservar.",
    steps: [
      { toolId: "classificar-atividade", note: "Descobre o teu código e o tratamento fiscal." },
      { toolId: "ato-isolado", note: "Confirma se precisas mesmo de abrir atividade." },
      { toolId: "recibos-verdes", note: "Vê o líquido real de cada recibo." },
      { toolId: "seguranca-social", note: "Estima a contribuição do primeiro trimestre." },
    ],
  },
  {
    id: "avaliar-proposta",
    title: "Avaliar uma proposta de trabalho",
    outcome: "Comparas contrato e recibos verdes com as mesmas premissas.",
    steps: [
      { toolId: "recibo-vencimento", note: "O líquido da proposta como contrato." },
      { toolId: "recibos-verdes", note: "O mesmo valor, mas em recibos verdes." },
      { toolId: "comparar-regimes", note: "Os três cenários lado a lado, com o ponto de viragem." },
    ],
  },
  {
    id: "confirmar-recibo",
    title: "Confirmar um recibo que recebeste",
    outcome: "Ficas com uma lista concreta de pontos para falar com a entidade.",
    steps: [
      { toolId: "recibo-vencimento", note: "Simula o valor que devias receber." },
      { toolId: "auditoria-recibo", note: "Compara com o recibo real, linha a linha." },
    ],
  },
  {
    id: "preparar-ano-fiscal",
    title: "Preparar o ano fiscal",
    outcome: "Chegas a abril a saber o que esperar da declaração.",
    steps: [
      { toolId: "irs-jovem", note: "Confirma se tens direito ao benefício." },
      { toolId: "simulador-irs", note: "Simula a declaração completa." },
      { toolId: "regime-simplificado", note: "Confirma o coeficiente da tua atividade." },
    ],
  },
];
