import { fonte, type QuizPergunta } from "./types";

export const PERGUNTAS_PARTE_3: QuizPergunta[] = [
  {
    id: "ativ-1",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um programador informático (código 1332 da tabela do Art. 151.º CIRS) que fatura através de recibos verdes tem retenção na fonte de:",
    opcoes: [
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora do Art. 151.º — programadores informáticos (código 1332) constam dessa tabela." },
      { texto: "16,5%", porque: "16,5% aplica-se a direitos de autor/propriedade intelectual, não à prestação de serviços de programação enquadrada no Art. 151.º." },
      { texto: "23%", porque: "Programadores informáticos (código 1332) constam da tabela do Art. 151.º CIRS, com retenção de 23% e coeficiente de 0,75 no regime simplificado." },
      { texto: "0% — sem retenção", porque: "Só vendas de bens estão dispensadas de retenção — a prestação de serviços de programação está sujeita a 23%." },
    ],
    correta: 2,
    legalBasis: "Art. 151.º CIRS (código 1332) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-2",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um motorista de TVDE (plataformas como Uber ou Bolt) tem retenção na fonte sobre os valores que recebe?",
    opcoes: [
      { texto: "Sim, 23%, como profissão do Art. 151.º.", porque: "A atividade de TVDE é enquadrada como transporte de passageiros (coef. 0,15) e não tem retenção — não está na tabela do Art. 151.º." },
      { texto: "Sim, 11,5%, como 'outra prestação de serviços'.", porque: "A atividade de TVDE está enquadrada com coeficiente 0,15 (transportes) e sem retenção na fonte — não com o tratamento de 'outros serviços'." },
      { texto: "Não — tem coeficiente 0,15 (transportes) e não há retenção na fonte.", porque: "TVDE é enquadrado com coeficiente 0,15 (Art. 31.º, al. a) CIRS — transportes) e sem retenção na fonte; a Segurança Social incide sobre 20% do rendimento." },
      { texto: "Sim, 16,5%, como cessão de equipamento (o veículo).", porque: "A cessão de uso de equipamentos é uma categoria distinta (coef. 0,95, ret. 16,5%) — não se aplica ao transporte de passageiros via TVDE." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. a) CIRS — transportes (atividade de TVDE)",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-3",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um criador de conteúdo digital / influencer (atividade fora do Art. 151.º) que recebe pagamentos de uma entidade com contabilidade organizada tem, em geral:",
    opcoes: [
      { texto: "Coeficiente 0,75 e retenção de 23%, como no Art. 151.º.", porque: "0,75/23% aplica-se às profissões da tabela do Art. 151.º — criadores de conteúdo digital não constam dessa tabela." },
      { texto: "Coeficiente 0,35 e retenção de 11,5% (Art. 31.º, al. c) CIRS).", porque: "Criadores de conteúdo digital, fora do Art. 151.º, têm coeficiente 0,35 e retenção de 11,5% quando o cliente tem contabilidade organizada (Art. 101.º, al. c) CIRS)." },
      { texto: "Coeficiente 0,95 e retenção de 16,5%, como direitos de autor.", porque: "0,95/16,5% aplica-se especificamente à cedência de propriedade intelectual — patrocínios/publicidade são tratados como prestação de serviços (coef. 0,35)." },
      { texto: "Coeficiente 0,15 e sem retenção, como venda de bens.", porque: "0,15/sem retenção aplica-se a venda de bens/hotelaria/transportes — não ao trabalho de criação de conteúdo digital." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. c) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-4",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um escritor que recebe direitos de autor pela venda da sua obra literária própria tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a prestações de serviços de escrita sem cedência de direitos de autor — não ao titular originário da obra." },
      { texto: "0,75", porque: "0,75 aplica-se às profissões do Art. 151.º — não é o caso do titular de direitos de autor de obra própria." },
      { texto: "0,95", porque: "Como titular originário de obra literária (direitos de autor), o coeficiente aplicável é 0,95 (Art. 31.º, al. d) CIRS)." },
      { texto: "1,00", porque: "1,00 só se aplica ao regime de transparência fiscal (serviços a sociedade onde se detém ≥5%), não a direitos de autor de obra literária." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. d) CIRS — titular originário de obra literária",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-5",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um prestador de serviços que trabalha exclusivamente para uma sociedade onde detém 10% do capital, há mais de 183 dias por ano, está sujeito a que coeficiente no regime simplificado (regime de transparência fiscal)?",
    opcoes: [
      { texto: "0,75", porque: "0,75 é o coeficiente normal das profissões do Art. 151.º — o regime de transparência fiscal tem um coeficiente próprio, mais elevado." },
      { texto: "0,95", porque: "0,95 aplica-se a direitos de autor/propriedade intelectual — não ao regime de transparência fiscal." },
      { texto: "1,00", porque: "Quando se prestam serviços a uma sociedade onde se detém ≥5% do capital por mais de 183 dias, o coeficiente aplicável é 1,00 (Art. 31.º, al. g) CIRS) — ou seja, todo o rendimento é tributável." },
      { texto: "0,15", porque: "0,15 aplica-se a venda de bens/restauração/hotelaria — não a este regime especial de transparência fiscal." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. g) CIRS — serviços a sociedade onde detém ≥ 5%",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-6",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Uma pessoa que explora um alojamento local numa moradia/apartamento (fora de zona de contenção) tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,15", porque: "0,15 aplica-se ao alojamento local em estabelecimento de hotelaria — para moradia/apartamento o coeficiente é mais elevado (0,35)." },
      { texto: "0,35", porque: "Alojamento local em moradia/apartamento (fora de zona de contenção) tem coeficiente de 0,35." },
      { texto: "0,50", porque: "0,50 aplica-se a alojamento local em moradia situada em zona de contenção (exige o anexo 13F), não ao caso geral." },
      { texto: "0,75", porque: "0,75 aplica-se às profissões do Art. 151.º — não ao alojamento local." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º CIRS — alojamento local (moradia/apartamento)",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "catf-1",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é a taxa autónoma de IRS sobre rendimentos de arrendamento para habitação (Categoria F)?",
    opcoes: [
      { texto: "23%", porque: "23% é a taxa normal de IVA — não se aplica à tributação autónoma de rendas (Categoria F)." },
      { texto: "25%", porque: "Os rendimentos de arrendamento para habitação (Categoria F) são tributados a uma taxa autónoma de 25% (Art. 72.º, n.º 1 CIRS)." },
      { texto: "28%", porque: "28% é a taxa aplicável ao arrendamento NÃO habitacional (comércio, escritórios), não ao arrendamento para habitação." },
      { texto: "35%", porque: "35% não corresponde a nenhuma taxa autónoma da Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º, n.º 1 CIRS — taxa especial dos rendimentos prediais (habitação)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-2",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é a taxa autónoma de IRS sobre rendimentos de arrendamento NÃO habitacional (ex.: lojas, escritórios)?",
    opcoes: [
      { texto: "25%", porque: "25% aplica-se ao arrendamento para habitação — o arrendamento não habitacional tem taxa superior (28%)." },
      { texto: "28%", porque: "Rendimentos de arrendamento não habitacional são tributados a uma taxa autónoma de 28% (Art. 72.º CIRS)." },
      { texto: "21%", porque: "21% não corresponde a nenhuma taxa da Categoria F prevista no Art. 72.º CIRS." },
      { texto: "30%", porque: "30% não corresponde à taxa em vigor para arrendamento não habitacional (28%)." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — rendimentos prediais de arrendamento não habitacional",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-3",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um contrato de arrendamento habitacional permanente com duração entre 10 e 20 anos, comunicado à AT, beneficia de uma redução da taxa autónoma de:",
    opcoes: [
      { texto: "10 pontos percentuais", porque: "10 p.p. é a redução para contratos entre 5 e 10 anos, não entre 10 e 20." },
      { texto: "15 pontos percentuais", porque: "Contratos de arrendamento habitacional permanente entre 10 e 20 anos beneficiam de uma redução de 15 p.p. na taxa autónoma (Art. 72.º, n.os 2 a 5 CIRS, Lei 56/2023)." },
      { texto: "20 pontos percentuais", porque: "20 p.p. é a redução para contratos de 20 ou mais anos, não para o intervalo de 10 a 20 anos." },
      { texto: "5 pontos percentuais", porque: "5 p.p. não corresponde a nenhuma das reduções previstas (10 / 15 / 20 p.p.)." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS (Lei 56/2023) — reduções por duração do contrato",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-4",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um contrato de arrendamento habitacional permanente com 20 ou mais anos de duração, comunicado à AT, beneficia de uma redução da taxa autónoma de:",
    opcoes: [
      { texto: "10 pontos percentuais", porque: "10 p.p. é a redução para contratos entre 5 e 10 anos, não para 20 ou mais anos." },
      { texto: "15 pontos percentuais", porque: "15 p.p. é a redução para contratos entre 10 e 20 anos — para 20 anos ou mais, a redução é maior (20 p.p.)." },
      { texto: "20 pontos percentuais", porque: "Contratos de arrendamento habitacional permanente com 20 ou mais anos beneficiam da maior redução prevista: 20 p.p. na taxa autónoma." },
      { texto: "25 pontos percentuais", porque: "25 p.p. tornaria a taxa efetiva negativa (a taxa base para habitação é 25%) — a redução máxima prevista é de 20 p.p." },
    ],
    correta: 2,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS (Lei 56/2023) — reduções por duração do contrato",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "praz-1",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Em que período do ano deve ser entregue a declaração anual de IRS (Modelo 3)?",
    opcoes: [
      { texto: "De 1 de janeiro a 31 de março.", porque: "Este período não corresponde ao prazo legal de entrega — a declaração de IRS entrega-se entre abril e junho." },
      { texto: "De 1 de abril a 30 de junho.", porque: "O período geral de entrega da declaração de IRS é de 1 de abril a 30 de junho." },
      { texto: "De 1 de maio a 31 de julho.", porque: "Este período não corresponde ao prazo legal — a entrega da declaração de IRS faz-se de 1 de abril a 30 de junho." },
      { texto: "De 1 de setembro a 31 de outubro.", porque: "Este período não corresponde à entrega da declaração de IRS — corresponde antes a uma altura de pagamentos por conta." },
    ],
    correta: 1,
    legalBasis: "Entrega da declaração de IRS — período geral 1 de abril a 30 de junho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-2",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "O pagamento mensal das contribuições para a Segurança Social de um trabalhador independente deve ser feito até que dia do mês?",
    opcoes: [
      { texto: "Dia 10", porque: "O pagamento pode iniciar-se no dia 10, mas o limite (prazo final) é o dia 20." },
      { texto: "Dia 15", porque: "O dia 15 não corresponde ao limite do prazo — o pagamento mensal de SS deve ser feito até ao dia 20." },
      { texto: "Dia 20", porque: "A contribuição mensal para a Segurança Social deve ser paga entre os dias 10 e 20 de cada mês, sendo o dia 20 o limite." },
      { texto: "Dia 30", porque: "Dia 30 não corresponde ao prazo de pagamento mensal de SS — o limite é o dia 20." },
    ],
    correta: 2,
    legalBasis: "Pagamento mensal — Segurança Social (entre os dias 10 e 20)",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-3",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "A declaração trimestral de rendimentos à Segurança Social, referente ao 1.º trimestre do ano (janeiro a março), deve ser feita até ao final de que mês?",
    opcoes: [
      { texto: "Janeiro", porque: "Janeiro corresponde à declaração do 4.º trimestre do ano anterior, não à do 1.º trimestre do ano em curso." },
      { texto: "Abril", porque: "A declaração trimestral à SS referente ao 1.º trimestre (jan-mar) é feita até ao final de abril." },
      { texto: "Julho", porque: "Julho corresponde à declaração do 2.º trimestre, não do 1.º." },
      { texto: "Outubro", porque: "Outubro corresponde à declaração do 3.º trimestre, não do 1.º." },
    ],
    correta: 1,
    legalBasis: "Declaração trimestral — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-4",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Para um trabalhador independente que não está isento de IVA e está no regime trimestral, a declaração periódica de IVA referente ao 1.º trimestre (jan-mar) deve ser entregue até ao dia 20 de que mês?",
    opcoes: [
      { texto: "Abril", porque: "Abril não é o mês correto — a declaração do 1.º trimestre tem um mês de carência adicional, sendo entregue em maio." },
      { texto: "Maio", porque: "A declaração periódica de IVA trimestral referente ao 1.º trimestre é entregue até ao dia 20 de maio." },
      { texto: "Junho", porque: "Junho não corresponde ao prazo de entrega da declaração de IVA do 1.º trimestre (maio)." },
      { texto: "Agosto", porque: "Agosto corresponde à entrega da declaração de IVA do 2.º trimestre, não do 1.º." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (trimestral)",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-5",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Os pagamentos por conta de IRS (para quem não tem retenção na fonte) ocorrem em que meses do ano?",
    opcoes: [
      { texto: "Janeiro, abril e julho", porque: "Estes meses não correspondem aos pagamentos por conta de IRS — os pagamentos ocorrem na segunda metade do ano." },
      { texto: "Março, junho e setembro", porque: "Estes meses não correspondem aos pagamentos por conta de IRS previstos." },
      { texto: "Julho, setembro e dezembro", porque: "Os 3 pagamentos por conta de IRS, para quem não tem retenção na fonte, ocorrem até ao dia 20 de julho, setembro e dezembro." },
      { texto: "Fevereiro, maio e agosto", porque: "Estes meses correspondem antes às declarações periódicas de IVA, não aos pagamentos por conta de IRS." },
    ],
    correta: 2,
    legalBasis: "Pagamentos por conta de IRS — para quem não faz retenção na fonte",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "ger-1",
    categoria: "geral",
    dificuldade: 1,
    pergunta: "O que é, em termos fiscais, um 'recibo verde'?",
    opcoes: [
      { texto: "Um documento exclusivo para pedir reembolso de IVA.", porque: "Um recibo verde não é um pedido de reembolso de IVA — é o documento (recibo eletrónico) emitido por trabalhadores independentes para titular rendimentos da categoria B." },
      { texto: "O recibo eletrónico emitido por um trabalhador independente (categoria B) para titular uma prestação de serviços ou venda.", porque: "'Recibo verde' é a designação comum do recibo eletrónico emitido no Portal das Finanças por trabalhadores independentes, para titular rendimentos da categoria B (prestações de serviços/atos isolados)." },
      { texto: "Um tipo de fatura usado apenas por empresas com contabilidade organizada.", porque: "Empresas com contabilidade organizada emitem faturas através de programas certificados — o 'recibo verde' é típico de trabalhadores independentes em nome individual." },
      { texto: "Um certificado de quitação da Segurança Social.", porque: "Um recibo verde não é um certificado de situação contributiva — é o documento que titula o rendimento de um serviço prestado ou bem vendido." },
    ],
    correta: 1,
    legalBasis: "Recibo eletrónico — rendimentos da categoria B (CIRS)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "ger-2",
    categoria: "geral",
    dificuldade: 2,
    pergunta: "A retenção na fonte de IRS aplicada num recibo verde e a contribuição para a Segurança Social são:",
    opcoes: [
      { texto: "A mesma coisa — pagas de uma só vez à Autoridade Tributária.", porque: "São impostos/contribuições distintos: a retenção de IRS é entregue à Autoridade Tributária, e a contribuição para a SS é paga separadamente à Segurança Social, com regras e bases próprias." },
      { texto: "Calculadas exatamente com a mesma percentagem e sobre a mesma base.", porque: "Não — a retenção de IRS varia por tipo de atividade (23%/11,5%/16,5%/0%), enquanto a SS tem taxa fixa de 21,4% sobre 70% ou 20% do rendimento." },
      { texto: "Obrigações distintas: a retenção é um adiantamento de IRS (à AT) e a contribuição é para a Segurança Social, com bases de cálculo próprias.", porque: "São obrigações fiscal/contributiva distintas, com entidades, taxas e bases de cálculo diferentes (retenção de IRS vs. contribuição para a SS)." },
      { texto: "Apenas uma delas é obrigatória — o trabalhador escolhe qual pagar.", porque: "Ambas podem ser obrigatórias em simultâneo (salvo isenções específicas de cada uma), e não são alternativas entre si." },
    ],
    correta: 2,
    legalBasis: "IRS (Art. 101.º CIRS) vs. Segurança Social (Código Contributivo) — obrigações distintas",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "ger-3",
    categoria: "geral",
    dificuldade: 2,
    pergunta: "Estar isento de IVA (Art. 53.º CIVA, por faturar menos de 15.000 €/ano) significa automaticamente que também se está isento de Segurança Social?",
    opcoes: [
      { texto: "Sim — os dois regimes partilham o mesmo limiar e a mesma isenção.", porque: "Apesar de partilharem por vezes limiares semelhantes, são regimes distintos: a isenção de IVA não implica isenção automática de Segurança Social." },
      { texto: "Não — são regimes distintos, com regras e isenções próprias (ex.: a SS tem isenção nos primeiros 12 meses de atividade, independente do IVA).", porque: "A isenção de IVA (Art. 53.º CIVA) e a isenção/obrigação de SS (Código Contributivo) são regimes distintos, com regras próprias — não se determinam automaticamente uma à outra." },
      { texto: "Sim, mas só durante o primeiro ano de atividade.", porque: "Mesmo no 1.º ano, a isenção de SS resulta de uma regra própria do Código Contributivo (12 meses sem atividade independente nos últimos 3 anos), não da isenção de IVA." },
      { texto: "Não — pelo contrário, ficar isento de IVA obriga a pagar mais Segurança Social.", porque: "Não existe qualquer relação de compensação direta entre a isenção de IVA e o valor pago à Segurança Social." },
    ],
    correta: 1,
    legalBasis: "Art. 53.º CIVA vs. Código Contributivo — regimes distintos",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "ger-4",
    categoria: "geral",
    dificuldade: 1,
    pergunta: "O 'Ato Isolado' nas Finanças é indicado para que situação?",
    opcoes: [
      { texto: "Quem tem atividade aberta nas Finanças e fatura regularmente todos os meses.", porque: "Quem fatura com regularidade deve ter atividade aberta — o ato isolado destina-se precisamente a quem NÃO presta serviços com regularidade." },
      { texto: "Quem presta um serviço ou faz uma venda ocasional, sem caráter de regularidade, sem ter (ou precisar de abrir) atividade nas Finanças.", porque: "O ato isolado é um documento emitido para situações pontuais/ocasionais, sem regularidade, permitindo titular esse rendimento sem necessidade de abrir atividade." },
      { texto: "Apenas para empresas (pessoas coletivas).", porque: "O ato isolado destina-se a pessoas singulares que não exercem a atividade de forma regular — não é um mecanismo de pessoas coletivas." },
      { texto: "Para substituir definitivamente a abertura de atividade, mesmo para quem fatura todos os meses.", porque: "Quem fatura com regularidade não deve recorrer ao ato isolado de forma continuada — deve abrir atividade nas Finanças." },
    ],
    correta: 1,
    legalBasis: "Ato isolado — rendimento ocasional, sem caráter de regularidade (categoria B)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "ger-5",
    categoria: "geral",
    dificuldade: 2,
    pergunta: "No regime simplificado de IRS, os coeficientes (0,75 / 0,35 / 0,15 / 0,95, etc.) servem para:",
    opcoes: [
      { texto: "Calcular diretamente o valor de IVA a entregar ao Estado.", porque: "Os coeficientes do regime simplificado não se aplicam ao cálculo do IVA — servem para apurar o rendimento tributável em sede de IRS." },
      { texto: "Estimar, a partir do rendimento bruto, a parte considerada rendimento tributável (presumindo as despesas da atividade).", porque: "Os coeficientes do Art. 31.º CIRS aplicam-se ao rendimento bruto para estimar o rendimento tributável, presumindo uma percentagem de despesas associada a cada tipo de atividade." },
      { texto: "Determinar a taxa de retenção na fonte a aplicar em cada recibo.", porque: "A retenção na fonte tem taxas próprias (23%/11,5%/16,5%/0%), distintas dos coeficientes do regime simplificado, embora ambas dependam do tipo de atividade." },
      { texto: "Calcular o valor da contribuição mensal para a Segurança Social.", porque: "A SS usa bases próprias (70% ou 20% do rendimento) — distintas dos coeficientes do regime simplificado de IRS." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º CIRS — coeficientes do regime simplificado",
    fonte: fonte("art31"),
  },
];
