import { fonte, type QuizPergunta } from "./types";

export const PERGUNTAS_PRAZOS: QuizPergunta[] = [
  {
    id: "praz-6",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Qual é o prazo máximo para emitir um recibo verde após o recebimento do pagamento?",
    opcoes: [
      { texto: "Deve ser emitido no próprio dia do pagamento, sem exceção.", porque: "Embora o ideal seja emitir no dia do pagamento, a lei permite até 5 dias úteis após." },
      { texto: "Até 5 dias úteis após a data do pagamento.", porque: "O recibo verde deve ser emitido na data do pagamento ou até 5 dias úteis após o recebimento." },
      { texto: "Até 10 dias úteis após a data do pagamento.", porque: "O prazo de 10 dias úteis não corresponde ao previsto na lei — o limite são 5 dias úteis." },
      { texto: "Até ao final do mês em que ocorreu o pagamento.", porque: "Não existe um prazo até ao final do mês — o recibo deve ser emitido até 5 dias úteis após o pagamento." },
    ],
    correta: 1,
    legalBasis: "Emissão de recibo verde — até 5 dias úteis após o pagamento",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-7",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Até quando devem ser validadas as faturas no e-Fatura para efeitos de deduções no IRS?",
    opcoes: [
      { texto: "Até 31 de janeiro do ano seguinte.", porque: "O prazo de validação das faturas no e-Fatura não é 31 de janeiro — e 15 de fevereiro." },
      { texto: "Até 15 de fevereiro do ano seguinte.", porque: "As faturas pendentes no e-Fatura devem ser validadas até 15 de fevereiro do ano seguinte ao das despesas." },
      { texto: "Até 31 de marco do ano seguinte.", porque: "O prazo de 31 de marco não está correto — a validação deve ocorrer até 15 de fevereiro." },
      { texto: "Até 30 de abril do ano seguinte.", porque: "Abril já corresponde ao período de entrega da declaração de IRS, não a validação de faturas." },
    ],
    correta: 1,
    legalBasis: "Validacao de faturas no e-Fatura — até 15 de fevereiro",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-8",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Quando começa o período de entrega da declaração anual de IRS?",
    opcoes: [
      { texto: "1 de janeiro.", porque: "A entrega da declaração de IRS não começa em janeiro — o prazo só abre em abril." },
      { texto: "1 de marco.", porque: "Marco não é o mês de início da entrega — a declaração de IRS entrega-se a partir de 1 de abril." },
      { texto: "1 de abril.", porque: "O período de entrega da declaração de IRS começa a 1 de abril e termina a 30 de junho." },
      { texto: "1 de maio.", porque: "O prazo não começa em maio — a entrega da declaração de IRS inicia-se a 1 de abril." },
    ],
    correta: 2,
    legalBasis: "Entrega da declaração de IRS — de 1 de abril a 30 de junho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-9",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Qual é a data-limite para entregar a declaração anual de IRS?",
    opcoes: [
      { texto: "31 de maio.", porque: "Maio não é o último mês do prazo — a declaração de IRS pode ser entregue até 30 de junho." },
      { texto: "30 de junho.", porque: "O prazo de entrega da declaração de IRS termina a 30 de junho." },
      { texto: "31 de julho.", porque: "O prazo de entrega da declaração de IRS não vai até julho — termina a 30 de junho." },
      { texto: "30 de setembro.", porque: "Setembro está fora do período legal de entrega da declaração de IRS (que termina a 30 de junho)." },
    ],
    correta: 1,
    legalBasis: "Entrega da declaração de IRS — prazo final 30 de junho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-10",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A janela de pagamento mensal da Segurança Social para trabalhadores independentes abre em que dia?",
    opcoes: [
      { texto: "Dia 1 do mês.", porque: "O período de pagamento não começa no dia 1 — começa no dia 10." },
      { texto: "Dia 5 do mês.", porque: "O pagamento mensal da SS não começa no dia 5 — começa no dia 10." },
      { texto: "Dia 10 do mês.", porque: "O pagamento mensal da Segurança Social pode ser feito entre os dias 10 e 20 de cada mês." },
      { texto: "Dia 15 do mês.", porque: "O dia 15 está dentro da janela, mas não é o dia de abertura — o pagamento abre no dia 10." },
    ],
    correta: 2,
    legalBasis: "Pagamento mensal — Segurança Social (entre os dias 10 e 20)",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-11",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Um trabalhador independente que acaba de abrir atividade está isento de contribuições para a Segurança Social durante quanto tempo?",
    opcoes: [
      { texto: "6 meses.", porque: "O período de isenção não é de 6 meses — a lei prevê uma isenção de 12 meses." },
      { texto: "12 meses.", porque: "Os trabalhadores independentes estão isentos de contribuições para a SS durante os primeiros 12 meses de atividade." },
      { texto: "18 meses.", porque: "O período de isenção não é de 18 meses — é de 12 meses após abertura de atividade." },
      { texto: "24 meses.", porque: "A isenção não dura 24 meses — o período legal é de 12 meses." },
    ],
    correta: 1,
    legalBasis: "Art. 157.º Código Contributivo — isenção nos primeiros 12 meses de atividade",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-12",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Até quando é, em regra, pago o reembolso de IRS pela Autoridade Tributária?",
    opcoes: [
      { texto: "Até 30 de junho.", porque: "Junho ainda está dentro do período de entrega da declaração — o reembolso e tipicamente pago até 31 de julho." },
      { texto: "Até 31 de julho.", porque: "O reembolso de IRS é tipicamente pago até 31 de julho do ano de entrega da declaração." },
      { texto: "Até 30 de setembro.", porque: "Embora possam existir atrasos, o prazo tipico e 31 de julho, não setembro." },
      { texto: "Até 31 de dezembro.", porque: "O reembolso e habitualmente emitido até 31 de julho, muito antes de dezembro." },
    ],
    correta: 1,
    legalBasis: "Reembolso de IRS — tipicamente pago até 31 de julho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-13",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Que anexo da declaração Modelo 3 de IRS deve ser preenchido por um trabalhador independente (categoria B)?",
    opcoes: [
      { texto: "Anexo A.", porque: "O Anexo A destina-se a rendimentos do trabalho dependente (categoria A), não a rendimentos de atividade independente." },
      { texto: "Anexo B.", porque: "O Anexo B e o anexo da Modelo 3 destinado a rendimentos empresariais e profissionais (categoria B)." },
      { texto: "Anexo E.", porque: "O Anexo É destina-se a rendimentos de capitais (categoria E), não a rendimentos de trabalho independente." },
      { texto: "Anexo F.", porque: "O Anexo F destina-se a rendimentos prediais (categoria F), não a rendimentos de atividade independente." },
    ],
    correta: 1,
    legalBasis: "Modelo 3 — Anexo B para rendimentos da categoria B",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-14",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Um trabalhador independente deve abrir atividade nas Finanças em que momento?",
    opcoes: [
      { texto: "Antes de iniciar a atividade ou até 30 dias após o início.", porque: "A abertura de atividade deve ser feita antes de iniciar a prestação de serviços, ou no prazo máximo de 30 dias após o início." },
      { texto: "Até 60 dias após emitir o primeiro recibo verde.", porque: "O prazo não é de 60 dias após o primeiro recibo — a atividade deve estar aberta antes ou até 30 dias após o início." },
      { texto: "Até ao final do ano civil em que começou a trabalhar.", porque: "Esperar até ao final do ano e extemporaneo — a abertura deve ser feita antes ou até 30 dias após o início." },
      { texto: "Apenas quando ultrapassar 15 000 euros de faturação anual.", porque: "A obrigação de abrir atividade não depende de um limiar de faturação — é obrigatória antes ou até 30 dias após o início." },
    ],
    correta: 0,
    legalBasis: "Abertura de atividade — antes do início ou até 30 dias após",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-15",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Em que dia do mês é o prazo-limite para o primeiro pagamento por conta de IRS?",
    opcoes: [
      { texto: "Dia 10 de julho.", porque: "O limite não é dia 10 — os pagamentos por conta de IRS vencem no dia 20." },
      { texto: "Dia 15 de julho.", porque: "O limite não é dia 15 — o prazo é até ao dia 20 de julho." },
      { texto: "Dia 20 de julho.", porque: "O primeiro pagamento por conta de IRS deve ser efetuado até ao dia 20 de julho." },
      { texto: "Dia 31 de julho.", porque: "O limite não é o último dia do mês — e especificamente o dia 20 de julho." },
    ],
    correta: 2,
    legalBasis: "Pagamentos por conta de IRS — primeiro pagamento até 20 de julho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-16",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração trimestral de rendimentos a Segurança Social referente ao 2.º trimestre (abril a junho) deve ser feita até ao final de que mês?",
    opcoes: [
      { texto: "Junho.", porque: "Junho e o último mês do trimestre, não o prazo de entrega — a declaração deve ser feita até ao final de julho." },
      { texto: "Julho.", porque: "A declaração trimestral a SS referente ao 2.º trimestre (abr-jun) deve ser entregue até ao final de julho." },
      { texto: "Agosto.", porque: "Agosto não corresponde ao prazo — a declaração do 2.º trimestre entrega-se até ao final de julho." },
      { texto: "Setembro.", porque: "Setembro não corresponde ao prazo de entrega do 2.º trimestre (que é julho)." },
    ],
    correta: 1,
    legalBasis: "Declaração trimestral — Segurança Social (2.º trimestre)",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-17",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração trimestral de rendimentos a Segurança Social referente ao 3.º trimestre (julho a setembro) deve ser feita até ao final de que mês?",
    opcoes: [
      { texto: "Setembro.", porque: "Setembro e o último mês do trimestre, não o prazo de entrega — deve ser feita até ao final de outubro." },
      { texto: "Outubro.", porque: "A declaração trimestral a SS referente ao 3.º trimestre (jul-set) deve ser entregue até ao final de outubro." },
      { texto: "Novembro.", porque: "Novembro não corresponde ao prazo de entrega do 3.º trimestre (que é outubro)." },
      { texto: "Dezembro.", porque: "Dezembro não corresponde ao prazo de entrega do 3.º trimestre — o prazo é outubro." },
    ],
    correta: 1,
    legalBasis: "Declaração trimestral — Segurança Social (3.º trimestre)",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-18",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração trimestral de rendimentos a Segurança Social referente ao 4.º trimestre (outubro a dezembro) deve ser feita até ao final de que mês?",
    opcoes: [
      { texto: "Dezembro do mesmo ano.", porque: "Dezembro e o último mês do trimestre, não o prazo de entrega — a declaração faz-se até ao final de janeiro do ano seguinte." },
      { texto: "Janeiro do ano seguinte.", porque: "A declaração trimestral a SS referente ao 4.º trimestre (out-dez) deve ser entregue até ao final de janeiro do ano seguinte." },
      { texto: "Fevereiro do ano seguinte.", porque: "Fevereiro não corresponde ao prazo correto — o limite é o final de janeiro do ano seguinte." },
      { texto: "Marco do ano seguinte.", porque: "Marco não corresponde ao prazo da declaração do 4.º trimestre — o prazo é janeiro do ano seguinte." },
    ],
    correta: 1,
    legalBasis: "Declaração trimestral — Segurança Social (4.º trimestre)",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-19",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração de IRS automática, quando disponível, fica acessível a partir de que data?",
    opcoes: [
      { texto: "1 de marco.", porque: "A declaração automática não fica disponível em marco — está disponível a partir de 1 de abril." },
      { texto: "1 de abril.", porque: "A declaração de IRS automática fica disponível a partir de 1 de abril, coincidindo com o início do período de entrega." },
      { texto: "1 de maio.", porque: "A declaração automática já está disponível desde 1 de abril, não apenas a partir de maio." },
      { texto: "15 de fevereiro.", porque: "Fevereiro corresponde ao prazo de validação de faturas no e-Fatura, não ao início da declaração automática." },
    ],
    correta: 1,
    legalBasis: "Declaração automática de IRS — disponível a partir de 1 de abril",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-20",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Quantos pagamentos por conta de IRS existem por ano para quem não faz retenção na fonte?",
    opcoes: [
      { texto: "1 pagamento.", porque: "Existe mais do que um pagamento por conta — são 3 ao longo do ano." },
      { texto: "2 pagamentos.", porque: "Não são 2 — os pagamentos por conta de IRS são 3 (julho, setembro e dezembro)." },
      { texto: "3 pagamentos.", porque: "Ha 3 pagamentos por conta de IRS por ano, em julho, setembro e dezembro." },
      { texto: "4 pagamentos.", porque: "Não são 4 — os pagamentos por conta são 3 (julho, setembro e dezembro)." },
    ],
    correta: 2,
    legalBasis: "Pagamentos por conta de IRS — 3 prestações (julho, setembro, dezembro)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-21",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração periódica de IVA no regime trimestral referente ao 2.º trimestre (abril a junho) deve ser entregue até ao dia 20 de que mês?",
    opcoes: [
      { texto: "Julho.", porque: "Julho não é o mês correto — a declaração do 2.º trimestre é entregue até ao dia 20 de agosto." },
      { texto: "Agosto.", porque: "A declaração periódica de IVA trimestral do 2.º trimestre deve ser entregue até ao dia 20 de agosto." },
      { texto: "Setembro.", porque: "Setembro não corresponde ao prazo — o prazo é até 20 de agosto." },
      { texto: "Outubro.", porque: "Outubro corresponde ao prazo do 3.º trimestre, não do 2.º." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (trimestral) — 2.º trimestre",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-22",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração periódica de IVA no regime trimestral referente ao 3.º trimestre (julho a setembro) deve ser entregue até ao dia 20 de que mês?",
    opcoes: [
      { texto: "Outubro.", porque: "Outubro não é o mês correto — a declaração do 3.º trimestre é entregue até ao dia 20 de novembro." },
      { texto: "Novembro.", porque: "A declaração periódica de IVA trimestral do 3.º trimestre deve ser entregue até ao dia 20 de novembro." },
      { texto: "Dezembro.", porque: "Dezembro não corresponde ao prazo do 3.º trimestre — o prazo é novembro." },
      { texto: "Janeiro do ano seguinte.", porque: "Janeiro corresponde ao prazo do 4.º trimestre, não do 3.º." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (trimestral) — 3.º trimestre",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-23",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A declaração periódica de IVA no regime trimestral referente ao 4.º trimestre (outubro a dezembro) deve ser entregue até ao dia 20 de que mês?",
    opcoes: [
      { texto: "Janeiro do ano seguinte.", porque: "Janeiro não é o mês correto — a declaração do 4.º trimestre é entregue até ao dia 20 de fevereiro do ano seguinte." },
      { texto: "Fevereiro do ano seguinte.", porque: "A declaração periódica de IVA trimestral do 4.º trimestre deve ser entregue até ao dia 20 de fevereiro do ano seguinte." },
      { texto: "Marco do ano seguinte.", porque: "Marco não corresponde ao prazo do 4.º trimestre — o prazo é fevereiro." },
      { texto: "Dezembro do mesmo ano.", porque: "Dezembro e o último mês do trimestre, não o prazo de entrega — o prazo é fevereiro do ano seguinte." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (trimestral) — 4.º trimestre",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-24",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Qual é o mês do segundo pagamento por conta de IRS?",
    opcoes: [
      { texto: "Agosto.", porque: "O segundo pagamento por conta não é em agosto — e em setembro." },
      { texto: "Setembro.", porque: "O segundo pagamento por conta de IRS deve ser efetuado até ao dia 20 de setembro." },
      { texto: "Outubro.", porque: "Outubro não corresponde a nenhum dos tres pagamentos por conta de IRS." },
      { texto: "Novembro.", porque: "Novembro não é o mês do segundo pagamento por conta — e setembro." },
    ],
    correta: 1,
    legalBasis: "Pagamentos por conta de IRS — segundo pagamento até 20 de setembro",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-25",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Qual é o mês do terceiro e último pagamento por conta de IRS?",
    opcoes: [
      { texto: "Outubro.", porque: "O terceiro pagamento por conta não é em outubro — e em dezembro." },
      { texto: "Novembro.", porque: "Novembro não é o mês correto — o terceiro pagamento por conta e em dezembro." },
      { texto: "Dezembro.", porque: "O terceiro pagamento por conta de IRS deve ser efetuado até ao dia 20 de dezembro." },
      { texto: "Janeiro do ano seguinte.", porque: "O terceiro pagamento por conta e ainda no mesmo ano fiscal, em dezembro, não em janeiro." },
    ],
    correta: 2,
    legalBasis: "Pagamentos por conta de IRS — terceiro pagamento até 20 de dezembro",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-26",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Se um trabalhador independente abriu atividade a 1 de marco, quando termina a isenção de contribuições para a Segurança Social?",
    opcoes: [
      { texto: "A 28 de fevereiro do ano seguinte.", porque: "A isenção dura 12 meses a contar da data de abertura de atividade, ou seja, termina no final de fevereiro do ano seguinte." },
      { texto: "A 31 de agosto do mesmo ano.", porque: "6 meses após a abertura não corresponde ao período legal de isenção, que é de 12 meses." },
      { texto: "A 31 de dezembro do mesmo ano.", porque: "A isenção não termina no final do ano civil — dura 12 meses a contar da abertura." },
      { texto: "A 1 de marco do terceiro ano.", porque: "A isenção não dura 24 meses — dura apenas 12 meses." },
    ],
    correta: 0,
    legalBasis: "Art. 157.º Código Contributivo — isenção nos primeiros 12 meses",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-27",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Quantos meses dura o período de entrega da declaração de IRS?",
    opcoes: [
      { texto: "1 mês.", porque: "O período não é de apenas 1 mês — a declaração pode ser entregue durante 3 meses (abril, maio e junho)." },
      { texto: "2 meses.", porque: "O período de entrega não é de 2 meses — dura 3 meses completos." },
      { texto: "3 meses.", porque: "O período de entrega da declaração de IRS dura 3 meses: de 1 de abril a 30 de junho." },
      { texto: "6 meses.", porque: "O período de entrega não é de 6 meses — é de 3 meses (abril a junho)." },
    ],
    correta: 2,
    legalBasis: "Entrega da declaração de IRS — 3 meses (1 abril a 30 junho)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-28",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "No regime de IVA trimestral, quantas declarações periódicas de IVA são entregues por ano?",
    opcoes: [
      { texto: "2 declarações.", porque: "No regime trimestral não são 2 — são 4 declarações por ano (uma por trimestre)." },
      { texto: "4 declarações.", porque: "No regime trimestral de IVA, entregam-se 4 declarações periódicas por ano, uma por cada trimestre." },
      { texto: "6 declarações.", porque: "6 declarações não correspondem ao regime trimestral — 4 e o número correto." },
      { texto: "12 declarações.", porque: "12 declarações correspondem ao regime mensal, não ao trimestral." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA — regime trimestral (4 por ano)",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-29",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "No regime de IVA mensal, quantas declarações periódicas de IVA são entregues por ano?",
    opcoes: [
      { texto: "4 declarações.", porque: "4 declarações correspondem ao regime trimestral, não ao mensal." },
      { texto: "6 declarações.", porque: "6 declarações não correspondem a nenhum dos regimes de IVA previstos." },
      { texto: "10 declarações.", porque: "Não são 10 — no regime mensal entregam-se 12 declarações por ano." },
      { texto: "12 declarações.", porque: "No regime mensal de IVA, entregam-se 12 declarações periódicas por ano, uma por cada mês." },
    ],
    correta: 3,
    legalBasis: "Declaração periódica de IVA — regime mensal (12 por ano)",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-30",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "A partir de quando ficam disponíveis as declarações de IRS automaticas?",
    opcoes: [
      { texto: "1 de marco.", porque: "As declarações automaticas não ficam disponíveis em marco — ficam a partir de 1 de abril." },
      { texto: "15 de marco.", porque: "Não ficam disponíveis em meados de marco — o início e 1 de abril." },
      { texto: "1 de abril.", porque: "As declarações de IRS automaticas ficam disponíveis a partir de 1 de abril." },
      { texto: "15 de abril.", porque: "A disponibilização e a 1 de abril, não a 15." },
    ],
    correta: 2,
    legalBasis: "IRS automático — disponível a partir de 1 de abril",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-31",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Se um trabalhador independente não entregar a declaração de IRS dentro do prazo, o que pode acontecer?",
    opcoes: [
      { texto: "Nada — a AT entrega automaticamente.", porque: "A declaração automática só se aplica em casos simples; na maioria das situações de categoria B, a falta de entrega gera coima." },
      { texto: "Recebe uma coima que pode variar entre 150 e 3750 euros.", porque: "A entrega tardia ou a falta de entrega da declaração de IRS pode resultar numa coima entre 150 e 3750 euros." },
      { texto: "É automaticamente inscrito no regime simplificado.", porque: "A falta de entrega não implica qualquer alteração de regime — implica a aplicação de coima." },
      { texto: "Perde o direito a deduções apenas nesse ano.", porque: "A consequência principal e a coima, não a perda de deduções." },
    ],
    correta: 1,
    legalBasis: "Coima por falta ou atraso na entrega da declaração de IRS",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-32",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "Quando abre a atividade, o trabalhador independente deve inscrever-se também na Segurança Social?",
    opcoes: [
      { texto: "Não, a inscrição é automática quando abre atividade nas Finanças.", porque: "Desde 2019, a comunicação entre a AT e a SS é automática — ao abrir atividade nas Finanças, a SS e notificada." },
      { texto: "Sim, tem de se deslocar pessoalmente a uma loja da SS.", porque: "Já não é necessário deslocar-se — a comunicação é feita automaticamente pela AT a SS." },
      { texto: "Sim, mas apenas após 12 meses de atividade.", porque: "A inscrição na SS é automática no momento da abertura, embora o pagamento de contribuições só comece após 12 meses." },
      { texto: "Sim, é tem de enviar carta registada a SS.", porque: "Não é necessário carta — a comunicação é automática entre AT e SS." },
    ],
    correta: 0,
    legalBasis: "Inscricao automática na SS via comunicação AT — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-33",
    categoria: "prazos",
    dificuldade: 1,
    pergunta: "O que acontece se um trabalhador independente não pagar a contribuição da Segurança Social dentro do prazo?",
    opcoes: [
      { texto: "Não há qualquer consequência se pagar no mês seguinte.", porque: "Ha consequências — o atraso gera juros de mora e pode gerar dívida a Segurança Social." },
      { texto: "E-lhe cobrada uma coima fixa de 500 euros.", porque: "Não há coima fixa de 500 euros — as consequências são juros de mora sobre o valor em dívida." },
      { texto: "São cobrados juros de mora sobre o valor em atraso.", porque: "O atraso no pagamento da contribuição gera juros de mora e pode constituir dívida a Segurança Social." },
      { texto: "A atividade e automaticamente encerrada.", porque: "A atividade não é encerrada por falta de pagamento — são aplicados juros de mora." },
    ],
    correta: 2,
    legalBasis: "Juros de mora por atraso no pagamento — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-34",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de janeiro deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de fevereiro.", porque: "Fevereiro não é o mês correto — no regime mensal, a declaração é entregue até ao dia 10 do 2.º mês seguinte." },
      { texto: "10 de marco.", porque: "No regime mensal, a declaração de IVA referente a janeiro deve ser entregue até ao dia 10 de marco (2.º mês após o mês de referência)." },
      { texto: "20 de marco.", porque: "O prazo no regime mensal e até ao dia 10, não dia 20 — dia 20 aplica-se ao regime trimestral." },
      { texto: "20 de fevereiro.", porque: "Fevereiro não é o mês correto e o dia 20 aplica-se ao regime trimestral, não ao mensal." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — até ao dia 10 do 2.º mês seguinte",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-35",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de junho deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de julho.", porque: "Julho não é o 2.º mês após junho — a declaração deve ser entregue até 10 de agosto." },
      { texto: "10 de agosto.", porque: "No regime mensal, a declaração de IVA referente a junho deve ser entregue até ao dia 10 de agosto." },
      { texto: "20 de agosto.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de setembro.", porque: "Setembro e o 3.º mês após junho, não o 2.º — o prazo é agosto." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a junho",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-36",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de novembro deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de dezembro.", porque: "Dezembro não é o 2.º mês após novembro — a declaração deve ser entregue até 10 de janeiro do ano seguinte." },
      { texto: "10 de janeiro do ano seguinte.", porque: "No regime mensal, a declaração de IVA referente a novembro deve ser entregue até ao dia 10 de janeiro do ano seguinte." },
      { texto: "20 de janeiro do ano seguinte.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de fevereiro do ano seguinte.", porque: "Fevereiro seria o 3.º mês após novembro — o prazo é janeiro (2.º mês após)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a novembro",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-37",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente pretende passar do regime trimestral para o regime mensal de IVA, até quando deve comunicar essa alteração a AT?",
    opcoes: [
      { texto: "Até 31 de janeiro do ano em que pretende iniciar o novo regime.", porque: "A alteração de regime de IVA deve ser comunicada até 31 de janeiro para produzir efeitos nesse ano." },
      { texto: "Até 31 de marco do ano em que pretende iniciar o novo regime.", porque: "O prazo não é marco — a comunicação deve ser feita até 31 de janeiro." },
      { texto: "A qualquer momento, com efeito imediato.", porque: "Não é possível alterar o regime a qualquer momento — há prazos específicos (até 31 de janeiro)." },
      { texto: "Até 30 de novembro do ano anterior.", porque: "O prazo não é novembro do ano anterior — e até 31 de janeiro do ano pretendido." },
    ],
    correta: 0,
    legalBasis: "Alteracao de regime de IVA — comunicação até 31 de janeiro",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-38",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Qual é a diferença entre o prazo de entrega da declaração de IVA no regime trimestral e no regime mensal?",
    opcoes: [
      { texto: "No trimestral e até ao dia 20; no mensal e até ao dia 10.", porque: "No regime trimestral a declaração entrega-se até ao dia 20 do 2.º mês após o trimestre; no mensal, até ao dia 10 do 2.º mês após o mês de referência." },
      { texto: "No trimestral e até ao dia 10; no mensal e até ao dia 20.", porque: "É ao contrário — o regime trimestral tem prazo até ao dia 20 e o mensal até ao dia 10." },
      { texto: "Ambos os regimes tem prazo até ao dia 15.", porque: "Não existe prazo de dia 15 — trimestral e dia 20 e mensal e dia 10." },
      { texto: "Não há diferença — ambos são até ao dia 20.", porque: "Ha diferença — no regime mensal o prazo é dia 10, não dia 20." },
    ],
    correta: 0,
    legalBasis: "Declaração periódica de IVA — trimestral (dia 20) vs mensal (dia 10)",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-39",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Após o período de isenção de 12 meses na Segurança Social, quando deve o trabalhador independente fazer a primeira declaração trimestral?",
    opcoes: [
      { texto: "No mês imediatamente a seguir ao fim da isenção.", porque: "A primeira declaração trimestral é feita no final do mês seguinte ao trimestre em que termina a isenção, e não no mês seguinte a isenção." },
      { texto: "Até ao final do mês seguinte ao trimestre em que terminou a isenção.", porque: "Após terminar a isenção de 12 meses, o trabalhador deve fazer a primeira declaração trimestral até ao final do mês seguinte ao trimestre correspondente." },
      { texto: "Apenas no ano seguinte ao fim da isenção.", porque: "Não é necessário esperar pelo ano seguinte — a primeira declaração é feita no final do mês seguinte ao trimestre em que terminou a isenção." },
      { texto: "Seis meses após o fim da isenção.", porque: "Não há um prazo de 6 meses — a declaração segue o calendário trimestral normal." },
    ],
    correta: 1,
    legalBasis: "Primeira declaração trimestral após isenção — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-40",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente cessar atividade, em que prazo deve comunicar a cessação a Autoridade Tributária?",
    opcoes: [
      { texto: "No prazo de 30 dias a contar da data de cessação.", porque: "A cessação de atividade deve ser comunicada a AT no prazo de 30 dias a contar da data em que ocorreu." },
      { texto: "No prazo de 60 dias a contar da data de cessação.", porque: "O prazo não é de 60 dias — é de 30 dias a contar da cessação." },
      { texto: "Até ao final do ano civil em que cessou.", porque: "Não é necessário esperar pelo final do ano — o prazo é de 30 dias após a cessação." },
      { texto: "Até a entrega da declaração de IRS do ano seguinte.", porque: "A comunicação de cessação tem prazo próprio (30 dias) e não coincide com a entrega do IRS." },
    ],
    correta: 0,
    legalBasis: "Cessacao de atividade — comunicação no prazo de 30 dias",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-41",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente pretende renunciar a isenção de IVA do Art. 53.º, quando deve apresentar a declaração de alterações?",
    opcoes: [
      { texto: "A qualquer momento, com efeitos imediatos.", porque: "A renúncia pode ser feita a qualquer momento, mas produz efeitos a partir do período de imposto seguinte." },
      { texto: "Até 31 de janeiro do ano em que pretende ficar enquadrado.", porque: "A renúncia pode ser feita em janeiro, mas também noutras alturas — o efeito depende do momento da apresentação." },
      { texto: "Em janeiro, com efeito a partir de marco.", porque: "O momento de efeito não depende fixamente de janeiro para marco — depende do período seguinte a apresentação." },
      { texto: "Pode ser apresentada a qualquer momento, com efeitos a partir do período de imposto seguinte.", porque: "A declaração de renúncia a isenção de IVA pode ser apresentada a qualquer momento, produzindo efeitos a partir do período seguinte." },
    ],
    correta: 3,
    legalBasis: "Art. 53.º e 55.º CIVA — renúncia a isenção de IVA",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-42",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "A nota de liquidação de IRS é enviada pela AT até quando?",
    opcoes: [
      { texto: "Até 30 de junho.", porque: "A nota de liquidação é emitida após o processamento, tipicamente até 31 de julho, não junho." },
      { texto: "Até 31 de julho.", porque: "A nota de liquidação de IRS é tipicamente emitida pela AT até 31 de julho." },
      { texto: "Até 30 de setembro.", porque: "Embora possam existir atrasos, o prazo tipico e 31 de julho." },
      { texto: "Até 31 de dezembro.", porque: "A nota de liquidação é emitida muito antes de dezembro — tipicamente até julho." },
    ],
    correta: 1,
    legalBasis: "Nota de liquidação de IRS — tipicamente emitida até 31 de julho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-43",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se a declaração de IRS resultar em imposto a pagar (em vez de reembolso), até quando deve ser feito o pagamento?",
    opcoes: [
      { texto: "Até ao final do mês seguinte ao da notificação da nota de liquidação.", porque: "O pagamento deve ser efetuado até ao final do mês seguinte ao da notificação da nota de liquidação." },
      { texto: "Até 30 de setembro, independentemente da data da nota de liquidação.", porque: "O prazo não é fixo em setembro — depende da data em que a nota de liquidação e notificada." },
      { texto: "No prazo de 15 dias após a nota de liquidação.", porque: "O prazo não é de 15 dias — e até ao final do mês seguinte ao da notificação." },
      { texto: "Até 31 de dezembro do ano corrente.", porque: "Não é obrigatoriamente até dezembro — o prazo depende da data da notificação." },
    ],
    correta: 0,
    legalBasis: "Pagamento de IRS — até ao final do mês seguinte a notificação",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-44",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente alterar a morada fiscal, em que prazo deve comunicar a alteração a AT?",
    opcoes: [
      { texto: "No prazo de 15 dias a contar da alteração.", porque: "O prazo para comunicar alteração de morada é de 60 dias, não de 15." },
      { texto: "No prazo de 30 dias a contar da alteração.", porque: "O prazo não é de 30 dias — a lei prevê 60 dias para a comunicação de alteração de morada fiscal." },
      { texto: "No prazo de 60 dias a contar da alteração.", porque: "A alteração de morada fiscal deve ser comunicada a AT no prazo de 60 dias." },
      { texto: "Até a próxima entrega da declaração de IRS.", porque: "Não é aceitável esperar pela próxima declaração de IRS — a comunicação deve ser feita no prazo de 60 dias." },
    ],
    correta: 2,
    legalBasis: "Alteracao de morada fiscal — comunicação no prazo de 60 dias",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-45",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "A declaração trimestral a Segurança Social pode ser entregue em que plataforma?",
    opcoes: [
      { texto: "Apenas presencialmente num balcão da Segurança Social.", porque: "A declaração trimestral já não exige deslocação presencial — pode ser feita online na Segurança Social Direta." },
      { texto: "Na plataforma Segurança Social Direta (online).", porque: "A declaração trimestral é feita online na plataforma Segurança Social Direta." },
      { texto: "No Portal das Finanças.", porque: "O Portal das Finanças e da AT, não da Segurança Social — a declaração faz-se na Segurança Social Direta." },
      { texto: "Por email para a Segurança Social.", porque: "Não é possível entregar a declaração trimestral por email — deve ser feita na Segurança Social Direta." },
    ],
    correta: 1,
    legalBasis: "Declaração trimestral — Segurança Social Direta",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-46",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Um trabalhador independente que esteve isento de IVA ao abrigo do Art. 53.º e que ultrapassou o limiar de 15 000 euros, em que prazo deve apresentar a declaração de alterações?",
    opcoes: [
      { texto: "No prazo de 15 dias após ultrapassar o limiar.", porque: "O prazo para apresentar a declaração de alterações quando se ultrapassa o limiar de isenção de IVA não é de 15 dias." },
      { texto: "Até ao final do mês seguinte aquele em que ultrapassou o limiar.", porque: "A obrigação de apresentar declaração de alterações surge quando se verifica que o volume de negocios ultrapassa o limiar, devendo ser feita no prazo previsto na lei." },
      { texto: "No prazo de 30 dias após ultrapassar o limiar.", porque: "Ao ultrapassar o limiar de isenção, deve ser apresentada declaração de alterações no prazo legalmente previsto." },
      { texto: "Apenas na declaração de IRS do ano seguinte.", porque: "A comunicação de alteração de regime de IVA não pode esperar pela declaração de IRS — há prazos específicos." },
    ],
    correta: 1,
    legalBasis: "Art. 53.º CIVA — obrigação de comunicar ultrapassagem do limiar de isenção",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-47",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de marco deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de abril.", porque: "Abril não é o 2.º mês após marco — a declaração deve ser entregue até 10 de maio." },
      { texto: "10 de maio.", porque: "No regime mensal, a declaração de IVA referente a marco deve ser entregue até ao dia 10 de maio." },
      { texto: "20 de maio.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de junho.", porque: "Junho e o 3.º mês após marco — o prazo é maio (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a marco",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-48",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de setembro deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de outubro.", porque: "Outubro não é o 2.º mês após setembro — a declaração deve ser entregue até 10 de novembro." },
      { texto: "20 de novembro.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de novembro.", porque: "No regime mensal, a declaração de IVA referente a setembro deve ser entregue até ao dia 10 de novembro." },
      { texto: "10 de dezembro.", porque: "Dezembro e o 3.º mês após setembro — o prazo é novembro (2.º mês)." },
    ],
    correta: 2,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a setembro",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-49",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Um trabalhador independente que faz retenção na fonte nos seus recibos verdes está obrigado a fazer pagamentos por conta de IRS?",
    opcoes: [
      { texto: "Sim, sempre, independentemente de fazer retenção.", porque: "Quem faz retenção na fonte pode estar dispensado de pagamentos por conta, dependendo do cálculo." },
      { texto: "Não, nunca — a retenção substitui os pagamentos por conta.", porque: "A retenção na fonte pode reduzir ou eliminar os pagamentos por conta, mas não é correto dizer 'nunca' de forma absoluta." },
      { texto: "Depende — se a retenção cobrir o imposto estimado, pode ficar dispensado.", porque: "Os pagamentos por conta podem não ser devidos se a retenção na fonte já cobrir o imposto estimado." },
      { texto: "Sim, mas apenas o primeiro dos tres pagamentos.", porque: "Não existe regra que obrigue apenas ao primeiro pagamento — a obrigação depende do cálculo global." },
    ],
    correta: 2,
    legalBasis: "Pagamentos por conta de IRS — relação com retenção na fonte",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-50",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente pretender alterar o código de atividade (CAE/CIRS) nas Finanças, em que prazo deve comunicar a alteração?",
    opcoes: [
      { texto: "No prazo de 15 dias a contar da alteração.", porque: "O prazo para comunicar alterações de atividade a AT é de 15 dias a contar do evento que originou a alteração." },
      { texto: "No prazo de 30 dias a contar da alteração.", porque: "O prazo previsto para este tipo de comunicação é de 15 dias, não de 30." },
      { texto: "Até ao final do trimestre em curso.", porque: "Não existe um prazo trimestral para está comunicação — o prazo é de 15 dias." },
      { texto: "Até a próxima declaração de IRS.", porque: "A comunicação de alterações não pode esperar pela declaração de IRS — deve ser feita no prazo de 15 dias." },
    ],
    correta: 0,
    legalBasis: "Comunicacao de alterações a AT — prazo de 15 dias",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-51",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Qual é a periodicidade da declaração trimestral de rendimentos a Segurança Social?",
    opcoes: [
      { texto: "Mensal.", porque: "A declaração de rendimentos a SS não é mensal — e trimestral." },
      { texto: "Trimestral, nos meses de janeiro, abril, julho e outubro.", porque: "A declaração trimestral é feita até ao final dos meses de janeiro, abril, julho e outubro, reportando o trimestre anterior." },
      { texto: "Semestral, nos meses de janeiro e julho.", porque: "A periodicidade não é semestral — e trimestral." },
      { texto: "Anual, no mês de janeiro.", porque: "A declaração não é anual — é feita trimestralmente." },
    ],
    correta: 1,
    legalBasis: "Declaração trimestral — Segurança Social (periodicidade)",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-52",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "O que acontece se um trabalhador independente não entregar a declaração trimestral de rendimentos a Segurança Social no prazo?",
    opcoes: [
      { texto: "A Segurança Social calcula automaticamente a contribuição com base no último rendimento declarado.", porque: "Se a declaração trimestral não for entregue, a SS pode fixar a contribuição com base em elementos disponíveis, incluindo o rendimento do trimestre anterior." },
      { texto: "É aplicada uma coima e a atividade e suspensa.", porque: "A atividade não é suspensa — a SS fixa a contribuição com base em dados disponíveis." },
      { texto: "O trabalhador fica automaticamente isento de contribuições nesse trimestre.", porque: "A falta de declaração não confere isenção — a SS calcula a contribuição com base em dados anteriores." },
      { texto: "A Segurança Social não toma qualquer medida até ao final do ano.", porque: "A SS não espera pelo final do ano — atua no momento, fixando a contribuição com dados anteriores." },
    ],
    correta: 0,
    legalBasis: "Falta de declaração trimestral — fixacao pela SS",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-53",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Os pagamentos por conta de IRS referem-se ao imposto de que ano?",
    opcoes: [
      { texto: "Ao imposto do ano anterior.", porque: "Os pagamentos por conta não se referem ao ano anterior — são adiantamentos do imposto do ano corrente." },
      { texto: "Ao imposto do ano corrente (em que são efetuados).", porque: "Os pagamentos por conta são adiantamentos do imposto estimado para o ano corrente em que são efetuados." },
      { texto: "Ao imposto do ano seguinte.", porque: "Não são adiantamentos do ano seguinte — referem-se ao imposto do ano em que ocorrem." },
      { texto: "Ao imposto de dois anos atrás.", porque: "Os pagamentos por conta não se referem a dois anos atrás — são do ano corrente." },
    ],
    correta: 1,
    legalBasis: "Pagamentos por conta de IRS — adiantamento do imposto do ano corrente",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-54",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente iniciar atividade em outubro, quando termina a sua isenção de contribuições para a Segurança Social?",
    opcoes: [
      { texto: "Em dezembro do mesmo ano.", porque: "A isenção não termina no final do ano civil — dura 12 meses a contar da data de abertura." },
      { texto: "Em abril do ano seguinte.", porque: "Abril do ano seguinte corresponde a 6 meses, não a 12." },
      { texto: "Em setembro do ano seguinte.", porque: "A isenção de 12 meses a contar de outubro termina no final de setembro do ano seguinte." },
      { texto: "Em outubro do segundo ano seguinte.", porque: "Isso corresponderia a 24 meses — a isenção é de apenas 12 meses." },
    ],
    correta: 2,
    legalBasis: "Art. 157.º Código Contributivo — isenção de 12 meses",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-55",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente abriu atividade em julho e a isenção de SS termina em junho do ano seguinte, quando deve fazer a primeira declaração trimestral?",
    opcoes: [
      { texto: "Até ao final de julho do ano seguinte (referente ao 2.º trimestre abr-jun).", porque: "Se a isenção termina em junho, o primeiro trimestre completo sob contribuições começa a partir de julho, mas deve declarar o trimestre em que terminou a isenção (2.º trimestre abr-jun) até ao final de julho." },
      { texto: "Até ao final de outubro do ano seguinte (referente ao 3.º trimestre jul-set).", porque: "O trabalhador deve declarar o trimestre em que terminou a isenção, não esperar pelo trimestre seguinte." },
      { texto: "Até ao final de janeiro do segundo ano seguinte.", porque: "Esperar até janeiro seria demasiado tarde — a primeira declaração deve ser feita logo após o fim da isenção." },
      { texto: "Não precisa de fazer declaração trimestral no primeiro ano após a isenção.", porque: "A declaração trimestral é obrigatória após o fim da isenção." },
    ],
    correta: 0,
    legalBasis: "Primeira declaração trimestral após isenção de 12 meses — SS",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-56",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Para efeitos de IRS, o ano fiscal em Portugal coincide com que período?",
    opcoes: [
      { texto: "De 1 de abril a 31 de marco do ano seguinte.", porque: "Em Portugal o ano fiscal coincide com o ano civil, não com o período abril-marco." },
      { texto: "De 1 de janeiro a 31 de dezembro.", porque: "O ano fiscal em Portugal coincide com o ano civil, de 1 de janeiro a 31 de dezembro." },
      { texto: "De 1 de julho a 30 de junho do ano seguinte.", porque: "Este período não corresponde ao ano fiscal portugues — o ano fiscal e o ano civil." },
      { texto: "De 1 de outubro a 30 de setembro do ano seguinte.", porque: "Em Portugal, o ano fiscal e o ano civil (janeiro a dezembro), não outubro a setembro." },
    ],
    correta: 1,
    legalBasis: "Ano fiscal em Portugal — coincide com o ano civil (janeiro a dezembro)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-57",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente emitir um recibo verde com erro, em que prazo pode anula-lo?",
    opcoes: [
      { texto: "Não é possível anular um recibo verde já emitido.", porque: "É possível anular recibos verdes emitidos com erro, desde que feito no prazo legal." },
      { texto: "Até ao final do mês seguinte ao da emissão.", porque: "O prazo de anulação não é o final do mês seguinte — há um prazo específico para este tipo de correção." },
      { texto: "Até a entrega da declaração de IRS.", porque: "A anulação do recibo não está condicionada a entrega da declaração de IRS — há um prazo independente." },
      { texto: "No prazo estabelecido pela AT, geralmente até ao final do ano civil ou após comunicação ao adquirente.", porque: "A anulação de recibos verdes obedece a regras específicas da AT, incluindo a comunicação ao adquirente e limites temporais." },
    ],
    correta: 3,
    legalBasis: "Anulacao de recibos verdes — regras e prazos da AT",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-58",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se a Autoridade Tributária detetar um erro na declaração de IRS, em quantos anos pode proceder a uma liquidação adicional?",
    opcoes: [
      { texto: "Até 2 anos após o prazo de entrega.", porque: "O prazo de caducidade do direito a liquidação não é de 2 anos — é de 4 anos." },
      { texto: "Até 4 anos após o prazo de entrega.", porque: "A AT pode proceder a liquidação adicional no prazo de caducidade de 4 anos após o termo do prazo de entrega da declaração." },
      { texto: "Até 8 anos após o prazo de entrega.", porque: "O prazo geral de caducidade não é de 8 anos — é de 4 anos." },
      { texto: "Sem limite temporal.", porque: "O direito a liquidação não é imprescritível — caduca em 4 anos." },
    ],
    correta: 1,
    legalBasis: "Caducidade do direito a liquidação — 4 anos (Art. 45.º LGT)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-59",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Até quando deve um trabalhador independente guardar os documentos comprovativos de rendimentos e despesas?",
    opcoes: [
      { texto: "Até ao final do ano seguinte.", porque: "Guardar apenas até ao ano seguinte e insuficiente — o prazo mínimo de conservacao é mais longo." },
      { texto: "Durante 4 anos após a entrega da declaração.", porque: "Os documentos devem ser guardados durante pelo menos 4 anos, coincidindo com o prazo de caducidade do direito a liquidação." },
      { texto: "Durante 2 anos após a entrega da declaração.", porque: "2 anos e insuficiente — o prazo de conservacao de documentos é de pelo menos 4 anos." },
      { texto: "Indefinidamente, sem limite.", porque: "Não é necessário guardar indefinidamente — o prazo mínimo é de 4 anos após a declaração." },
    ],
    correta: 1,
    legalBasis: "Conservacao de documentos — 4 anos (prazo de caducidade)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-60",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente não pagar o IVA no prazo, que consequência imediata pode enfrentar?",
    opcoes: [
      { texto: "Encerramento automático da atividade.", porque: "A atividade não é encerrada automaticamente por falta de pagamento de IVA." },
      { texto: "Juros compensatórios e eventual procedimento de cobrança coerciva.", porque: "O não pagamento de IVA no prazo gera juros compensatórios e pode levar a cobrança coerciva pela AT." },
      { texto: "Apenas um aviso sem consequências financeiras.", porque: "Não se trata de mero aviso — há consequências financeiras como juros é possível cobrança coerciva." },
      { texto: "Perda automática da isenção do Art. 53.º.", porque: "A perda de isenção do Art. 53.º está ligada a ultrapassagem do limiar de faturação, não a falta de pagamento de IVA." },
    ],
    correta: 1,
    legalBasis: "Falta de pagamento de IVA — juros compensatórios e cobrança coerciva",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-61",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "A retenção na fonte de IRS feita por um trabalhador independente nos seus recibos é entregue ao Estado por quem?",
    opcoes: [
      { texto: "Pelo próprio trabalhador independente, mensalmente.", porque: "A retenção na fonte é entregue pela entidade pagadora (cliente), não pelo trabalhador independente que emitiu o recibo." },
      { texto: "Pela entidade pagadora (cliente) que recebeu o recibo.", porque: "A retenção na fonte é entregue ao Estado pela entidade pagadora, que a desconta no momento do pagamento ao trabalhador." },
      { texto: "Pela Segurança Social.", porque: "A Segurança Social não intervem na retenção de IRS — está é entregue pela entidade pagadora." },
      { texto: "Não é entregue — fica retida pelo trabalhador.", porque: "A retenção é descontada pela entidade pagadora é entregue ao Estado, não ficando retida pelo trabalhador." },
    ],
    correta: 1,
    legalBasis: "Retenção na fonte — entregue pela entidade pagadora",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-62",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente quer reclamar de uma nota de liquidação de IRS, qual é o prazo para apresentar reclamação graciosa?",
    opcoes: [
      { texto: "30 dias após a notificação.", porque: "O prazo para reclamação graciosa não é de 30 dias — é mais alargado." },
      { texto: "60 dias após a notificação.", porque: "O prazo para reclamação graciosa não é de 60 dias — a lei prevê um prazo de 120 dias." },
      { texto: "120 dias após o termo do prazo de pagamento voluntário.", porque: "A reclamação graciosa pode ser apresentada no prazo de 120 dias após o termo do prazo de pagamento voluntário." },
      { texto: "1 ano após a notificação.", porque: "O prazo não é de 1 ano — é de 120 dias após o termo do prazo de pagamento voluntário." },
    ],
    correta: 2,
    legalBasis: "Reclamacao graciosa — prazo de 120 dias (Art. 70.º CPPT)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-63",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "A declaração de substituição do IRS (para corrigir erros na declaração já entregue) pode ser apresentada em que prazo?",
    opcoes: [
      { texto: "Apenas durante o período de entrega (até 30 de junho).", porque: "A declaração de substituição pode ser entregue após o período normal, não estando limitada a 30 de junho." },
      { texto: "Até 30 dias após o final do período de entrega.", porque: "O prazo não é de apenas 30 dias após — é mais alargado." },
      { texto: "Até ao final do prazo de caducidade (4 anos), mas com consequências diferentes consoante o momento.", porque: "A declaração de substituição pode ser apresentada dentro do prazo de caducidade (4 anos), embora as consequências variem." },
      { texto: "Nunca — uma vez entregue, a declaração não pode ser alterada.", porque: "É possível corrigir a declaração de IRS atraves de declaração de substituição dentro do prazo legal." },
    ],
    correta: 2,
    legalBasis: "Declaração de substituição de IRS — prazo de caducidade",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-64",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Que declaração anual recapitulativa de IVA deve ser entregue por quem faz operações intracomunitarias?",
    opcoes: [
      { texto: "Declaração periódica de IVA.", porque: "A declaração periódica é obrigatória para todos os sujeitos passivos de IVA, mas não é a declaração recapitulativa." },
      { texto: "Declaração recapitulativa de IVA (para operações intracomunitarias).", porque: "Quem realiza operações intracomunitarias deve entregar a declaração recapitulativa de IVA." },
      { texto: "Anexo B da declaração de IRS.", porque: "O Anexo B e para rendimentos da categoria B no IRS, não para operações intracomunitarias de IVA." },
      { texto: "Modelo 22 de IRC.", porque: "A Modelo 22 e a declaração de rendimentos de IRC para empresas, não é aplicável aqui." },
    ],
    correta: 1,
    legalBasis: "Declaração recapitulativa de IVA — operações intracomunitarias",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-65",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente tiver rendimentos superiores a 27 360 euros anuais, que regime de IVA lhe e imposto?",
    opcoes: [
      { texto: "Regime trimestral de IVA.", porque: "O regime trimestral é o regime normal para faturação até 650 000 euros, mas a pergunta refere-se ao enquadramento obrigatório por ultrapassar o limiar de isenção." },
      { texto: "Regime mensal de IVA.", porque: "O regime mensal só é obrigatório a partir de um volume de negocios de 650 000 euros anuais, não de 27 360 euros." },
      { texto: "Perde a isenção do Art. 53.º e passa a cobrar IVA, podendo optar pelo regime trimestral.", porque: "Quem ultrapassa 15 000 euros perde a isenção do Art. 53.º, mas o limiar de 27 360 euros não é relevante para a isenção de IVA." },
      { texto: "Deve obrigatoriamente ter contabilidade organizada.", porque: "A contabilidade organizada é obrigatória a partir de rendimentos superiores a 200 000 euros, não de 27 360." },
    ],
    correta: 2,
    legalBasis: "Art. 53.º CIVA — isenção de IVA até 15 000 euros de volume de negocios",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-66",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente não entregar a declaração periódica de IVA no prazo, qual é a coima mínima?",
    opcoes: [
      { texto: "50 euros.", porque: "A coima mínima por falta de entrega da declaração periódica de IVA não é de 50 euros." },
      { texto: "150 euros.", porque: "A coima por falta de entrega atempada de declarações fiscais pode comecar nos 150 euros." },
      { texto: "500 euros.", porque: "500 euros não corresponde ao valor mínimo — o valor mínimo é inferior." },
      { texto: "1000 euros.", porque: "1000 euros e significativamente superior ao valor mínimo da coima." },
    ],
    correta: 1,
    legalBasis: "Coimas por falta de entrega de declarações fiscais — RGIT",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-67",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "O trabalhador independente que pretenda cessar atividade para efeitos de IVA, em que momento deve entregar a declaração de cessação?",
    opcoes: [
      { texto: "No prazo de 30 dias a contar da data de cessação.", porque: "A declaração de cessação de atividade deve ser apresentada no prazo de 30 dias." },
      { texto: "No prazo de 60 dias a contar da data de cessação.", porque: "O prazo não é de 60 dias para cessação de atividade — é de 30 dias." },
      { texto: "Até ao final do ano civil.", porque: "Não é necessário esperar pelo final do ano — o prazo é de 30 dias após a cessação." },
      { texto: "Até a entrega da declaração de IRS.", porque: "A cessação tem prazo próprio (30 dias), independente do IRS." },
    ],
    correta: 0,
    legalBasis: "Cessacao de atividade para efeitos de IVA — 30 dias",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-68",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de dezembro deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de janeiro do ano seguinte.", porque: "Janeiro não é o 2.º mês após dezembro — a declaração deve ser entregue até 10 de fevereiro do ano seguinte." },
      { texto: "10 de fevereiro do ano seguinte.", porque: "No regime mensal, a declaração de IVA referente a dezembro deve ser entregue até ao dia 10 de fevereiro do ano seguinte." },
      { texto: "20 de fevereiro do ano seguinte.", porque: "O dia 20 de fevereiro é o prazo do 4.º trimestre no regime trimestral, não do regime mensal." },
      { texto: "10 de marco do ano seguinte.", porque: "Marco e o 3.º mês após dezembro — o prazo é fevereiro (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a dezembro",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-69",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Se um trabalhador independente alterar o seu IBAN associado a conta da AT, em que prazo deve comunicar essa alteração?",
    opcoes: [
      { texto: "No prazo de 15 dias.", porque: "A alteração do IBAN deve ser comunicada atempadamente, mas não tem um prazo rigido de 15 dias — basta atualizar antes de submeter declarações." },
      { texto: "Imediatamente, para garantir que os reembolsos são depositados na conta correta.", porque: "É recomendável atualizar o IBAN o mais cedo possível para evitar problemas com reembolsos." },
      { texto: "Até a próxima declaração de IRS.", porque: "É aconselhável atualizar antes da declaração, mas pode ser feito a qualquer momento." },
      { texto: "Não é necessário comunicar — a AT deteta automaticamente.", porque: "A AT não deteta automaticamente alterações de IBAN — é responsabilidade do contribuinte atualizar." },
    ],
    correta: 1,
    legalBasis: "Atualizacao de dados bancários — Portal das Finanças",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-70",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Qual é o prazo para o contribuinte contestar uma coima fiscal aplicada pela AT?",
    opcoes: [
      { texto: "10 dias úteis após a notificação.", porque: "O prazo para contestar não é de 10 dias úteis — é mais alargado." },
      { texto: "20 dias após a notificação.", porque: "A defesa em processo de contraordenação pode ser apresentada no prazo de 20 dias." },
      { texto: "60 dias após a notificação.", porque: "O prazo para defesa em contraordenação tributária não é de 60 dias." },
      { texto: "90 dias após a notificação.", porque: "90 dias excede o prazo legal para apresentação de defesa." },
    ],
    correta: 1,
    legalBasis: "Defesa em processo de contraordenação — RGIT",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-71",
    categoria: "prazos",
    dificuldade: 2,
    pergunta: "Qual é a consequência para um trabalhador independente que emita um recibo verde após os 5 dias úteis permitidos?",
    opcoes: [
      { texto: "O recibo e automaticamente rejeitado pelo sistema.", porque: "O sistema não rejeita automaticamente recibos emitidos fora do prazo — mas o trabalhador pode ser sujeito a coima." },
      { texto: "Pode ser sujeito a uma coima por emissão fora de prazo.", porque: "A emissão de recibo verde fora do prazo legal (até 5 dias úteis) pode resultar numa coima." },
      { texto: "Não há qualquer consequência.", porque: "Ha consequências — a emissão fora do prazo constitui uma infração que pode originar coima." },
      { texto: "O recibo é válido, mas o trabalhador perde o direito a deduções.", porque: "A validade do recibo não está em causa, mas a emissão fora do prazo pode gerar coima, não perda de deduções." },
    ],
    correta: 1,
    legalBasis: "Emissão de recibo verde fora de prazo — coima",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-72",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de abril deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de maio.", porque: "Maio não é o 2.º mês após abril — a declaração deve ser entregue até 10 de junho." },
      { texto: "10 de junho.", porque: "No regime mensal, a declaração de IVA referente a abril deve ser entregue até ao dia 10 de junho." },
      { texto: "20 de junho.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de julho.", porque: "Julho seria o 3.º mês após abril — o prazo é junho (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a abril",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-73",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente no regime trimestral de IVA pretender mudar para o regime mensal, que condição de faturação deve cumprir?",
    opcoes: [
      { texto: "Volume de negocios superior a 100 000 euros no ano anterior.", porque: "O limiar para passagem obrigatória ao regime mensal não é 100 000 euros." },
      { texto: "Volume de negocios superior a 650 000 euros no ano anterior.", porque: "O regime mensal de IVA é obrigatório quando o volume de negocios no ano anterior ultrapassa 650 000 euros." },
      { texto: "Volume de negocios superior a 250 000 euros no ano anterior.", porque: "250 000 euros não é o limiar correto — e 650 000 euros." },
      { texto: "Não há condição — é sempre uma opção voluntária.", porque: "A passagem ao regime mensal é obrigatória acima de 650 000 euros, embora também possa ser voluntária abaixo desse limiar." },
    ],
    correta: 1,
    legalBasis: "Regime mensal de IVA — obrigatório acima de 650 000 euros de volume de negocios",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-74",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente abriu atividade a 15 de maio e a isenção de SS termina a 14 de maio do ano seguinte, o primeiro pagamento de contribuições refere-se a que mês?",
    opcoes: [
      { texto: "Maio do ano seguinte, pago entre 10 e 20 de junho.", porque: "O primeiro pagamento refere-se ao mês em que termina a isenção (maio), sendo pago no período de 10 a 20 do mês seguinte (junho)." },
      { texto: "Junho do ano seguinte, pago entre 10 e 20 de julho.", porque: "Se a isenção termina a 14 de maio, as contribuições são devidas a partir de maio, não de junho." },
      { texto: "Abril do ano seguinte, pago entre 10 e 20 de maio.", porque: "Em abril a isenção ainda está em vigor — o primeiro mês com contribuições e maio." },
      { texto: "Janeiro do segundo ano, pago entre 10 e 20 de fevereiro.", porque: "Janeiro e demasiado tarde — as contribuições são devidas a partir do mês em que termina a isenção." },
    ],
    correta: 0,
    legalBasis: "Primeiro pagamento após isenção de 12 meses — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-75",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente está no regime trimestral de IVA é faturou 5000 euros no 1.º trimestre, com IVA a 23%, qual é o prazo para entregar é pagar a declaração?",
    opcoes: [
      { texto: "Até 20 de abril.", porque: "Abril não é o prazo — no regime trimestral, a declaração do 1.º trimestre é entregue é paga até 20 de maio." },
      { texto: "Até 20 de maio.", porque: "A declaração é o pagamento do IVA trimestral do 1.º trimestre devem ser feitos até 20 de maio." },
      { texto: "Até 10 de maio.", porque: "O dia 10 aplica-se ao regime mensal; no trimestral, o prazo é até ao dia 20." },
      { texto: "Até 20 de junho.", porque: "Junho não corresponde ao prazo do 1.º trimestre — o prazo é maio." },
    ],
    correta: 1,
    legalBasis: "Declaração é pagamento de IVA trimestral — 1.º trimestre até 20 de maio",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-76",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de julho deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de agosto.", porque: "Agosto não é o 2.º mês após julho — a declaração deve ser entregue até 10 de setembro." },
      { texto: "10 de setembro.", porque: "No regime mensal, a declaração de IVA referente a julho deve ser entregue até ao dia 10 de setembro." },
      { texto: "20 de setembro.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de outubro.", porque: "Outubro seria o 3.º mês após julho — o prazo é setembro (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a julho",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-77",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se a AT enviar uma notificação para regularizar uma divergência na declaração de IRS, em que prazo deve o contribuinte responder?",
    opcoes: [
      { texto: "15 dias a contar da notificação.", porque: "O prazo habitual para resposta a divergências não é de 15 dias." },
      { texto: "30 dias a contar da notificação.", porque: "O prazo para regularizar divergências na declaração de IRS é geralmente de 30 dias a contar da notificação." },
      { texto: "60 dias a contar da notificação.", porque: "O prazo habitual é de 30 dias, não de 60." },
      { texto: "Não há prazo — pode responder a qualquer momento.", porque: "Ha um prazo — a falta de resposta pode levar a liquidação oficiosa." },
    ],
    correta: 1,
    legalBasis: "Regularizacao de divergências na declaração de IRS — prazo de 30 dias",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-78",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Um trabalhador independente que inicie atividade em setembro e esteja isento de IVA (Art. 53.º), até quando vigora a isenção de contribuições para a SS?",
    opcoes: [
      { texto: "Até 31 de dezembro do mesmo ano.", porque: "A isenção não termina no final do ano civil — dura 12 meses a contar da abertura." },
      { texto: "Até ao final de agosto do ano seguinte.", porque: "A isenção de 12 meses a contar de setembro termina no final de agosto do ano seguinte." },
      { texto: "Até ao final de setembro do ano seguinte.", porque: "A isenção termina 12 meses após, ou seja, no final de agosto (não setembro) do ano seguinte, dependendo do dia exato de início." },
      { texto: "Até ao final de marco do ano seguinte.", porque: "6 meses não correspondem ao período legal de isenção — são 12 meses." },
    ],
    correta: 1,
    legalBasis: "Art. 157.º Código Contributivo — isenção de 12 meses a contar da abertura de atividade",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-79",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente receber um pagamento a 28 de dezembro (sexta-feira) e os 5 dias úteis incluem feriados, como se conta o prazo para emitir o recibo verde?",
    opcoes: [
      { texto: "Conta-se a partir do dia do pagamento, incluindo fins de semana e feriados.", porque: "O prazo de 5 dias úteis exclui fins de semana e feriados por definição." },
      { texto: "Conta-se 5 dias úteis a partir do dia do pagamento, excluindo fins de semana e feriados.", porque: "O prazo de 5 dias úteis para emissão do recibo verde conta apenas dias úteis, excluindo fins de semana e feriados." },
      { texto: "Conta-se 5 dias corridos.", porque: "O prazo é de 5 dias úteis, não corridos — fins de semana e feriados não contam." },
      { texto: "Tem até ao final de janeiro para emitir.", porque: "Não há prazo até ao final de janeiro — o prazo é de 5 dias úteis após o pagamento." },
    ],
    correta: 1,
    legalBasis: "Emissão de recibo verde — até 5 dias úteis após o pagamento",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-80",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Qual é o prazo de prescrição das dívidas tributarias (IRS, IVA) em Portugal?",
    opcoes: [
      { texto: "4 anos.", porque: "4 anos é o prazo de caducidade do direito a liquidação, não de prescrição da dívida." },
      { texto: "8 anos.", porque: "O prazo de prescrição das dívidas tributarias em Portugal é de 8 anos, a contar do início do ano civil seguinte." },
      { texto: "10 anos.", porque: "O prazo de prescrição de dívidas tributarias não é de 10 anos — é de 8 anos." },
      { texto: "15 anos.", porque: "15 anos excede o prazo legal de prescrição, que é de 8 anos." },
    ],
    correta: 1,
    legalBasis: "Prescricao de dívidas tributarias — 8 anos (Art. 48.º LGT)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-81",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente tiver dívidas a Segurança Social, em quantos anos prescrevem essas dívidas?",
    opcoes: [
      { texto: "3 anos.", porque: "O prazo de prescrição de contribuições a SS não é de 3 anos — é mais longo." },
      { texto: "5 anos.", porque: "O prazo de prescrição das contribuições devidas a Segurança Social é de 5 anos." },
      { texto: "8 anos.", porque: "8 anos é o prazo de prescrição de dívidas tributarias (IRS/IVA), não de contribuições a SS." },
      { texto: "10 anos.", porque: "O prazo de prescrição de contribuições a SS não é de 10 anos — é de 5 anos." },
    ],
    correta: 1,
    legalBasis: "Prescricao de dívidas a Segurança Social — 5 anos",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-82",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de outubro deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de novembro.", porque: "Novembro não é o 2.º mês após outubro — a declaração deve ser entregue até 10 de dezembro." },
      { texto: "10 de dezembro.", porque: "No regime mensal, a declaração de IVA referente a outubro deve ser entregue até ao dia 10 de dezembro." },
      { texto: "20 de dezembro.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de janeiro do ano seguinte.", porque: "Janeiro seria o 3.º mês após outubro — o prazo é dezembro (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a outubro",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-83",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente entregar a declaração de IRS com atraso de 10 dias (fora do prazo), qual é a coima mínima que pode ser aplicada?",
    opcoes: [
      { texto: "25 euros.", porque: "A coima mínima por entrega fora de prazo não é tão baixa — o valor mínimo é mais elevado." },
      { texto: "75 euros.", porque: "75 euros não corresponde ao valor mínimo — a coima mínima por atraso na entrega é de 150 euros." },
      { texto: "150 euros.", porque: "A coima mínima por entrega tardia da declaração de IRS é de 150 euros." },
      { texto: "300 euros.", porque: "300 euros não é o valor mínimo — a coima começa nos 150 euros." },
    ],
    correta: 2,
    legalBasis: "Coima por entrega tardia de declaração de IRS — mínimo 150 euros (RGIT)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-84",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Qual é o valor máximo da coima por falta de entrega da declaração de IRS?",
    opcoes: [
      { texto: "1500 euros.", porque: "A coima máxima por falta de entrega é superior a 1500 euros." },
      { texto: "2500 euros.", porque: "2500 euros não é o valor máximo — o limite superior pode chegar a 3750 euros." },
      { texto: "3750 euros.", porque: "A coima máxima por falta ou atraso na entrega da declaração de IRS pode atingir 3750 euros." },
      { texto: "5000 euros.", porque: "5000 euros excede o valor máximo da coima para pessoas singulares nesta situação." },
    ],
    correta: 2,
    legalBasis: "Coima por falta de entrega de declaração de IRS — máximo 3750 euros (RGIT)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-85",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente pretender reduzir os pagamentos por conta de IRS (por considerar que o imposto sera inferior), até quando pode solicitar a redução?",
    opcoes: [
      { texto: "Não é possível reduzir os pagamentos por conta.", porque: "É possível solicitar a redução ou suspensão dos pagamentos por conta, caso o contribuinte preveja que o imposto sera inferior." },
      { texto: "Pode solicitar a redução a qualquer momento antes do vencimento de cada prestação.", porque: "O contribuinte pode solicitar a limitação dos pagamentos por conta se considerar que o imposto a pagar sera inferior ao valor dos pagamentos, apresentando requerimento antes do vencimento." },
      { texto: "Apenas após o primeiro pagamento por conta.", porque: "A redução pode ser solicitada antes do primeiro pagamento, não apenas após." },
      { texto: "Apenas até 30 de junho.", porque: "O prazo não é fixo em 30 de junho — depende do vencimento de cada prestação." },
    ],
    correta: 1,
    legalBasis: "Reducao de pagamentos por conta — Art. 107.º CIRS",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-86",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Quando um trabalhador independente emite um recibo verde com retenção na fonte e o cliente não paga a retenção ao Estado, quem e responsável?",
    opcoes: [
      { texto: "O trabalhador independente.", porque: "A responsabilidade pela entrega da retenção ao Estado e da entidade pagadora (cliente), não do trabalhador que emitiu o recibo." },
      { texto: "A entidade pagadora (cliente).", porque: "A entidade pagadora que reteve o imposto na fonte e a responsável pela sua entrega ao Estado." },
      { texto: "Ambos — solidariamente.", porque: "A responsabilidade principal e da entidade pagadora que efetua a retenção, não é solidaria por defeito." },
      { texto: "A Segurança Social.", porque: "A Segurança Social não intervem na retenção de IRS — a responsabilidade e da entidade pagadora." },
    ],
    correta: 1,
    legalBasis: "Retenção na fonte — responsabilidade da entidade pagadora",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-87",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente receber rendimentos de um único cliente (sem retenção) e não fizer pagamentos por conta, que consequência pode enfrentar no acerto final de IRS?",
    opcoes: [
      { texto: "Nenhuma — os pagamentos por conta são opcionais.", porque: "Os pagamentos por conta não são opcionais — são obrigatorios quando calculados pela AT, e a falta de pagamento gera juros." },
      { texto: "Um valor elevado de imposto a pagar de uma só vez, alem de juros compensatórios.", porque: "Sem retenção na fonte e sem pagamentos por conta, todo o imposto sera apurado na liquidação final, podendo gerar um valor elevado a pagar com juros compensatórios." },
      { texto: "Perde o direito ao regime simplificado.", porque: "A falta de pagamentos por conta não implica perda do regime simplificado." },
      { texto: "É automaticamente inscrito no regime de contabilidade organizada.", porque: "A falta de pagamentos por conta não muda o regime de tributação." },
    ],
    correta: 1,
    legalBasis: "Pagamentos por conta — consequência da falta de pagamento",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-88",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Quando um trabalhador independente com contabilidade organizada pode entregar a declaração de IRS?",
    opcoes: [
      { texto: "Apenas em janeiro e fevereiro.", porque: "Janeiro e fevereiro não são o período de entrega — a declaração é entregue entre 1 de abril e 30 de junho, tal como no regime simplificado." },
      { texto: "De 1 de abril a 30 de junho, tal como no regime simplificado.", porque: "O período de entrega da declaração de IRS é o mesmo independentemente de estar no regime simplificado ou em contabilidade organizada: de 1 de abril a 30 de junho." },
      { texto: "De 1 de marco a 31 de maio.", porque: "O período de entrega não é este — é de 1 de abril a 30 de junho." },
      { texto: "Só após entrega do relatorio de contas pelo TOC, sem prazo fixo.", porque: "Ha um prazo fixo (1 abril a 30 junho) independentemente do TOC." },
    ],
    correta: 1,
    legalBasis: "Entrega da declaração de IRS — período único de 1 abril a 30 junho",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-89",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente iniciar atividade em janeiro e a isenção de SS terminar em dezembro, qual é o trimestre da primeira declaração trimestral?",
    opcoes: [
      { texto: "1.º trimestre do ano seguinte (jan-mar), com entrega até ao final de abril.", porque: "A primeira declaração após o fim da isenção refere-se ao trimestre em que está terminou (4.º trimestre out-dez), não ao 1.º trimestre do ano seguinte." },
      { texto: "4.º trimestre do ano de início (out-dez), com entrega até ao final de janeiro do ano seguinte.", porque: "Se a isenção termina em dezembro, a primeira declaração trimestral refere-se ao 4.º trimestre (out-dez), com entrega até ao final de janeiro do ano seguinte." },
      { texto: "3.º trimestre do ano de início (jul-set), com entrega até ao final de outubro.", porque: "Em julho-setembro a isenção ainda está em vigor, por isso não haveria obrigação de declaração." },
      { texto: "2.º trimestre do ano seguinte (abr-jun), com entrega até ao final de julho.", porque: "Esperar pelo 2.º trimestre do ano seguinte seria demasiado tarde — a primeira declaração é referente ao 4.º trimestre." },
    ],
    correta: 1,
    legalBasis: "Primeira declaração trimestral após isenção — 4.º trimestre",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-90",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente declarar rendimentos de 0 euros na declaração trimestral da SS, qual é a consequência para as contribuições?",
    opcoes: [
      { texto: "Fica isento de contribuições nesse trimestre.", porque: "Declarar 0 euros não isenta automaticamente — há um valor mínimo de contribuição obrigatória (contribuição mínima de 20 euros)." },
      { texto: "É obrigado a pagar a contribuição mínima de 20 euros por mês.", porque: "Mesmo com rendimentos de 0 euros, o trabalhador independente deve pagar a contribuição mínima mensal de 20 euros." },
      { texto: "A Segurança Social encerra automaticamente a sua atividade.", porque: "A SS não encerra a atividade por rendimentos zero — o trabalhador continua obrigado a pagar a contribuição mínima." },
      { texto: "É automaticamente reencaminhado para o regime de trabalhador por conta de outrem.", porque: "Declarar zero não altera o regime contributivo — continua no regime de trabalhador independente com contribuição mínima." },
    ],
    correta: 1,
    legalBasis: "Contribuição mínima mensal de 20 euros — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-91",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente tiver simultaneamente rendimentos da categoria A (trabalho dependente) e da categoria B (atividade independente), como funciona a declaração de IRS?",
    opcoes: [
      { texto: "Entrega duas declarações separadas, uma para cada categoria.", porque: "Não se entregam duas declarações — a Modelo 3 engloba todos os rendimentos, com os anexos correspondentes." },
      { texto: "Entrega uma única Modelo 3 com o Anexo A (categoria A) e o Anexo B (categoria B).", porque: "A declaração de IRS é única (Modelo 3), incluindo o Anexo A para a categoria A e o Anexo B para a categoria B." },
      { texto: "Apenas declara os rendimentos da categoria B, pois a categoria A é automática.", porque: "Ambas as categorias devem ser incluídas na declaração, embora os rendimentos da categoria A possam ser pre-preenchidos." },
      { texto: "Declara apenas a categoria com maior rendimento.", porque: "Todos os rendimentos devem ser declarados, independentemente do valor de cada categoria." },
    ],
    correta: 1,
    legalBasis: "Modelo 3 — Anexo A e Anexo B para categorias A e B respetivamente",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-92",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se a AT emitir uma liquidação oficiosa por falta de entrega da declaração de IRS, o contribuinte pode ainda entregar a declaração em falta?",
    opcoes: [
      { texto: "Não — uma vez emitida a liquidação oficiosa, não é possível corrigir.", porque: "É possível entregar a declaração em falta mesmo após a liquidação oficiosa, embora possa haver coima." },
      { texto: "Sim, pode entregar a declaração em falta, mas ficara sujeito a coima por entrega fora de prazo.", porque: "O contribuinte pode entregar a declaração em falta para substituir a liquidação oficiosa, mas incorre em coima por atraso." },
      { texto: "Sim, mas apenas nos 30 dias seguintes a liquidação oficiosa.", porque: "Não há um limite de 30 dias — a declaração pode ser entregue dentro do prazo de caducidade, com coima." },
      { texto: "Sim, mas perde todas as deduções.", porque: "A entrega tardia não implica perda automática de deduções — as deduções a que tem direito são aplicadas." },
    ],
    correta: 1,
    legalBasis: "Liquidacao oficiosa — possibilidade de entrega da declaração em falta",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-93",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente cessar atividade em novembro, deve entregar a declaração periódica de IVA relativa ao 4.º trimestre?",
    opcoes: [
      { texto: "Não — ao cessar atividade, deixa de ter obrigações de IVA.", porque: "Mesmo cessando em novembro, deve entregar a declaração do 4.º trimestre referente aos meses em que esteve ativo." },
      { texto: "Sim, deve entregar a declaração referente ao período em que esteve ativo no 4.º trimestre (outubro e novembro).", porque: "A cessação de atividade não dispensa a entrega da declaração de IVA referente ao período de atividade no 4.º trimestre." },
      { texto: "Sim, mas só se tiver faturado mais de 1000 euros nesse período.", porque: "A obrigação de declaração não depende de um limiar de faturação — deve ser entregue independentemente do valor." },
      { texto: "Apenas se a AT o notificar para tal.", porque: "A obrigação de entrega existe por lei, não depende de notificação da AT." },
    ],
    correta: 1,
    legalBasis: "Declaração de IVA após cessação — período de atividade no trimestre",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-94",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Qual é a taxa de juros de mora aplicada as dívidas tributarias em atraso (IRS, IVA)?",
    opcoes: [
      { texto: "Taxa fixa de 2% ao ano.", porque: "A taxa de juros de mora sobre dívidas tributarias não é de 2%." },
      { texto: "A taxa de juros de mora e definida anualmente por portaria, sendo tipicamente superior a taxa de juro de referência do BCE.", porque: "A taxa de juros de mora é fixada anualmente e é superior a taxa de referência, variando conforme o ano." },
      { texto: "Taxa fixa de 10% ao ano.", porque: "A taxa não é fixa em 10% — e definida anualmente por portaria." },
      { texto: "Não há juros de mora — apenas coimas.", porque: "Alem de coimas, são aplicados juros de mora sobre o valor em dívida." },
    ],
    correta: 1,
    legalBasis: "Juros de mora — taxa definida anualmente por portaria",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-95",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente tiver um crédito de IVA (mais IVA deduzido do que cobrado), o que pode fazer?",
    opcoes: [
      { texto: "Solicitar o reembolso imediatamente após a declaração.", porque: "O reembolso de IVA pode ser pedido, mas há regras específicas — nem sempre é imediato." },
      { texto: "Reportar o crédito para o período seguinte ou solicitar reembolso, conforme as regras aplicáveis.", porque: "O crédito de IVA pode ser reportado para o período seguinte ou o contribuinte pode solicitar reembolso quando reunidas as condições previstas na lei." },
      { texto: "O crédito e automaticamente perdido se não for pedido no trimestre seguinte.", porque: "O crédito não é perdido — pode ser reportado para períodos seguintes." },
      { texto: "Deve usar o crédito para pagar contribuições a Segurança Social.", porque: "O crédito de IVA não pode ser usado para pagar contribuições a SS — são entidades e obrigações distintas." },
    ],
    correta: 1,
    legalBasis: "Credito de IVA — reporte ou pedido de reembolso",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-96",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de fevereiro deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de marco.", porque: "Marco não é o 2.º mês após fevereiro — a declaração deve ser entregue até 10 de abril." },
      { texto: "10 de abril.", porque: "No regime mensal, a declaração de IVA referente a fevereiro deve ser entregue até ao dia 10 de abril." },
      { texto: "20 de abril.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de maio.", porque: "Maio seria o 3.º mês após fevereiro — o prazo é abril (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a fevereiro",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-97",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente cessar atividade a meio de um trimestre, como é calculada a contribuição para a SS nesse trimestre?",
    opcoes: [
      { texto: "Paga o trimestre completo, independentemente da data de cessação.", porque: "A contribuição não é necessariamente do trimestre completo — é devida pelo período de atividade efetiva." },
      { texto: "A contribuição é devida apenas pelos meses em que esteve efetivamente ativo.", porque: "A contribuição para a SS é devida pelos meses em que o trabalhador esteve ativo, não pelo trimestre inteiro." },
      { texto: "Não paga contribuições no trimestre da cessação.", porque: "A cessação não isenta das contribuições dos meses em que esteve ativo." },
      { texto: "Paga metade do valor trimestral.", porque: "Não há regra de metade — a contribuição é proporcional aos meses de atividade efetiva." },
    ],
    correta: 1,
    legalBasis: "Contribuição proporcional após cessação — Segurança Social",
    fonte: fonte("segSocialGov"),
  },
  {
    id: "praz-98",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Qual é a diferença entre caducidade (4 anos) e prescrição (8 anos) em materia tributária?",
    opcoes: [
      { texto: "São sinonimos — ambos se referem ao prazo de 4 anos.", porque: "Não são sinonimos — caducidade (4 anos) é o prazo para a AT liquidar; prescrição (8 anos) é o prazo para cobrar." },
      { texto: "A caducidade refere-se ao prazo para a AT proceder a liquidação; a prescrição refere-se ao prazo para cobrar a dívida.", porque: "A caducidade (4 anos) limita o tempo que a AT tem para liquidar o imposto; a prescrição (8 anos) limita o tempo para exigir o pagamento da dívida já liquidada." },
      { texto: "A caducidade aplica-se apenas ao IRS; a prescrição aplica-se apenas ao IVA.", porque: "Ambos os conceitos se aplicam a todos os impostos, não apenas a um tipo específico." },
      { texto: "A prescrição é de 4 anos e a caducidade é de 8 anos.", porque: "É ao contrário — caducidade e 4 anos e prescrição e 8 anos." },
    ],
    correta: 1,
    legalBasis: "Caducidade (Art. 45.º LGT) vs prescrição (Art. 48.º LGT)",
    fonte: fonte("govptTrabIndependente"),
  },
  {
    id: "praz-99",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "No regime mensal de IVA, a declaração periódica referente ao mês de agosto deve ser entregue até que data?",
    opcoes: [
      { texto: "10 de setembro.", porque: "Setembro não é o 2.º mês após agosto — a declaração deve ser entregue até 10 de outubro." },
      { texto: "10 de outubro.", porque: "No regime mensal, a declaração de IVA referente a agosto deve ser entregue até ao dia 10 de outubro." },
      { texto: "20 de outubro.", porque: "O dia 20 aplica-se ao regime trimestral; no regime mensal, o prazo é dia 10." },
      { texto: "10 de novembro.", porque: "Novembro seria o 3.º mês após agosto — o prazo é outubro (2.º mês)." },
    ],
    correta: 1,
    legalBasis: "Declaração periódica de IVA (mensal) — referente a agosto",
    fonte: fonte("portalFinancasIVA"),
  },
  {
    id: "praz-100",
    categoria: "prazos",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente pretender impugnar judicialmente uma liquidação de IRS, qual é o prazo para apresentar a impugnação judicial?",
    opcoes: [
      { texto: "30 dias após a notificação.", porque: "O prazo para impugnação judicial não é de 30 dias — é mais alargado." },
      { texto: "60 dias após a notificação.", porque: "O prazo não é de 60 dias — a impugnação judicial deve ser apresentada no prazo de 90 dias." },
      { texto: "90 dias após o termo do prazo de pagamento voluntário.", porque: "A impugnação judicial pode ser apresentada no prazo de 90 dias após o termo do prazo de pagamento voluntário." },
      { texto: "120 dias após a notificação.", porque: "120 dias é o prazo para reclamação graciosa, não para impugnação judicial (que é 90 dias)." },
    ],
    correta: 2,
    legalBasis: "Impugnacao judicial — prazo de 90 dias (Art. 102.º CPPT)",
    fonte: fonte("govptTrabIndependente"),
  },
];
