import { fonte, type QuizPergunta } from "./types";

export const PERGUNTAS_ATIVIDADES: QuizPergunta[] = [
  {
    id: "ativ-7",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um arquiteto (código 1001 da tabela do Art. 151.º CIRS) que emite recibos verdes tem retenção na fonte de:",
    opcoes: [
      { texto: "23%", porque: "Arquitetos (código 1001) constam da tabela do Art. 151.º CIRS, pelo que a retenção na fonte é de 23% (Art. 101.º, n.º 1, al. a) CIRS)." },
      { texto: "11,5%", porque: "11,5% aplica-se a prestações de serviços fora do Art. 151.º (código residual 1519) — arquitetos constam da tabela." },
      { texto: "16,5%", porque: "16,5% aplica-se a rendimentos de propriedade intelectual/direitos de autor, não à prestação de serviços de arquitetura." },
      { texto: "0% — sem retenção", porque: "A dispensa de retenção aplica-se apenas a vendas de bens — a prestação de serviços de arquitetura está sujeita a 23%." },
    ],
    correta: 0,
    legalBasis: "Art. 151.º CIRS (código 1001) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-8",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual o coeficiente do regime simplificado para um engenheiro (código 1003) inscrito na tabela do Art. 151.º?",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços fora do Art. 151.º — engenheiros estão na tabela, com coeficiente 0,75." },
      { texto: "0,75", porque: "Engenheiros (código 1003) constam do Art. 151.º, pelo que o coeficiente é 0,75 (Art. 31.º, al. b) CIRS) — apenas 75% do rendimento é tributado." },
      { texto: "0,95", porque: "0,95 aplica-se a rendimentos de propriedade intelectual (Art. 31.º, al. d) CIRS), não a serviços de engenharia." },
      { texto: "0,15", porque: "0,15 aplica-se a vendas de bens, hotelaria e restauração (Art. 31.º, al. a) CIRS), não a profissões liberais." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-9",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um advogado (código 6010 do Art. 151.º) que presta serviços a uma empresa portuguesa tem retenção de:",
    opcoes: [
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora do Art. 151.º — advogados constam da tabela com retenção de 23%." },
      { texto: "0% — sem retenção", porque: "A prestação de serviços de advocacia está sujeita a retenção na fonte de 23%, ao abrigo do Art. 101.º, al. a) CIRS." },
      { texto: "16,5%", porque: "16,5% é a taxa de retenção para direitos de autor/propriedade intelectual, não para serviços de advocacia." },
      { texto: "23%", porque: "Advogados (código 6010) integram a tabela do Art. 151.º CIRS, pelo que a retenção é de 23% (Art. 101.º, n.º 1, al. a) CIRS)." },
    ],
    correta: 3,
    legalBasis: "Art. 151.º CIRS (código 6010) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-10",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um designer (código 1336 do Art. 151.º) tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,15", porque: "0,15 aplica-se a vendas de bens e hotelaria — designers do Art. 151.º têm coeficiente 0,75." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços fora do Art. 151.º — designers com código 1336 estão na tabela." },
      { texto: "0,75", porque: "Designers (código 1336) constam da tabela do Art. 151.º CIRS, pelo que o coeficiente no regime simplificado é 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,95", porque: "0,95 aplica-se a rendimentos de propriedade intelectual, não à prestação de serviços de design." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-11",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual a taxa de retenção na fonte para um médico de clínica geral (código 7014) que fatura a uma clínica privada?",
    opcoes: [
      { texto: "23%", porque: "Médicos de clínica geral (código 7014) constam do Art. 151.º CIRS, sendo a retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora da tabela do Art. 151.º — a medicina consta dessa tabela." },
      { texto: "25%", porque: "Não existe taxa de retenção de 25% no Art. 101.º CIRS para rendimentos da categoria B." },
      { texto: "16,5%", porque: "16,5% é a taxa para rendimentos de propriedade intelectual, não para prestação de serviços médicos." },
    ],
    correta: 0,
    legalBasis: "Art. 151.º CIRS (código 7014) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-12",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um enfermeiro (código 5010 do Art. 151.º) que emite recibos verdes a um hospital privado tem coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 é para prestações de serviços não previstas no Art. 151.º — enfermeiros constam da tabela, com coeficiente 0,75." },
      { texto: "0,15", porque: "0,15 aplica-se a venda de bens e hotelaria, não a serviços de enfermagem." },
      { texto: "0,75", porque: "Enfermeiros (código 5010) estão na tabela do Art. 151.º CIRS, pelo que o coeficiente do regime simplificado é 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "1,00", porque: "1,00 só se aplica ao regime de transparência fiscal (Art. 31.º, al. g) CIRS), não a enfermeiros." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-13",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual o coeficiente do regime simplificado para a venda de bens/mercadorias por um trabalhador independente?",
    opcoes: [
      { texto: "0,75", porque: "0,75 aplica-se a serviços profissionais do Art. 151.º, não a vendas de bens." },
      { texto: "0,15", porque: "A venda de bens/mercadorias tem coeficiente 0,15 (Art. 31.º, al. a) CIRS) — apenas 15% do rendimento é tributado." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços (código 1519), não a vendas de bens." },
      { texto: "0,50", porque: "0,50 aplica-se apenas ao alojamento local em zona de contenção, não a vendas de bens." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. a) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-14",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "A venda de bens por um trabalhador independente está sujeita a retenção na fonte de IRS?",
    opcoes: [
      { texto: "Não — as vendas de bens não estão sujeitas a retenção na fonte.", porque: "A venda de bens/mercadorias não está sujeita a retenção na fonte de IRS (Art. 101.º CIRS refere-se apenas a rendimentos de prestação de serviços e propriedade intelectual)." },
      { texto: "Sim, 23%.", porque: "23% é a taxa das profissões do Art. 151.º — as vendas de bens não estão sujeitas a retenção." },
      { texto: "Sim, 11,5%.", porque: "11,5% aplica-se a outros serviços (código 1519) — vendas de bens não têm retenção." },
      { texto: "Sim, 5%.", porque: "Não existe taxa de retenção de 5% no regime dos trabalhadores independentes." },
    ],
    correta: 0,
    legalBasis: "Art. 101.º CIRS — vendas de bens excluídas de retenção",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-15",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um contabilista certificado (código 4013 do Art. 151.º) tem retenção na fonte de:",
    opcoes: [
      { texto: "16,5%", porque: "16,5% aplica-se a rendimentos de propriedade intelectual, não a serviços de contabilidade." },
      { texto: "23%", porque: "Contabilistas (código 4013) constam da tabela do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "11,5%", porque: "11,5% é para atividades fora do Art. 151.º — contabilistas constam dessa tabela." },
      { texto: "0% — sem retenção", porque: "Contabilistas são profissionais liberais do Art. 151.º e estão sujeitos a retenção de 23%." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 4013) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-16",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um veterinário (código 1410 do Art. 151.º) tem, no regime simplificado, um coeficiente de:",
    opcoes: [
      { texto: "0,75", porque: "Veterinários (código 1410) constam do Art. 151.º CIRS, pelo que o coeficiente é 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — veterinários estão na tabela." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços veterinários." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a serviços veterinários." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-17",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual a taxa de retenção na fonte para um tradutor (código 1334 do Art. 151.º)?",
    opcoes: [
      { texto: "0% — sem retenção", porque: "Tradutores do Art. 151.º estão sujeitos a retenção de 23% quando o cliente tem contabilidade organizada." },
      { texto: "11,5%", porque: "11,5% aplica-se a serviços não listados no Art. 151.º — tradutores constam dessa tabela." },
      { texto: "23%", porque: "Tradutores (código 1334) estão na tabela do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a direitos de autor — a tradução como serviço tem tratamento distinto (23%)." },
    ],
    correta: 2,
    legalBasis: "Art. 151.º CIRS (código 1334) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-18",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual é o código residual da tabela do Art. 151.º CIRS para 'outros prestadores de serviços' não listados?",
    opcoes: [
      { texto: "1310", porque: "1310 corresponde a Administradores de bens, não ao código residual." },
      { texto: "9999", porque: "Não existe código 9999 na tabela do Art. 151.º — o residual é 1519." },
      { texto: "1519", porque: "O código 1519 ('Outros prestadores de serviços') é o código residual para atividades não previstas especificamente na tabela do Art. 151.º." },
      { texto: "1500", porque: "Não existe código 1500 na tabela — o código residual é 1519." },
    ],
    correta: 2,
    legalBasis: "Art. 151.º CIRS — código residual 1519",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-19",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um professor (código 8012 do Art. 151.º) que dá aulas como trabalhador independente tem coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — professores (código 8012) estão na tabela, com coeficiente 0,75." },
      { texto: "0,75", porque: "Professores (código 8012) constam da tabela do Art. 151.º CIRS, com coeficiente de 0,75 no regime simplificado (Art. 31.º, al. b) CIRS)." },
      { texto: "0,50", porque: "Não existe coeficiente de 0,50 para serviços de ensino — 0,50 aplica-se apenas ao alojamento local em zona de contenção." },
      { texto: "0,95", porque: "0,95 aplica-se a rendimentos de propriedade intelectual, não a serviços de ensino." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-20",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um economista (código 4014 do Art. 151.º) tem retenção na fonte de:",
    opcoes: [
      { texto: "11,5%", porque: "11,5% é para atividades fora da tabela do Art. 151.º — economistas constam dessa tabela." },
      { texto: "23%", porque: "Economistas (código 4014) estão na tabela do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a rendimentos de propriedade intelectual, não a serviços de economia/consultoria." },
      { texto: "25%", porque: "Não existe taxa de retenção de 25% para rendimentos da categoria B no Art. 101.º CIRS." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 4014) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-21",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um psicólogo (código 1010 do Art. 151.º) que emite recibos verdes tem coeficiente de:",
    opcoes: [
      { texto: "0,75", porque: "Psicólogos (código 1010) estão na tabela do Art. 151.º CIRS, com coeficiente 0,75 no regime simplificado (Art. 31.º, al. b) CIRS)." },
      { texto: "0,35", porque: "0,35 é para serviços fora do Art. 151.º — psicólogos constam dessa tabela." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços de psicologia." },
      { texto: "1,00", porque: "1,00 aplica-se apenas ao regime de transparência fiscal, não a psicólogos." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-22",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um jornalista (código 1327 do Art. 151.º) que fatura a um jornal tem retenção de:",
    opcoes: [
      { texto: "11,5%", porque: "11,5% é para atividades fora do Art. 151.º — jornalistas constam dessa tabela." },
      { texto: "0% — sem retenção", porque: "Jornalistas do Art. 151.º estão sujeitos a retenção na fonte de 23%." },
      { texto: "23%", porque: "Jornalistas (código 1327) constam do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a direitos de autor — o jornalismo como serviço tem retenção de 23%." },
    ],
    correta: 2,
    legalBasis: "Art. 151.º CIRS (código 1327) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-23",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual o coeficiente do regime simplificado para um formador (código 8011 do Art. 151.º)?",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — formadores constam dessa tabela." },
      { texto: "0,50", porque: "0,50 é exclusivo do alojamento local em zona de contenção, não de serviços de formação." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços de formação." },
      { texto: "0,75", porque: "Formadores (código 8011) estão na tabela do Art. 151.º CIRS, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
    ],
    correta: 3,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-24",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um farmacêutico (código 1335 do Art. 151.º) que presta serviços como independente tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "Farmacêuticos (código 1335) constam do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora da tabela do Art. 151.º — farmacêuticos estão na tabela." },
      { texto: "0% — sem retenção", porque: "A prestação de serviços farmacêuticos está sujeita a retenção na fonte de 23%." },
      { texto: "16,5%", porque: "16,5% é para rendimentos de propriedade intelectual, não para serviços farmacêuticos." },
    ],
    correta: 0,
    legalBasis: "Art. 151.º CIRS (código 1335) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-25",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um fisioterapeuta (código 5012 do Art. 151.º) tem coeficiente no regime simplificado de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — fisioterapeutas constam dessa tabela." },
      { texto: "0,95", porque: "0,95 é para propriedade intelectual, não para serviços de fisioterapia." },
      { texto: "0,75", porque: "Fisioterapeutas (código 5012) estão no Art. 151.º, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços de fisioterapia." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-26",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Qual a taxa de retenção e o coeficiente para um nutricionista (código 5013 do Art. 151.º)?",
    opcoes: [
      { texto: "Retenção 11,5% e coeficiente 0,35.", porque: "Estes valores aplicam-se a atividades fora do Art. 151.º — nutricionistas constam da tabela." },
      { texto: "Retenção 23% e coeficiente 0,75.", porque: "Nutricionistas (código 5013) estão na tabela do Art. 151.º, com retenção de 23% e coeficiente de 0,75." },
      { texto: "Retenção 16,5% e coeficiente 0,95.", porque: "Estes valores aplicam-se a propriedade intelectual, não a serviços de nutrição." },
      { texto: "Sem retenção e coeficiente 0,15.", porque: "Sem retenção/0,15 aplica-se a vendas de bens — nutricionistas têm 23%/0,75." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 5013) · Art. 31.º, al. b) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-27",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um solicitador (código 6012 do Art. 151.º) que emite recibos verdes a um escritório tem coeficiente de:",
    opcoes: [
      { texto: "0,95", porque: "0,95 aplica-se a rendimentos de propriedade intelectual, não a serviços jurídicos." },
      { texto: "0,75", porque: "Solicitadores (código 6012) constam do Art. 151.º CIRS, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,35", porque: "0,35 é para serviços fora do Art. 151.º — solicitadores estão na tabela." },
      { texto: "0,50", porque: "0,50 é exclusivo do alojamento local em zona de contenção." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-28",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Uma pessoa que explora um negócio de restauração e bebidas como trabalhador independente tem coeficiente de:",
    opcoes: [
      { texto: "0,15", porque: "Restauração e bebidas é classificada como venda de bens/hotelaria, com coeficiente 0,15 (Art. 31.º, al. a) CIRS)." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços, não a restauração." },
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º, não a restauração." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a restauração." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 1, al. a) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-29",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Uma pessoa com o código residual 1519 ('Outros prestadores de serviços') tem retenção na fonte de:",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões da tabela do Art. 151.º — o código 1519 é o residual, com retenção de 11,5%." },
      { texto: "11,5%", porque: "O código 1519 corresponde a prestações de serviços não previstas no Art. 151.º, com retenção de 11,5% (Art. 101.º, n.º 1, al. c) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a direitos de autor/propriedade intelectual, não ao código residual 1519." },
      { texto: "0% — sem retenção", porque: "Prestadores de serviços com código 1519 estão sujeitos a retenção de 11,5%." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º, n.º 1, al. c) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-30",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual a diferença de coeficiente entre um programador do Art. 151.º (código 1332) e um técnico de informática não listado nessa tabela?",
    opcoes: [
      { texto: "Ambos têm coeficiente 0,75.", porque: "Apenas o programador do Art. 151.º tem 0,75 — o técnico fora da tabela tem 0,35." },
      { texto: "Ambos têm coeficiente 0,35.", porque: "O programador do Art. 151.º (código 1332) tem 0,75, não 0,35." },
      { texto: "O programador tem 0,75 e o técnico tem 0,35.", porque: "Programadores informáticos (código 1332) constam do Art. 151.º, com coeficiente 0,75. Técnicos fora dessa tabela usam o código residual 1519, com coeficiente 0,35." },
      { texto: "O programador tem 0,95 e o técnico tem 0,75.", porque: "0,95 aplica-se a propriedade intelectual — o programador tem 0,75 e o técnico fora da tabela tem 0,35." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. b) e c) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-31",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um motorista de TVDE (Uber, Bolt) tem, para efeitos de Segurança Social, rendimento relevante calculado sobre que percentagem da faturação?",
    opcoes: [
      { texto: "70%", porque: "70% é a base de Segurança Social para prestação de serviços — TVDE é classificado como transporte (bens), com base de 20%." },
      { texto: "20%", porque: "A atividade de TVDE é classificada como transporte de passageiros (equiparada a bens/hotelaria), pelo que a Segurança Social incide sobre 20% do rendimento relevante." },
      { texto: "50%", porque: "Não existe base de 50% para efeitos de Segurança Social — as opções são 70% (serviços) ou 20% (bens/hotelaria/transportes)." },
      { texto: "100%", porque: "A SS nunca incide sobre 100% do rendimento — há sempre um coeficiente de ajustamento (70% ou 20%)." },
    ],
    correta: 1,
    legalBasis: "Art. 162.º Código Contributivo — base de incidência",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-32",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um influencer / criador de conteúdo digital que recebe patrocínios de uma empresa portuguesa tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões do Art. 151.º — criadores de conteúdo digital não constam dessa tabela (usam código 1519)." },
      { texto: "11,5%", porque: "Criadores de conteúdo digital enquadram-se como 'outras prestações de serviços' (código 1519), com retenção de 11,5% (Art. 101.º, al. c) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual — patrocínios são tratados como prestação de serviços (11,5%)." },
      { texto: "0% — sem retenção", porque: "Patrocínios pagos por empresas portuguesas com contabilidade organizada estão sujeitos a retenção de 11,5%." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º, n.º 1, al. c) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-33",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual o coeficiente do regime simplificado para rendimentos de direitos de autor de obra própria?",
    opcoes: [
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º — direitos de autor têm coeficiente 0,95." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços — direitos de autor têm tratamento específico (0,95)." },
      { texto: "0,95", porque: "Rendimentos de propriedade intelectual do titular originário (direitos de autor) têm coeficiente 0,95 (Art. 31.º, al. d) CIRS). Ou seja, 95% do rendimento é tributável." },
      { texto: "1,00", porque: "1,00 aplica-se ao regime de transparência fiscal, não a direitos de autor." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. d) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-34",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual a taxa de retenção na fonte sobre rendimentos de propriedade intelectual / direitos de autor?",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões do Art. 151.º — rendimentos de propriedade intelectual têm retenção de 16,5%." },
      { texto: "16,5%", porque: "Rendimentos de propriedade intelectual / direitos de autor estão sujeitos a retenção de 16,5% (Art. 101.º, n.º 1, al. b) CIRS)." },
      { texto: "11,5%", porque: "11,5% aplica-se a prestações de serviços fora do Art. 151.º — propriedade intelectual tem taxa própria de 16,5%." },
      { texto: "25%", porque: "Não existe taxa de retenção de 25% para rendimentos da categoria B." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º, n.º 1, al. b) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-35",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "O alojamento local em estabelecimento (tipo hostel/hotel) tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se ao alojamento local em moradia/apartamento — estabelecimentos têm coeficiente 0,15." },
      { texto: "0,50", porque: "0,50 aplica-se apenas ao alojamento local em zona de contenção." },
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º — alojamento local em estabelecimento tem 0,15." },
      { texto: "0,15", porque: "Alojamento local em estabelecimento (hotelaria) tem coeficiente 0,15 (Art. 31.º, al. a) CIRS), equiparado a hotelaria tradicional." },
    ],
    correta: 3,
    legalBasis: "Art. 31.º, al. a) CIRS — alojamento local (estabelecimento)",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-36",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual o coeficiente do regime simplificado para o alojamento local em moradia/apartamento situado em zona de contenção?",
    opcoes: [
      { texto: "0,15", porque: "0,15 é o coeficiente do alojamento local em estabelecimento, não em moradia em zona de contenção." },
      { texto: "0,35", porque: "0,35 aplica-se ao alojamento local em moradia/apartamento FORA de zona de contenção — em zona de contenção sobe para 0,50." },
      { texto: "0,50", porque: "Alojamento local em moradia/apartamento situado em zona de contenção (zona de pressão urbanística) tem coeficiente 0,50 (Art. 31.º, al. h) CIRS)." },
      { texto: "0,75", porque: "0,75 é para profissões liberais do Art. 151.º, não para alojamento local." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. h) CIRS",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-37",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Quando um trabalhador independente presta serviços a uma empresa estrangeira (não residente em Portugal), qual a retenção na fonte?",
    opcoes: [
      { texto: "23%", porque: "A retenção na fonte (Art. 101.º CIRS) só se aplica quando o cliente tem sede em Portugal — cliente estrangeiro = sem retenção." },
      { texto: "11,5%", porque: "A retenção na fonte não se aplica quando o cliente não é residente em Portugal." },
      { texto: "Depende do país do cliente.", porque: "A regra é clara: sem retenção quando o cliente não tem sede em Portugal, independentemente do país." },
      { texto: "0% — sem retenção.", porque: "Quando o cliente é não residente (empresa estrangeira), não há retenção na fonte de IRS — o Art. 101.º CIRS aplica-se apenas a pagamentos por entidades com sede em Portugal." },
    ],
    correta: 3,
    legalBasis: "Art. 101.º CIRS — retenção aplicável apenas a entidades residentes",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-38",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um fotógrafo freelance (não listado no Art. 151.º) tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º — fotógrafos não constam dessa tabela." },
      { texto: "0,35", porque: "Fotógrafos não listados no Art. 151.º enquadram-se como 'outras prestações de serviços' (Art. 31.º, al. c) CIRS), com coeficiente 0,35." },
      { texto: "0,95", porque: "0,95 aplica-se a rendimentos de propriedade intelectual — a prestação de serviços de fotografia tem coeficiente 0,35." },
      { texto: "0,15", porque: "0,15 aplica-se a vendas de bens e hotelaria, não a serviços de fotografia." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. c) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-39",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual o coeficiente para subsídios ou subvenções NÃO destinados à exploração, no regime simplificado?",
    opcoes: [
      { texto: "0,10", porque: "0,10 aplica-se a subsídios destinados à exploração — os não destinados à exploração têm coeficiente 0,30." },
      { texto: "0,30", porque: "Subsídios não destinados à exploração têm coeficiente 0,30 (Art. 31.º, al. e) CIRS). São tributados em 1/5 no ano e nos quatro seguintes." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços, não a subsídios." },
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º, não a subsídios." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. e) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-40",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual o coeficiente para subsídios destinados à exploração no regime simplificado?",
    opcoes: [
      { texto: "0,10", porque: "Subsídios destinados à exploração têm coeficiente 0,10 (Art. 31.º, al. f) CIRS) — apenas 10% do valor recebido é tributável." },
      { texto: "0,30", porque: "0,30 aplica-se a subsídios NÃO destinados à exploração — os destinados à exploração têm 0,10." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para subsídios." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços, não a subsídios." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 1, al. f) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-41",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um personal trainer (não listado no Art. 151.º) que presta serviços a um ginásio com contabilidade organizada tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões listadas no Art. 151.º — personal trainers não constam dessa tabela." },
      { texto: "0% — sem retenção", porque: "Personal trainers estão sujeitos a retenção de 11,5% quando faturam a entidades com contabilidade organizada." },
      { texto: "11,5%", porque: "Personal trainers, fora do Art. 151.º, enquadram-se como 'outras prestações de serviços', com retenção de 11,5% (Art. 101.º, al. c) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a serviços de treino pessoal." },
    ],
    correta: 2,
    legalBasis: "Art. 101.º, n.º 1, al. c) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-42",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "A regra dos 15% (Art. 31.º, n.º 2 CIRS) aplica-se a que coeficientes do regime simplificado?",
    opcoes: [
      { texto: "A todos os coeficientes sem exceção.", porque: "A regra dos 15% aplica-se apenas aos coeficientes 0,75 e 0,35 (alíneas b) e c) do Art. 31.º CIRS)." },
      { texto: "Apenas ao coeficiente 0,75.", porque: "A regra dos 15% aplica-se tanto ao coeficiente 0,75 como ao 0,35." },
      { texto: "Aos coeficientes 0,75 e 0,35.", porque: "A regra dos 15% exige a comprovação de despesas de pelo menos 15% do rendimento para manter os coeficientes 0,75 (Art. 151.º) e 0,35 (outros serviços)." },
      { texto: "Apenas ao coeficiente 0,15.", porque: "O coeficiente 0,15 (vendas de bens) está isento da regra dos 15%." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 2 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-43",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual o coeficiente e a retenção para um consultor de marketing (fora do Art. 151.º)?",
    opcoes: [
      { texto: "Coeficiente 0,75 e retenção 23%.", porque: "Estes valores aplicam-se a profissões do Art. 151.º — consultoria de marketing, quando fora da tabela, tem coeficiente 0,35 e retenção 11,5%." },
      { texto: "Coeficiente 0,35 e retenção 11,5%.", porque: "Consultores de marketing fora do Art. 151.º enquadram-se como 'outras prestações de serviços' (código 1519), com coeficiente 0,35 e retenção 11,5%." },
      { texto: "Coeficiente 0,15 e sem retenção.", porque: "0,15 e sem retenção aplica-se a vendas de bens, não a consultoria." },
      { texto: "Coeficiente 0,95 e retenção 16,5%.", porque: "0,95/16,5% aplica-se a propriedade intelectual, não a consultoria de marketing." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. c) CIRS · Art. 101.º, al. c) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-44",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um trabalhador independente que fatura menos de 15 000 EUR por ano pode pedir dispensa de retenção na fonte. Essa dispensa aplica-se a que situação?",
    opcoes: [
      { texto: "Aplica-se automaticamente a todos os trabalhadores independentes.", porque: "A dispensa não é automática — o trabalhador deve solicitar a dispensa junto das Finanças." },
      { texto: "Aplica-se quando o rendimento anual estimado é inferior a 15 000 EUR.", porque: "A dispensa de retenção na fonte pode ser solicitada quando o trabalhador preveja faturar menos de 15 000 EUR/ano (Art. 101.º-B CIRS). Deve ser comunicada à AT." },
      { texto: "Só se aplica a vendas de bens.", porque: "A dispensa aplica-se a qualquer atividade sujeita a retenção, não apenas a vendas (que já não têm retenção)." },
      { texto: "Não existe dispensa — a retenção é sempre obrigatória.", porque: "Existe dispensa de retenção para quem preveja faturar menos de 15 000 EUR/ano, ao abrigo do Art. 101.º-B CIRS." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º-B CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-45",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um mediador imobiliário certificado pelo IMPIC (código 1330 do Art. 151.º) tem retenção de:",
    opcoes: [
      { texto: "11,5%", porque: "11,5% aplica-se a mediadores não certificados (fora do Art. 151.º) — os certificados com código 1330 têm 23%." },
      { texto: "23%", porque: "Mediadores imobiliários certificados (código 1330) constam do Art. 151.º CIRS, com retenção de 23%." },
      { texto: "0% — sem retenção", porque: "A mediação imobiliária é uma prestação de serviços sujeita a retenção na fonte." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a mediação imobiliária." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 1330) · Art. 101.º, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-46",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Se um designer (código 1336, Art. 151.º) prestar serviços a uma empresa sediada na Alemanha, qual a retenção?",
    opcoes: [
      { texto: "23%", porque: "23% aplicar-se-ia se o cliente fosse residente em Portugal — cliente estrangeiro = sem retenção." },
      { texto: "0% — sem retenção", porque: "Quando o cliente não tem sede em Portugal, não há retenção na fonte de IRS, independentemente da atividade do prestador (Art. 101.º CIRS)." },
      { texto: "11,5%", porque: "11,5% não se aplica ao código 1336 (designer, Art. 151.º), e para clientes estrangeiros não há retenção." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual — mas para clientes estrangeiros não há retenção de qualquer forma." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º CIRS — retenção aplicável apenas a entidades residentes",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-47",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "A Segurança Social de um prestador de serviços do Art. 151.º incide sobre que percentagem do rendimento relevante?",
    opcoes: [
      { texto: "20%", porque: "20% aplica-se a vendas de bens e hotelaria — prestação de serviços tem base de 70%." },
      { texto: "70%", porque: "A Segurança Social dos prestadores de serviços incide sobre 70% do rendimento relevante (Art. 162.º do Código Contributivo)." },
      { texto: "50%", porque: "Não existe base de 50% no regime de trabalhador independente." },
      { texto: "100%", porque: "A SS nunca incide sobre 100% do rendimento — para serviços é 70%." },
    ],
    correta: 1,
    legalBasis: "Art. 162.º Código Contributivo",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-48",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um músico (código 2013 do Art. 151.º) que atua como trabalhador independente tem coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 é para serviços fora do Art. 151.º — músicos constam dessa tabela (código 2013)." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual — a prestação de serviços de música ao vivo tem coeficiente 0,75." },
      { texto: "0,75", porque: "Músicos (código 2013) estão na tabela do Art. 151.º CIRS, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços artísticos." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-49",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um estafeta / motorista de entregas (transporte de mercadorias) tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços — transporte de mercadorias é equiparado a vendas/hotelaria, com coeficiente 0,15." },
      { texto: "0,75", porque: "0,75 é para profissões do Art. 151.º — transporte de mercadorias tem coeficiente 0,15." },
      { texto: "0,15", porque: "Transporte de mercadorias / estafetas têm coeficiente 0,15 (Art. 31.º, al. a) CIRS), sem retenção na fonte, e Segurança Social sobre 20%." },
      { texto: "0,50", porque: "0,50 é exclusivo do alojamento local em zona de contenção." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. a) CIRS — transportes",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-50",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um artesão que produz e vende os seus próprios produtos tem, no regime simplificado:",
    opcoes: [
      { texto: "Coeficiente 0,75 e retenção 23%.", porque: "Estes valores aplicam-se a profissões do Art. 151.º — a produção artesanal enquadra-se como venda de bens (0,15, sem retenção)." },
      { texto: "Coeficiente 0,15 e sem retenção.", porque: "A produção e venda de artesanato enquadra-se como venda de bens (Art. 31.º, al. a) CIRS), com coeficiente 0,15 e sem retenção na fonte." },
      { texto: "Coeficiente 0,35 e retenção 11,5%.", porque: "0,35/11,5% aplica-se a prestação de serviços fora do Art. 151.º — a venda de produtos artesanais é venda de bens (0,15)." },
      { texto: "Coeficiente 0,95 e retenção 16,5%.", porque: "0,95/16,5% aplica-se a propriedade intelectual, não a produção artesanal." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. a) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-51",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um dentista (código 7010 do Art. 151.º) tem retenção na fonte de:",
    opcoes: [
      { texto: "0% — sem retenção", porque: "Dentistas do Art. 151.º estão sujeitos a retenção de 23%." },
      { texto: "11,5%", porque: "11,5% é para atividades fora do Art. 151.º — dentistas constam dessa tabela." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a serviços de medicina dentária." },
      { texto: "23%", porque: "Dentistas (código 7010) estão na tabela do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
    ],
    correta: 3,
    legalBasis: "Art. 151.º CIRS (código 7010) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-52",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "A regra dos 15% aplica-se ao coeficiente 0,15 (vendas de bens)?",
    opcoes: [
      { texto: "Sim, aplica-se a todos os coeficientes.", porque: "A regra dos 15% aplica-se apenas aos coeficientes 0,75 e 0,35, não ao 0,15." },
      { texto: "Sim, mas apenas no primeiro ano de atividade.", porque: "A regra dos 15% não se aplica ao coeficiente 0,15, independentemente do ano." },
      { texto: "Não — a regra dos 15% só se aplica aos coeficientes 0,75 e 0,35.", porque: "A regra dos 15% (Art. 31.º, n.º 2 CIRS) exige comprovação de despesas apenas para os coeficientes 0,75 (al. b) e 0,35 (al. c). Vendas (0,15) estão isentas." },
      { texto: "Não — aplica-se apenas ao coeficiente 0,75.", porque: "A regra aplica-se tanto ao 0,75 como ao 0,35, mas não ao 0,15." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 2 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-53",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um auditor (código 4011 do Art. 151.º) que fatura a uma empresa em Lisboa tem coeficiente de:",
    opcoes: [
      { texto: "0,75", porque: "Auditores (código 4011) constam do Art. 151.º CIRS, com coeficiente 0,75 no regime simplificado (Art. 31.º, al. b) CIRS)." },
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — auditores estão na tabela." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a serviços de auditoria." },
      { texto: "1,00", porque: "1,00 aplica-se ao regime de transparência fiscal, não a serviços de auditoria." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-54",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Uma modelo profissional (fora do Art. 151.º) que recebe de uma agência portuguesa tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões do Art. 151.º — modelos não constam dessa tabela." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual — serviços de modelagem são prestação de serviços (11,5%)." },
      { texto: "0% — sem retenção", porque: "Modelos que faturam a entidades com contabilidade organizada estão sujeitas a retenção de 11,5%." },
      { texto: "11,5%", porque: "Modelos profissionais, fora do Art. 151.º, enquadram-se como 'outras prestações de serviços' (código 1519), com retenção de 11,5%." },
    ],
    correta: 3,
    legalBasis: "Art. 101.º, n.º 1, al. c) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-55",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um notário (código 9011 do Art. 151.º) tem, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — notários constam dessa tabela." },
      { texto: "0,75", porque: "Notários (código 9011) estão na tabela do Art. 151.º CIRS, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "1,00", porque: "1,00 aplica-se ao regime de transparência fiscal, não a serviços notariais." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a serviços notariais." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-56",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um explicador / tutor privado que não está registado no Art. 151.º (código 1519) tem coeficiente de:",
    opcoes: [
      { texto: "0,75", porque: "0,75 aplicar-se-ia se estivesse registado com código 8010 (Explicadores) do Art. 151.º — com o código 1519 o coeficiente é 0,35." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços de explicação." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a serviços de ensino." },
      { texto: "0,35", porque: "Com o código residual 1519, o coeficiente é 0,35 (Art. 31.º, al. c) CIRS). Se se registasse como Explicador (8010) no Art. 151.º, passaria a 0,75." },
    ],
    correta: 3,
    legalBasis: "Art. 31.º, al. c) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-57",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um revisor oficial de contas (código 9010 do Art. 151.º) tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "Revisores oficiais de contas (código 9010) constam do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora do Art. 151.º — ROC constam da tabela." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a serviços de revisão de contas." },
      { texto: "0% — sem retenção", porque: "A prestação de serviços de ROC está sujeita a retenção de 23%." },
    ],
    correta: 0,
    legalBasis: "Art. 151.º CIRS (código 9010) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-58",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Subsídios não destinados à exploração estão sujeitos a retenção na fonte?",
    opcoes: [
      { texto: "Sim, 23%.", porque: "Subsídios não destinados à exploração não estão sujeitos a retenção na fonte." },
      { texto: "Sim, 11,5%.", porque: "Subsídios desta natureza não estão sujeitos a retenção na fonte de IRS." },
      { texto: "Não — sem retenção.", porque: "Subsídios não destinados à exploração não estão sujeitos a retenção na fonte de IRS. Têm coeficiente 0,30 e são tributados em 1/5 no ano de recebimento e nos quatro seguintes." },
      { texto: "Sim, 16,5%.", porque: "16,5% aplica-se a propriedade intelectual — subsídios não têm retenção." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. e) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-59",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual a diferença entre o alojamento local em 'estabelecimento' e em 'moradia/apartamento' no que toca ao coeficiente?",
    opcoes: [
      { texto: "Ambos têm coeficiente 0,15.", porque: "Apenas o estabelecimento tem 0,15 — moradia/apartamento tem 0,35 (ou 0,50 em zona de contenção)." },
      { texto: "Estabelecimento tem 0,15 e moradia/apartamento tem 0,35.", porque: "O alojamento local em estabelecimento tem coeficiente 0,15 (hotelaria); em moradia/apartamento é 0,35 (fora de zona de contenção) ou 0,50 (em zona de contenção)." },
      { texto: "Ambos têm coeficiente 0,35.", porque: "Apenas moradia/apartamento (fora de contenção) tem 0,35 — estabelecimento tem 0,15." },
      { texto: "Estabelecimento tem 0,35 e moradia/apartamento tem 0,15.", porque: "É ao contrário: estabelecimento 0,15, moradia/apartamento 0,35." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º CIRS — alojamento local",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-60",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Qual a base de Segurança Social para quem faz vendas de bens como trabalhador independente?",
    opcoes: [
      { texto: "70% do rendimento relevante.", porque: "70% aplica-se a prestação de serviços — vendas de bens têm base de 20%." },
      { texto: "20% do rendimento relevante.", porque: "Para vendas de bens e hotelaria, a Segurança Social incide sobre 20% do rendimento relevante (Art. 162.º do Código Contributivo)." },
      { texto: "50% do rendimento relevante.", porque: "Não existe base de 50% no regime de trabalhador independente." },
      { texto: "35% do rendimento relevante.", porque: "35% não é uma base de SS — as opções são 70% (serviços) ou 20% (bens)." },
    ],
    correta: 1,
    legalBasis: "Art. 162.º Código Contributivo",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-61",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um geólogo (código 1005 do Art. 151.º) tem retenção na fonte de:",
    opcoes: [
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora do Art. 151.º — geólogos constam dessa tabela." },
      { texto: "23%", porque: "Geólogos (código 1005) estão na tabela do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a serviços de geologia." },
      { texto: "0% — sem retenção", porque: "Geólogos do Art. 151.º estão sujeitos a retenção de 23%." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 1005) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-62",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um guionista que recebe direitos de autor pela sua obra original tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões do Art. 151.º — rendimentos de direitos de autor têm retenção de 16,5%." },
      { texto: "11,5%", porque: "11,5% aplica-se a prestações de serviços fora do Art. 151.º — direitos de autor têm taxa própria." },
      { texto: "16,5%", porque: "Rendimentos de direitos de autor (propriedade intelectual) estão sujeitos a retenção de 16,5% (Art. 101.º, al. b) CIRS)." },
      { texto: "0% — sem retenção", porque: "Direitos de autor pagos por entidades residentes estão sujeitos a retenção de 16,5%." },
    ],
    correta: 2,
    legalBasis: "Art. 101.º, n.º 1, al. b) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-63",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "A regra dos 15% aplica-se a rendimentos de propriedade intelectual (coeficiente 0,95)?",
    opcoes: [
      { texto: "Sim, aplica-se a todos os tipos de rendimento.", porque: "A regra dos 15% só se aplica aos coeficientes 0,75 e 0,35 — o coeficiente 0,95 está isento." },
      { texto: "Não — só se aplica aos coeficientes 0,75 e 0,35.", porque: "A regra dos 15% (Art. 31.º, n.º 2 CIRS) aplica-se apenas às alíneas b) (0,75) e c) (0,35). Rendimentos de propriedade intelectual (coef. 0,95, al. d) estão isentos." },
      { texto: "Sim, mas apenas acima de 50 000 EUR.", porque: "A regra dos 15% depende do tipo de coeficiente, não do volume de negócios." },
      { texto: "Sim, com exigência de 25% em vez de 15%.", porque: "Não existe exigência de 25% — a regra dos 15% aplica-se apenas aos coeficientes 0,75 e 0,35." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 2 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-64",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um DJ profissional (fora do Art. 151.º) que atua em eventos tem coeficiente de:",
    opcoes: [
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º — DJ profissional (fora da tabela) tem coeficiente 0,35." },
      { texto: "0,35", porque: "DJ profissional, fora do Art. 151.º, enquadra-se como 'outras prestações de serviços' (código 1519), com coeficiente 0,35." },
      { texto: "0,15", porque: "0,15 aplica-se a vendas de bens e hotelaria, não a espetáculos." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a atuações ao vivo." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. c) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-65",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um publicitário (código 1333 do Art. 151.º) tem coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — publicitários com código 1333 estão na tabela." },
      { texto: "0,75", porque: "Publicitários (código 1333) constam do Art. 151.º CIRS, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a serviços de publicidade." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para publicidade." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-66",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "A regra dos 15% aplica-se ao regime de transparência fiscal (coeficiente 1,00)?",
    opcoes: [
      { texto: "Sim, aplica-se porque o coeficiente é superior a 0,75.", porque: "A regra dos 15% só se aplica aos coeficientes 0,75 e 0,35 — a transparência fiscal (1,00) está isenta." },
      { texto: "Não — a regra dos 15% aplica-se apenas aos coeficientes 0,75 e 0,35.", porque: "O regime de transparência fiscal (coef. 1,00, Art. 31.º, al. g) CIRS) não está sujeito à regra dos 15%, que se limita às alíneas b) e c)." },
      { texto: "Sim, com uma exigência de 20%.", porque: "Não existe variação da regra para o regime de transparência fiscal — a regra dos 15% simplesmente não se aplica." },
      { texto: "Depende da atividade da sociedade.", porque: "A regra dos 15% é determinada pelo coeficiente, não pela atividade da sociedade." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 2 CIRS · Art. 31.º, al. g) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-67",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "No primeiro ano de atividade, um programador (código 1332, coef. 0,75) beneficia de uma redução do coeficiente de:",
    opcoes: [
      { texto: "25%", porque: "25% é a redução no 2.º ano de atividade — no 1.º ano a redução é de 50%." },
      { texto: "75%", porque: "Não existe redução de 75% do coeficiente. As reduções são 50% no 1.º ano e 25% no 2.º ano." },
      { texto: "50%", porque: "No 1.º ano de atividade, o coeficiente do regime simplificado é reduzido em 50% (Art. 31.º, n.º 10 CIRS). Para o programador: 0,75 x 50% = coeficiente efetivo de 0,375." },
      { texto: "0% — sem redução", porque: "Existe sim redução: 50% no 1.º ano e 25% no 2.º ano (Art. 31.º, n.º 10 CIRS)." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 10 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-68",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "No segundo ano de atividade, o coeficiente do regime simplificado é reduzido em:",
    opcoes: [
      { texto: "50%", porque: "50% é a redução no 1.º ano — no 2.º ano a redução é de 25%." },
      { texto: "10%", porque: "Não existe redução de 10% — as reduções são 50% (1.º ano) e 25% (2.º ano)." },
      { texto: "25%", porque: "No 2.º ano de atividade, o coeficiente do regime simplificado é reduzido em 25% (Art. 31.º, n.º 10 CIRS)." },
      { texto: "0% — sem redução", porque: "Existe sim redução no 2.º ano: 25% (Art. 31.º, n.º 10 CIRS)." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 10 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-69",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Se um advogado (código 6010, coef. 0,75) iniciar atividade, qual será o coeficiente efetivo no 1.º ano (com a redução de 50%)?",
    opcoes: [
      { texto: "0,75", porque: "0,75 é o coeficiente normal — com a redução de 50% no 1.º ano, o efetivo é 0,375." },
      { texto: "0,375", porque: "No 1.º ano, o coeficiente 0,75 é reduzido em 50%: 0,75 x (1 - 0,50) = 0,375. Ou seja, apenas 37,5% do rendimento é tributável." },
      { texto: "0,50", porque: "0,50 não corresponde à redução de 50% sobre 0,75 — o resultado correto é 0,375." },
      { texto: "0,5625", porque: "0,5625 resultaria de uma redução de 25% (2.º ano), não de 50% (1.º ano)." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 10 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-70",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente com código 1519 (coef. 0,35) iniciar atividade, qual será o coeficiente efetivo no 2.º ano (com a redução de 25%)?",
    opcoes: [
      { texto: "0,175", porque: "0,175 seria com a redução de 50% (1.º ano) — no 2.º ano a redução é de 25%, resultando em 0,2625." },
      { texto: "0,35", porque: "0,35 é o coeficiente normal — com a redução de 25%, o efetivo é 0,2625." },
      { texto: "0,2625", porque: "No 2.º ano, o coeficiente é reduzido em 25%: 0,35 x (1 - 0,25) = 0,2625." },
      { texto: "0,30", porque: "0,30 não resulta de nenhuma redução sobre 0,35 — o correto é 0,35 x 0,75 = 0,2625." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 10 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-71",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "No regime de transparência fiscal (coeficiente 1,00), que percentagem do rendimento é efetivamente tributada no regime simplificado?",
    opcoes: [
      { texto: "75%", porque: "75% aplica-se ao coeficiente 0,75 (Art. 151.º) — na transparência fiscal é 100%." },
      { texto: "95%", porque: "95% aplica-se ao coeficiente 0,95 (propriedade intelectual) — na transparência fiscal é 100%." },
      { texto: "50%", porque: "Não existe coeficiente de 0,50 para transparência fiscal." },
      { texto: "100%", porque: "Com coeficiente 1,00 (Art. 31.º, al. g) CIRS), todo o rendimento é considerado tributável. Este regime aplica-se quando se prestam serviços a sociedade onde se detém 5% ou mais do capital por mais de 183 dias." },
    ],
    correta: 3,
    legalBasis: "Art. 31.º, n.º 1, al. g) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-72",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um trabalhador independente que presta serviços exclusivamente a uma sociedade onde detém 3% do capital está sujeito ao regime de transparência fiscal?",
    opcoes: [
      { texto: "Sim, desde que trabalhe mais de 183 dias.", porque: "O regime de transparência fiscal exige participação de 5% ou mais — com 3% não se aplica." },
      { texto: "Não — o mínimo de participação é 5%.", porque: "O regime de transparência fiscal (Art. 31.º, al. g) CIRS) exige detenção de 5% ou mais do capital social. Com 3%, o trabalhador não está sujeito a este regime e usa o coeficiente normal da sua atividade." },
      { texto: "Sim, qualquer participação ativa a transparência.", porque: "Não é qualquer participação — o mínimo legal é 5% do capital." },
      { texto: "Depende do volume de faturação.", porque: "A transparência fiscal depende da percentagem de participação (mínimo 5%) e duração (183 dias), não do volume de faturação." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. g) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-73",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um trabalhador com atividades mistas (serviços do Art. 151.º e venda de bens) deve declarar os rendimentos:",
    opcoes: [
      { texto: "Todos com o coeficiente mais alto (0,75).", porque: "Os rendimentos de cada atividade são declarados com o respetivo coeficiente — não se usa o mais alto para tudo." },
      { texto: "Todos com o coeficiente mais baixo (0,15).", porque: "Os rendimentos de cada atividade são declarados com o respetivo coeficiente — não se usa o mais baixo." },
      { texto: "Separadamente, cada tipo com o seu coeficiente (0,75 para serviços e 0,15 para vendas).", porque: "Em atividades mistas, cada tipo de rendimento é declarado com o respetivo coeficiente: serviços do Art. 151.º com 0,75 e vendas com 0,15." },
      { texto: "Com a média dos dois coeficientes.", porque: "Não se faz média de coeficientes — cada rendimento é declarado com o coeficiente da respetiva atividade." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º CIRS — atividades mistas",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-74",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um programador (código 1332, Art. 151.º) que também cede licenças de software próprio tem dois tipos de rendimento. Como são tributados no regime simplificado?",
    opcoes: [
      { texto: "Ambos com coeficiente 0,75.", porque: "A cedência de licenças de software é propriedade intelectual (coef. 0,95) — não se aplica o coeficiente de serviços a ambos." },
      { texto: "Serviços com 0,75 e licenças com 0,95.", porque: "A prestação de serviços de programação tem coeficiente 0,75 (Art. 31.º, al. b) CIRS) e a cedência de licenças de software próprio tem coeficiente 0,95 (Art. 31.º, al. d) CIRS — propriedade intelectual)." },
      { texto: "Ambos com coeficiente 0,95.", porque: "Os serviços de programação têm coeficiente 0,75 — só as licenças de software são propriedade intelectual (0,95)." },
      { texto: "Serviços com 0,35 e licenças com 0,75.", porque: "Programadores do Art. 151.º têm coeficiente 0,75, não 0,35 — e licenças de software são 0,95." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. b) e d) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-75",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um trabalhador independente que muda de atividade (ex.: de programador 1332 para consultor 1519) deve:",
    opcoes: [
      { texto: "Não fazer nada — a mudança é automática.", porque: "A alteração de atividade deve ser comunicada formalmente às Finanças." },
      { texto: "Comunicar a alteração de atividade no Portal das Finanças e atualizar o CAE/CIRS.", porque: "A alteração de atividade deve ser comunicada à AT (Portal das Finanças), dentro de 15 dias, atualizando o código da atividade. Isto pode alterar o coeficiente (de 0,75 para 0,35) e a retenção (de 23% para 11,5%)." },
      { texto: "Fechar a atividade e abrir uma nova.", porque: "Não é necessário fechar e reabrir — basta alterar a atividade registada junto das Finanças." },
      { texto: "Esperar pelo final do ano fiscal.", porque: "A alteração deve ser comunicada no prazo de 15 dias, não no final do ano." },
    ],
    correta: 1,
    legalBasis: "Art. 112.º CIRS — alterações de atividade",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-76",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Uma pessoa que explora alojamento local em moradia e que NÃO exerce outra atividade pode beneficiar de isenção de Segurança Social?",
    opcoes: [
      { texto: "Sim, automaticamente.", porque: "A potencial isenção de SS para AL em moradia/apartamento é condicional à exclusividade e não é aplicada automaticamente — deve ser confirmada com contabilista." },
      { texto: "Não, nunca.", porque: "A legislação prevê a possibilidade de isenção condicional para AL em moradia exercido em exclusivo, embora não seja automática." },
      { texto: "Possivelmente — a isenção é condicional à exclusividade e deve ser confirmada com contabilista.", porque: "A eventual isenção de Segurança Social para AL em moradia/apartamento depende de exercer AL em exclusivo. É condicional e não automática — o trabalhador deve confirmar o enquadramento com o seu contabilista." },
      { texto: "Sim, se faturar menos de 15 000 EUR.", porque: "A potencial isenção de SS para AL não depende do volume de faturação, mas da exclusividade do exercício da atividade." },
    ],
    correta: 2,
    legalBasis: "Código Contributivo — alojamento local",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-77",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um designer (código 1336, coef. 0,75) tem de justificar que percentagem mínima do rendimento em despesas para manter o coeficiente (regra dos 15%)?",
    opcoes: [
      { texto: "25%", porque: "A regra exige 15%, não 25%. Sem justificar 15%, o rendimento tributável pode ser ajustado." },
      { texto: "15%", porque: "No regime simplificado, para os coeficientes 0,75 e 0,35, a regra dos 15% (Art. 31.º, n.º 2 CIRS) exige que o trabalhador justifique despesas de pelo menos 15% do rendimento bruto. Caso contrário, o rendimento tributável aumenta." },
      { texto: "10%", porque: "A obrigação é de 15%, não 10% (Art. 31.º, n.º 2 CIRS)." },
      { texto: "0% — não precisa justificar despesas.", porque: "O regime simplificado com coeficiente 0,75 está sujeito à regra dos 15%." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 2 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-78",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Se um fotógrafo (código 1519, coef. 0,35) ceder os direitos de autor das suas fotografias a uma editora, qual o coeficiente aplicável a essa cedência?",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se à prestação de serviços — a cedência de direitos de autor tem coeficiente 0,95." },
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º — a cedência de direitos de autor é propriedade intelectual (0,95)." },
      { texto: "0,95", porque: "A cedência de direitos de autor de fotografias é rendimento de propriedade intelectual (Art. 31.º, al. d) CIRS), com coeficiente 0,95. A prestação do serviço de fotografia mantém o coeficiente 0,35." },
      { texto: "0,15", porque: "0,15 é para vendas de bens — a cedência de direitos de autor tem coeficiente 0,95." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. d) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-79",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Qual o coeficiente efetivo de um trabalhador com código 1519 (coef. 0,35) no 1.º ano de atividade, com a redução de 50%?",
    opcoes: [
      { texto: "0,175", porque: "No 1.º ano, o coeficiente 0,35 é reduzido em 50%: 0,35 x (1 - 0,50) = 0,175. Apenas 17,5% do rendimento é tributável." },
      { texto: "0,35", porque: "0,35 é o coeficiente normal — com a redução de 50% no 1.º ano, baixa para 0,175." },
      { texto: "0,2625", porque: "0,2625 resulta da redução de 25% (2.º ano), não de 50% (1.º ano)." },
      { texto: "0,25", porque: "0,25 não resulta de nenhuma redução sobre 0,35 — o correto é 0,175." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 10 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-80",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um alojamento local em moradia/apartamento fora de zona de contenção está sujeito à regra dos 15%?",
    opcoes: [
      { texto: "Sim, porque o coeficiente é 0,35.", porque: "Embora o coeficiente seja 0,35, o alojamento local em moradia tem regra15=false — não se aplica a regra dos 15%." },
      { texto: "Não — o alojamento local em moradia está isento da regra dos 15%.", porque: "O alojamento local em moradia/apartamento (coef. 0,35) tem uma isenção específica da regra dos 15%, apesar de o coeficiente ser o mesmo das 'outras prestações de serviços'." },
      { texto: "Sim, como qualquer atividade com coeficiente 0,35.", porque: "O alojamento local em moradia é uma exceção: apesar do coeficiente 0,35, está isento da regra dos 15%." },
      { texto: "Depende do volume de hóspedes.", porque: "A aplicação da regra dos 15% depende do regime fiscal, não do volume de hóspedes." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º CIRS — alojamento local (moradia/apartamento)",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-81",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "A Segurança Social de um proprietário de alojamento local em estabelecimento incide sobre:",
    opcoes: [
      { texto: "70% do rendimento relevante.", porque: "70% aplica-se a prestação de serviços — alojamento local em estabelecimento é equiparado a hotelaria (20%)." },
      { texto: "20% do rendimento relevante.", porque: "Alojamento local em estabelecimento é equiparado a hotelaria, pelo que a SS incide sobre 20% do rendimento relevante (base 'bens')." },
      { texto: "0% — isento de Segurança Social.", porque: "O alojamento local em estabelecimento não é automaticamente isento de SS — a base é 20%." },
      { texto: "50% do rendimento relevante.", porque: "Não existe base de 50% no regime de trabalhador independente." },
    ],
    correta: 1,
    legalBasis: "Art. 162.º Código Contributivo — hotelaria",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-82",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um advogado (código 6010) que fatura 10 000 EUR a um cliente português e 40 000 EUR a clientes estrangeiros. Quanto é retido na fonte no total?",
    opcoes: [
      { texto: "11 500 EUR (23% sobre 50 000 EUR).", porque: "A retenção só se aplica aos 10 000 EUR faturados ao cliente português — clientes estrangeiros = sem retenção." },
      { texto: "2 300 EUR (23% sobre 10 000 EUR).", porque: "A retenção na fonte aplica-se apenas aos pagamentos de entidades residentes em Portugal. 23% sobre 10 000 EUR = 2 300 EUR. Os 40 000 EUR de clientes estrangeiros não têm retenção." },
      { texto: "0 EUR — sem retenção porque a maioria é estrangeira.", porque: "A retenção aplica-se recibo a recibo — os 10 000 EUR do cliente português estão sujeitos a 23%, independentemente do peso dos clientes estrangeiros." },
      { texto: "5 750 EUR (11,5% sobre 50 000 EUR).", porque: "A taxa de retenção para advogados é 23% (não 11,5%), e apenas sobre os 10 000 EUR do cliente residente." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º CIRS — retenção aplicável apenas a entidades residentes",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-83",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Se um trabalhador independente (código 1519, coef. 0,35) não justificar despesas de 15% do rendimento, o que acontece ao rendimento tributável?",
    opcoes: [
      { texto: "Nada — o coeficiente mantém-se igual.", porque: "Sem justificar 15%, o rendimento tributável pode ser ajustado em alta (regra dos 15%, Art. 31.º, n.º 2 CIRS)." },
      { texto: "O coeficiente sobe para 0,75.", porque: "O coeficiente não sobe para 0,75 — a penalização é sobre o rendimento tributável, não uma mudança de coeficiente." },
      { texto: "A diferença entre as despesas justificadas e 15% do rendimento é adicionada ao rendimento tributável.", porque: "Quando o trabalhador não comprova despesas de pelo menos 15% do rendimento, a diferença entre as despesas efetivas e os 15% exigidos é adicionada ao rendimento tributável (Art. 31.º, n.º 2 CIRS)." },
      { texto: "Perde o regime simplificado e passa a contabilidade organizada.", porque: "O incumprimento da regra dos 15% não obriga à mudança de regime — apenas ajusta o rendimento tributável." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 2 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-84",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Subsídios destinados à exploração estão sujeitos à regra dos 15%?",
    opcoes: [
      { texto: "Sim, como qualquer rendimento com coeficiente baixo.", porque: "Subsídios destinados à exploração (coef. 0,10) não estão sujeitos à regra dos 15%, que se limita aos coeficientes 0,75 e 0,35." },
      { texto: "Sim, com exigência reduzida de 10%.", porque: "Não existe versão reduzida da regra — os subsídios simplesmente não estão sujeitos." },
      { texto: "Não — os subsídios (coef. 0,10) estão isentos da regra dos 15%.", porque: "Subsídios destinados à exploração (Art. 31.º, al. f) CIRS) têm coeficiente 0,10 e não estão sujeitos à regra dos 15%, que se aplica apenas às alíneas b) (0,75) e c) (0,35)." },
      { texto: "Depende do montante do subsídio.", porque: "A aplicação da regra dos 15% depende do tipo de coeficiente, não do montante." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 2 CIRS · Art. 31.º, al. f) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-85",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um influencer que recebe 30 000 EUR em patrocínios (serviços, coef. 0,35) e 10 000 EUR em royalties de conteúdo próprio (coef. 0,95). Qual o rendimento tributável total no regime simplificado?",
    opcoes: [
      { texto: "20 000 EUR (0,50 x 40 000).", porque: "Não se aplica um coeficiente médio — cada tipo de rendimento usa o seu coeficiente." },
      { texto: "40 000 EUR (100%).", porque: "O regime simplificado aplica coeficientes ao rendimento — não tributa 100%." },
      { texto: "20 000 EUR (0,75 x 30 000 - alguma dedução).", porque: "O coeficiente para serviços fora do Art. 151.º é 0,35 (não 0,75), e royalties é 0,95." },
      { texto: "20 000 EUR (0,35 x 30 000 + 0,95 x 10 000 = 10 500 + 9 500).", porque: "Serviços (patrocínios): 30 000 x 0,35 = 10 500 EUR. Royalties: 10 000 x 0,95 = 9 500 EUR. Total tributável: 20 000 EUR." },
    ],
    correta: 3,
    legalBasis: "Art. 31.º, al. c) e d) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-86",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Qual a condição temporal para se aplicar o regime de transparência fiscal (coeficiente 1,00)?",
    opcoes: [
      { texto: "Prestar serviços à sociedade durante mais de 90 dias por ano.", porque: "O limiar é 183 dias, não 90 dias (Art. 31.º, al. g) CIRS)." },
      { texto: "Prestar serviços à sociedade durante mais de 183 dias por ano.", porque: "O regime de transparência fiscal aplica-se quando se prestam serviços a sociedade onde se detém 5% ou mais do capital durante mais de 183 dias por ano (Art. 31.º, al. g) CIRS)." },
      { texto: "Prestar serviços durante todo o ano civil (365 dias).", porque: "O limiar é 183 dias, não 365 dias." },
      { texto: "Não há condição temporal — basta deter 5%.", porque: "Há sim condição temporal: é necessário prestar serviços durante mais de 183 dias por ano." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. g) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-87",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "O alojamento local em zona de contenção exige que formulário adicional na declaração de IRS?",
    opcoes: [
      { texto: "Anexo B apenas.", porque: "Além do Anexo B, o alojamento local em zona de contenção exige o Anexo 13F." },
      { texto: "Nenhum formulário adicional.", porque: "O alojamento local em zona de contenção exige o Anexo 13F na declaração de IRS." },
      { texto: "Anexo 13F.", porque: "O alojamento local em moradia/apartamento em zona de contenção (coef. 0,50) exige o preenchimento do Anexo 13F na declaração de IRS, para comprovar a localização em zona de pressão urbanística." },
      { texto: "Anexo SS.", porque: "O Anexo SS é para a Segurança Social — o formulário específico para AL em zona de contenção é o Anexo 13F." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. h) CIRS — zona de contenção",
    fonte: fonte("alojamentoLocal"),
  },
  {
    id: "ativ-88",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Quando um trabalhador independente tem dispensa de retenção (< 15 000 EUR/ano) e fatura a uma empresa portuguesa, o cliente retém na fonte?",
    opcoes: [
      { texto: "Sim, a empresa retém sempre.", porque: "Se o trabalhador obteve dispensa de retenção junto da AT, a empresa cliente não retém." },
      { texto: "Não — o trabalhador comunica a dispensa e a empresa não retém.", porque: "Quando o trabalhador obtém dispensa de retenção (Art. 101.º-B CIRS), deve comunicar esta dispensa ao cliente. A empresa deixa de reter na fonte, mas o trabalhador continua sujeito a IRS no apuramento anual." },
      { texto: "Sim, mas a uma taxa reduzida de 5%.", porque: "Não existe taxa reduzida de 5% — com dispensa, a retenção é 0%." },
      { texto: "Depende se a empresa é PME ou grande empresa.", porque: "A dispensa de retenção não depende da dimensão da empresa cliente." },
    ],
    correta: 1,
    legalBasis: "Art. 101.º-B CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-89",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Subsídios não destinados à exploração são tributados de uma vez ou de forma faseada?",
    opcoes: [
      { texto: "De uma vez, no ano de recebimento.", porque: "Subsídios não destinados à exploração são tributados de forma faseada: 1/5 por ano." },
      { texto: "De forma faseada: 1/5 no ano de recebimento e em cada um dos quatro anos seguintes.", porque: "Subsídios não destinados à exploração (coef. 0,30) são tributados em 1/5 no ano de recebimento e nos quatro exercícios seguintes (Art. 31.º, al. e) CIRS)." },
      { texto: "Metade no ano de recebimento e metade no seguinte.", porque: "A tributação é em 1/5 ao longo de 5 anos, não 50/50 em dois anos." },
      { texto: "Isentos de tributação.", porque: "Subsídios não destinados à exploração não são isentos — são tributados com coeficiente 0,30, de forma faseada." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, al. e) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-90",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um escultor (código 2012 do Art. 151.º) que vende uma escultura original a um colecionador — este rendimento é tratado como prestação de serviço ou venda de bens?",
    opcoes: [
      { texto: "Venda de bens (coef. 0,15).", porque: "A venda de obras de arte por artistas listados no Art. 151.º mantém o enquadramento do Art. 151.º (coef. 0,75), não é tratada como simples venda de bens." },
      { texto: "Prestação de serviços do Art. 151.º (coef. 0,75, ret. 23%).", porque: "Escultores (código 2012) estão na tabela do Art. 151.º. A atividade artística, incluindo a criação e venda de obras originais, mantém o enquadramento de profissão liberal (coef. 0,75, ret. 23%)." },
      { texto: "Propriedade intelectual (coef. 0,95).", porque: "0,95 aplica-se à cedência de direitos de autor, não à venda de obras físicas de arte." },
      { texto: "Depende do valor da escultura.", porque: "O enquadramento fiscal depende do tipo de atividade (Art. 151.º), não do valor da obra." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 2012)",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-91",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Se um prestador de serviços do Art. 151.º (coef. 0,75) não conseguir justificar nenhuma despesa, qual a penalização máxima da regra dos 15%?",
    opcoes: [
      { texto: "O rendimento tributável aumenta em 15% do rendimento bruto.", porque: "Se não justificar nenhuma despesa, a totalidade dos 15% exigidos é adicionada ao rendimento tributável (diferença = 15% - 0% = 15% do rendimento bruto)." },
      { texto: "Perde o regime simplificado.", porque: "A penalização da regra dos 15% é um ajuste ao rendimento tributável, não a perda do regime." },
      { texto: "O coeficiente sobe de 0,75 para 0,90.", porque: "O ajuste é uma adição ao rendimento tributável, não uma alteração do coeficiente." },
      { texto: "Nenhuma penalização — é facultativo.", porque: "A regra dos 15% é obrigatória para os coeficientes 0,75 e 0,35. O incumprimento resulta em aumento do rendimento tributável." },
    ],
    correta: 0,
    legalBasis: "Art. 31.º, n.º 2 CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-92",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um consultor fiscal (código 4012, Art. 151.º) que presta serviços a uma startup americana sediada nos EUA tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "23% aplicar-se-ia se o cliente tivesse sede em Portugal — cliente americano = sem retenção." },
      { texto: "11,5%", porque: "11,5% nem sequer é a taxa correta para Art. 151.º — e para clientes estrangeiros não há retenção." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual — e para clientes estrangeiros não há retenção de qualquer forma." },
      { texto: "0% — sem retenção.", porque: "Quando o cliente não tem sede em Portugal (empresa americana), não há retenção na fonte de IRS (Art. 101.º CIRS)." },
    ],
    correta: 3,
    legalBasis: "Art. 101.º CIRS — retenção aplicável apenas a entidades residentes",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-93",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Qual a diferença prática entre um mediador imobiliário certificado pelo IMPIC (código 1330, Art. 151.º) e um não certificado (código 1519)?",
    opcoes: [
      { texto: "Não há diferença fiscal.", porque: "Há diferença significativa: código 1330 tem coef. 0,75 e ret. 23%; código 1519 tem coef. 0,35 e ret. 11,5%." },
      { texto: "O certificado tem coeficiente 0,75 e retenção 23%; o não certificado tem 0,35 e 11,5%.", porque: "Mediadores certificados (código 1330, Art. 151.º) têm coeficiente 0,75 e retenção 23%. Mediadores não certificados enquadram-se no código 1519 (coef. 0,35, ret. 11,5%). A certificação pelo IMPIC determina o enquadramento fiscal." },
      { texto: "Apenas a retenção difere (23% vs. 11,5%), o coeficiente é o mesmo.", porque: "Tanto o coeficiente como a retenção diferem: certificado = 0,75/23%, não certificado = 0,35/11,5%." },
      { texto: "Apenas o coeficiente difere (0,75 vs. 0,35), a retenção é a mesma.", porque: "Ambos diferem: o certificado tem coef. 0,75 e ret. 23%, enquanto o não certificado tem coef. 0,35 e ret. 11,5%." },
    ],
    correta: 1,
    legalBasis: "Art. 151.º CIRS (código 1330) · Art. 31.º, al. b) e c) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-94",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Atividades agrícolas, silvícolas e pecuárias têm, no regime simplificado, que coeficiente?",
    opcoes: [
      { texto: "0,15", porque: "0,15 aplica-se a vendas de bens e hotelaria — atividades agrícolas têm coeficiente próprio de 0,10." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços — atividades agrícolas têm coeficiente de 0,10." },
      { texto: "0,75", porque: "0,75 aplica-se a profissões do Art. 151.º — atividades agrícolas não constam dessa tabela." },
      { texto: "0,10", porque: "Atividades agrícolas, silvícolas e pecuárias têm coeficiente 0,10 (Art. 31.º CIRS), sem retenção na fonte, e Segurança Social sobre 20%." },
    ],
    correta: 3,
    legalBasis: "Art. 31.º CIRS — atividades agrícolas",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-95",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um desportista profissional (código 1323 do Art. 151.º) tem coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a serviços fora do Art. 151.º — desportistas constam dessa tabela." },
      { texto: "0,75", porque: "Desportistas (código 1323) estão na tabela do Art. 151.º CIRS, com coeficiente 0,75 (Art. 31.º, al. b) CIRS)." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços desportivos." },
      { texto: "0,95", porque: "0,95 aplica-se a propriedade intelectual, não a atividades desportivas." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-96",
    categoria: "atividades",
    dificuldade: 1,
    pergunta: "Um consultor (código 1320 do Art. 151.º) tem retenção na fonte de:",
    opcoes: [
      { texto: "23%", porque: "Consultores (código 1320) estão na tabela do Art. 151.º CIRS, com retenção de 23% (Art. 101.º, al. a) CIRS)." },
      { texto: "11,5%", porque: "11,5% aplica-se a atividades fora do Art. 151.º — consultores com código 1320 constam da tabela." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a serviços de consultoria." },
      { texto: "0% — sem retenção", porque: "Consultores do Art. 151.º estão sujeitos a retenção na fonte de 23%." },
    ],
    correta: 0,
    legalBasis: "Art. 151.º CIRS (código 1320) · Art. 101.º, n.º 1, al. a) CIRS",
    fonte: fonte("portaria151"),
  },
  {
    id: "ativ-97",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um cozinheiro freelance (fora do Art. 151.º) que presta serviços a um restaurante tem retenção de:",
    opcoes: [
      { texto: "23%", porque: "23% aplica-se a profissões do Art. 151.º — cozinheiros freelance estão fora dessa tabela." },
      { texto: "0% — sem retenção", porque: "Cozinheiros freelance que faturam a entidades com contabilidade organizada têm retenção de 11,5%." },
      { texto: "11,5%", porque: "Cozinheiros freelance, fora do Art. 151.º, enquadram-se como 'outras prestações de serviços' (código 1519), com retenção de 11,5% (Art. 101.º, al. c) CIRS)." },
      { texto: "16,5%", porque: "16,5% aplica-se a propriedade intelectual, não a serviços de cozinha." },
    ],
    correta: 2,
    legalBasis: "Art. 101.º, n.º 1, al. c) CIRS",
    fonte: fonte("art101cirs"),
  },
  {
    id: "ativ-98",
    categoria: "atividades",
    dificuldade: 2,
    pergunta: "Um esteticista que se regista com o código 1325 do Art. 151.º tem coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplicar-se-ia se estivesse fora do Art. 151.º — com o código 1325 o coeficiente é 0,75." },
      { texto: "0,75", porque: "Esteticistas registados com o código 1325 do Art. 151.º têm coeficiente 0,75 (Art. 31.º, al. b) CIRS). Se não usassem o Art. 151.º, teriam coeficiente 0,35." },
      { texto: "0,15", porque: "0,15 é para vendas de bens e hotelaria, não para serviços de estética." },
      { texto: "0,50", porque: "0,50 é exclusivo do alojamento local em zona de contenção." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-99",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Cessão de uso de equipamentos (aluguer de maquinaria a terceiros) tem que coeficiente e retenção?",
    opcoes: [
      { texto: "Coeficiente 0,35 e retenção 11,5%.", porque: "A cessão de equipamentos é classificada como propriedade intelectual/industrial (Art. 31.º, al. d) CIRS), com coeficiente 0,95 e retenção 16,5%." },
      { texto: "Coeficiente 0,15 e sem retenção.", porque: "A cessão de uso de equipamentos não é venda de bens — é propriedade intelectual/industrial (coef. 0,95, ret. 16,5%)." },
      { texto: "Coeficiente 0,95 e retenção 16,5%.", porque: "A cessão de uso de equipamentos enquadra-se no Art. 31.º, al. d) CIRS, com coeficiente 0,95 e retenção 16,5% (Art. 101.º, al. b) CIRS)." },
      { texto: "Coeficiente 0,75 e retenção 23%.", porque: "0,75/23% aplica-se a profissões do Art. 151.º — a cessão de equipamentos é rendimento de propriedade intelectual/industrial (0,95/16,5%)." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, al. d) CIRS · Art. 101.º, al. b) CIRS",
    fonte: fonte("art31"),
  },
  {
    id: "ativ-100",
    categoria: "atividades",
    dificuldade: 3,
    pergunta: "Um trabalhador independente com atividade mista: 25 000 EUR em serviços do Art. 151.º (coef. 0,75) e 15 000 EUR em vendas de bens (coef. 0,15). Qual o rendimento tributável total no regime simplificado?",
    opcoes: [
      { texto: "21 000 EUR", porque: "21 000 EUR resultaria de aplicar 0,525 (média) a 40 000 EUR — mas não se faz média de coeficientes." },
      { texto: "30 000 EUR (0,75 x 40 000).", porque: "O coeficiente 0,75 não se aplica a toda a faturação — apenas aos serviços." },
      { texto: "21 000 EUR (0,75 x 25 000 + 0,15 x 15 000 = 18 750 + 2 250).", porque: "Cada tipo de rendimento usa o seu coeficiente: serviços = 25 000 x 0,75 = 18 750 EUR; vendas = 15 000 x 0,15 = 2 250 EUR. Total tributável: 21 000 EUR." },
      { texto: "6 000 EUR (0,15 x 40 000).", porque: "O coeficiente 0,15 não se aplica a toda a faturação — apenas às vendas de bens." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º CIRS — atividades mistas",
    fonte: fonte("art31"),
  },
];
