import { fonte, type QuizPergunta } from "./types";

export const PERGUNTAS_PARTE_2: QuizPergunta[] = [
  {
    id: "rs-1",
    categoria: "regime_simplificado",
    dificuldade: 1,
    pergunta:
      "No regime simplificado de IRS, qual é o coeficiente aplicável a profissões da tabela do Art. 151.º CIRS (ex.: arquitetos, consultores, programadores)?",
    opcoes: [
      { texto: "0,15", porque: "0,15 é o coeficiente para venda de bens, restauração e hotelaria, não para profissões liberais do Art. 151.º." },
      { texto: "0,35", porque: "0,35 é o coeficiente para 'outras prestações de serviços' fora do Art. 151.º." },
      { texto: "0,75", porque: "As profissões da tabela do Art. 151.º CIRS têm coeficiente de 0,75 — apenas 75% do rendimento bruto é considerado rendimento tributável." },
      { texto: "0,95", porque: "0,95 é o coeficiente para direitos de autor e propriedade intelectual, não para profissões liberais do Art. 151.º." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. b) CIRS — serviços do Art. 151.º",
    fonte: fonte("art31"),
  },
  {
    id: "rs-2",
    categoria: "regime_simplificado",
    dificuldade: 2,
    pergunta: "Qual o coeficiente do regime simplificado para 'outras prestações de serviços' não previstas no Art. 151.º (código residual 1519)?",
    opcoes: [
      { texto: "0,75", porque: "0,75 é o coeficiente das profissões da tabela do Art. 151.º — diferente da categoria residual 1519." },
      { texto: "0,35", porque: "Outras prestações de serviços (fora do Art. 151.º) têm coeficiente de 0,35, nos termos do Art. 31.º, n.º 1, al. c) CIRS." },
      { texto: "0,15", porque: "0,15 aplica-se à venda de bens, restauração e hotelaria, não a serviços gerais fora do Art. 151.º." },
      { texto: "1,00", porque: "1,00 só se aplica a serviços prestados a uma sociedade onde o prestador detenha pelo menos 5% do capital (transparência fiscal)." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. c) CIRS — outras prestações de serviços",
    fonte: fonte("art31"),
  },
  {
    id: "rs-3",
    categoria: "regime_simplificado",
    dificuldade: 1,
    pergunta: "Qual o coeficiente do regime simplificado aplicável à venda de mercadorias, restauração e hotelaria?",
    opcoes: [
      { texto: "0,10", porque: "0,10 aplica-se a subsídios destinados à exploração e a atividades agrícolas — não diretamente à venda de bens em geral." },
      { texto: "0,15", porque: "Vendas de bens, restauração e hotelaria têm coeficiente de 0,15, refletindo margens brutas tipicamente mais baixas (Art. 31.º, n.º 1, al. a) CIRS)." },
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços, e não à venda de mercadorias." },
      { texto: "0,75", porque: "0,75 aplica-se às profissões liberais do Art. 151.º, não à venda de bens." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 1, al. a) CIRS — vendas de bens, restauração e hotelaria",
    fonte: fonte("art31"),
  },
  {
    id: "rs-4",
    categoria: "regime_simplificado",
    dificuldade: 2,
    pergunta: "Os rendimentos de direitos de autor e de propriedade intelectual/industrial têm, no regime simplificado, coeficiente de:",
    opcoes: [
      { texto: "0,35", porque: "0,35 aplica-se a outras prestações de serviços, não a direitos de autor." },
      { texto: "0,75", porque: "0,75 aplica-se às profissões do Art. 151.º, não a direitos de autor." },
      { texto: "0,95", porque: "Direitos de autor e propriedade intelectual/industrial têm coeficiente de 0,95 (Art. 31.º, n.º 1, al. d) CIRS)." },
      { texto: "1,00", porque: "1,00 só se aplica ao regime de transparência fiscal (serviços a sociedade onde se detém ≥5%), não a direitos de autor em geral." },
    ],
    correta: 2,
    legalBasis: "Art. 31.º, n.º 1, al. d) CIRS — propriedade intelectual/industrial",
    fonte: fonte("art31"),
  },
  {
    id: "rs-5",
    categoria: "regime_simplificado",
    dificuldade: 2,
    pergunta: "No 1.º ano de atividade, o coeficiente do regime simplificado sofre uma redução de:",
    opcoes: [
      { texto: "25%", porque: "25% é a redução aplicável ao 2.º ano de atividade, não ao 1.º." },
      { texto: "50%", porque: "No 1.º ano de atividade, o coeficiente é reduzido em 50% (Art. 31.º, n.º 10 CIRS); no 2.º ano, a redução é de 25%." },
      { texto: "75%", porque: "75% não corresponde a nenhuma das reduções previstas — são 50% (1.º ano) e 25% (2.º ano)." },
      { texto: "Não há redução — aplica-se sempre o coeficiente integral.", porque: "Existe sim uma redução nos dois primeiros anos de atividade: 50% no 1.º ano e 25% no 2.º ano." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º, n.º 10 CIRS — redução de 50% (1.º ano) e 25% (2.º ano)",
    fonte: fonte("art31"),
  },
  {
    id: "rs-6",
    categoria: "regime_simplificado",
    dificuldade: 3,
    pergunta: "A 'regra dos 15%' do regime simplificado (para coeficientes 0,75 e 0,35) diz que:",
    opcoes: [
      { texto: "Pelo menos 15% do rendimento bruto deve ser pago em IVA.", porque: "Esta regra não tem relação com IVA — é sobre despesas dedutíveis consideradas para efeitos de IRS." },
      { texto: "Pelo menos 15% do rendimento bruto deve estar justificado com despesas, ou a diferença é acrescida ao rendimento tributável.", porque: "A parte de 15% do rendimento bruto não justificada com despesas dedutíveis é acrescida ao rendimento tributável (Art. 31.º CIRS)." },
      { texto: "A retenção na fonte aumenta 15% se não houver despesas registadas.", porque: "A retenção na fonte (23%/11,5%/16,5%) não varia com despesas — é fixa por tipo de atividade." },
      { texto: "15% do rendimento fica automaticamente isento de Segurança Social.", porque: "A regra dos 15% aplica-se ao cálculo do rendimento tributável de IRS, não tem qualquer efeito na Segurança Social." },
    ],
    correta: 1,
    legalBasis: "Art. 31.º CIRS — 15% do rendimento bruto a justificar com despesas",
    fonte: fonte("occRegimeSimplificado"),
  },
  {
    id: "rs-7",
    categoria: "regime_simplificado",
    dificuldade: 2,
    pergunta: "Qual é o limite de rendimento bruto anual para se poder estar no regime simplificado de IRS?",
    opcoes: [
      { texto: "100.000 €", porque: "100.000 € não é o limite atual do regime simplificado — o valor correto é 200.000 €." },
      { texto: "150.000 €", porque: "150.000 € não corresponde ao limite legal — o valor correto é 200.000 €." },
      { texto: "200.000 €", porque: "O Art. 28.º CIRS fixa em 200.000 € o limite de rendimento bruto anual para permanecer no regime simplificado." },
      { texto: "Não há limite — aplica-se a qualquer volume de faturação.", porque: "Existe sim um limite (200.000 €); acima desse valor passa a aplicar-se o regime de contabilidade organizada." },
    ],
    correta: 2,
    legalBasis: "Art. 28.º CIRS — limite de rendimento bruto do regime simplificado",
    fonte: fonte("art68cirs"),
  },
  {
    id: "jov-1",
    categoria: "irs_jovem",
    dificuldade: 1,
    pergunta: "Até que idade (no último dia do ano em causa) se pode beneficiar do regime de IRS Jovem?",
    opcoes: [
      { texto: "28 anos", porque: "28 anos não é o limite — o regime de IRS Jovem aplica-se até aos 35 anos." },
      { texto: "30 anos", porque: "30 anos não é o limite atual — o regime aplica-se até aos 35 anos." },
      { texto: "35 anos", porque: "O regime de IRS Jovem aplica-se a quem tenha até 35 anos no último dia do ano a que respeitam os rendimentos." },
      { texto: "40 anos", porque: "40 anos excede o limite previsto — o regime aplica-se até aos 35 anos." },
    ],
    correta: 2,
    legalBasis: "Regime IRS Jovem — até 35 anos no último dia do ano",
    fonte: fonte("art12bCirs"),
  },
  {
    id: "jov-2",
    categoria: "irs_jovem",
    dificuldade: 2,
    pergunta: "No 1.º ano de obtenção de rendimentos no regime de IRS Jovem, qual a percentagem de isenção?",
    opcoes: [
      { texto: "50%", porque: "50% aplica-se aos anos 5 a 7 do regime, não ao 1.º ano." },
      { texto: "75%", porque: "75% aplica-se aos anos 2 a 4 do regime, não ao 1.º ano." },
      { texto: "100%", porque: "No 1.º ano de obtenção de rendimentos, a isenção do IRS Jovem é de 100% (dentro do teto de 55 × IAS)." },
      { texto: "25%", porque: "25% aplica-se aos anos 8 a 10 do regime, não ao 1.º ano." },
    ],
    correta: 2,
    legalBasis: "Regime IRS Jovem — 100% (1.º ano)",
    fonte: fonte("art12bCirs"),
  },
  {
    id: "jov-3",
    categoria: "irs_jovem",
    dificuldade: 2,
    pergunta: "Do 2.º ao 4.º ano de obtenção de rendimentos no IRS Jovem, qual a percentagem de isenção aplicável?",
    opcoes: [
      { texto: "100%", porque: "100% aplica-se apenas ao 1.º ano do regime." },
      { texto: "75%", porque: "Do 2.º ao 4.º ano, a isenção do IRS Jovem é de 75%." },
      { texto: "50%", porque: "50% aplica-se aos anos 5 a 7 do regime, não aos anos 2 a 4." },
      { texto: "25%", porque: "25% aplica-se aos anos 8 a 10 do regime, não aos anos 2 a 4." },
    ],
    correta: 1,
    legalBasis: "Regime IRS Jovem — 75% (2.º ao 4.º ano)",
    fonte: fonte("art12bCirs"),
  },
  {
    id: "jov-4",
    categoria: "irs_jovem",
    dificuldade: 3,
    pergunta: "O teto anual de rendimento isento no regime de IRS Jovem corresponde a quantas vezes o valor do IAS?",
    opcoes: [
      { texto: "40 × IAS", porque: "40× não é o multiplicador correto — o teto do IRS Jovem é 55 × IAS." },
      { texto: "55 × IAS", porque: "O teto anual de rendimento isento no IRS Jovem corresponde a 55 vezes o IAS." },
      { texto: "60 × IAS", porque: "60× não é o multiplicador correto — o teto do IRS Jovem é 55 × IAS." },
      { texto: "12 × IAS", porque: "12 × IAS corresponde ao teto mensal de rendimento relevante para a Segurança Social, não ao teto do IRS Jovem." },
    ],
    correta: 1,
    legalBasis: "Teto anual de isenção = 55 × IAS",
    fonte: fonte("art12bCirs"),
  },
  {
    id: "jov-5",
    categoria: "irs_jovem",
    dificuldade: 2,
    pergunta: "Nos últimos anos do regime de IRS Jovem (do 8.º ao 10.º ano de obtenção de rendimentos), qual a percentagem de isenção?",
    opcoes: [
      { texto: "25%", porque: "Do 8.º ao 10.º ano, a isenção do IRS Jovem é de 25% — a última fase decrescente do regime." },
      { texto: "50%", porque: "50% aplica-se aos anos 5 a 7 do regime, não aos anos 8 a 10." },
      { texto: "75%", porque: "75% aplica-se aos anos 2 a 4 do regime, não aos anos finais." },
      { texto: "0% — nos últimos anos já não há qualquer isenção.", porque: "Ainda existe isenção nos anos 8 a 10, embora reduzida para 25%." },
    ],
    correta: 0,
    legalBasis: "Regime IRS Jovem — 25% (8.º ao 10.º ano)",
    fonte: fonte("art12bCirs"),
  },
  {
    id: "esc-1",
    categoria: "escaloes_deducoes",
    dificuldade: 2,
    pergunta: "Qual é a taxa marginal do 1.º escalão de IRS em 2026 (rendimento coletável até 8.342 €)?",
    opcoes: [
      { texto: "12,5%", porque: "O 1.º escalão de IRS 2026 (até 8.342 €) tem taxa marginal de 12,5% (Art. 68.º CIRS)." },
      { texto: "14,5%", porque: "14,5% não corresponde a nenhum escalão de IRS 2026 — o 1.º escalão é 12,5%." },
      { texto: "15,7%", porque: "15,7% corresponde ao 2.º escalão (até 12.587 €), não ao 1.º." },
      { texto: "21,2%", porque: "21,2% corresponde ao 3.º escalão (até 17.838 €), não ao 1.º." },
    ],
    correta: 0,
    legalBasis: "Art. 68.º CIRS — escalões 2026, 1.º escalão",
    fonte: fonte("art68cirs"),
  },
  {
    id: "esc-2",
    categoria: "escaloes_deducoes",
    dificuldade: 2,
    pergunta: "Qual é a taxa marginal do último escalão de IRS em 2026 (rendimento coletável acima de 86.634 €)?",
    opcoes: [
      { texto: "43,1%", porque: "43,1% corresponde ao 7.º escalão (até 46.566 €), não ao último." },
      { texto: "44,6%", porque: "44,6% corresponde ao 8.º escalão (até 86.634 €), não ao último (9.º)." },
      { texto: "46,0%", porque: "46,0% não corresponde a nenhum escalão de 2026 — o último escalão tem taxa de 48%." },
      { texto: "48,0%", porque: "O 9.º e último escalão de IRS 2026 (acima de 86.634 €) tem taxa marginal de 48%." },
    ],
    correta: 3,
    legalBasis: "Art. 68.º CIRS — escalões 2026, último escalão",
    fonte: fonte("art68cirs"),
  },
  {
    id: "esc-3",
    categoria: "escaloes_deducoes",
    dificuldade: 3,
    pergunta: "Qual é o valor da dedução específica da categoria B em 2026, calculada como máx(4.104 €; 8,54 × IAS)?",
    opcoes: [
      { texto: "4.104,00 €", porque: "4.104 € é o piso fixo da fórmula, mas 8,54 × IAS (537,13 €) é superior, pelo que prevalece esse valor mais alto." },
      { texto: "4.587,09 €", porque: "8,54 × 537,13 € = 4.587,09 €, superior ao piso de 4.104 €, sendo este o valor da dedução específica em 2026." },
      { texto: "5.000,00 €", porque: "5.000 € não corresponde ao cálculo máx(4.104 €; 8,54 × IAS), que resulta em 4.587,09 €." },
      { texto: "6.445,56 €", porque: "6.445,56 € corresponde a 12 × IAS (teto mensal da SS), não à dedução específica da categoria B." },
    ],
    correta: 1,
    legalBasis: "Art. 25.º / 31.º CIRS — máx(4.104 €; 8,54 × IAS)",
    fonte: fonte("occRegimeSimplificado"),
  },
  {
    id: "esc-4",
    categoria: "escaloes_deducoes",
    dificuldade: 2,
    pergunta: "Qual é o valor do mínimo de existência em 2026 (RMMG 920 € × 14)?",
    opcoes: [
      { texto: "11.000 €", porque: "11.000 € não corresponde ao cálculo 920 € × 14 = 12.880 €." },
      { texto: "12.880 €", porque: "920 € × 14 = 12.880 € — o rendimento protegido de IRS pelo mínimo de existência em 2026 (Art. 70.º CIRS)." },
      { texto: "13.500 €", porque: "13.500 € não corresponde ao cálculo correto (920 € × 14 = 12.880 €)." },
      { texto: "15.000 €", porque: "15.000 € é o limiar de isenção de IVA / dispensa de retenção — não o mínimo de existência de IRS." },
    ],
    correta: 1,
    legalBasis: "Art. 70.º CIRS — mínimo de existência 2026 (RMMG 920 € × 14)",
    fonte: fonte("art70cirs"),
  },
  {
    id: "esc-5",
    categoria: "escaloes_deducoes",
    dificuldade: 2,
    pergunta: "Qual é o valor da dedução à coleta de IRS por cada dependente com mais de 3 anos?",
    opcoes: [
      { texto: "400 €", porque: "400 € não corresponde ao valor atual — a dedução por dependente (>3 anos) é de 600 €." },
      { texto: "600 €", porque: "A dedução à coleta por dependente com mais de 3 anos é de 600 € (Art. 78.º-A CIRS)." },
      { texto: "726 €", porque: "726 € é o valor da dedução por dependente até 3 anos (bebé), não para dependentes com mais de 3 anos." },
      { texto: "900 €", porque: "900 € corresponde à dedução majorada a partir do 2.º dependente (até 6 anos), não ao valor base." },
    ],
    correta: 1,
    legalBasis: "Art. 78.º-A CIRS — por dependente com mais de 3 anos",
    fonte: fonte("art78aCirs"),
  },
  {
    id: "esc-6",
    categoria: "escaloes_deducoes",
    dificuldade: 2,
    pergunta: "Qual é o valor da dedução à coleta de IRS por dependente até aos 3 anos de idade?",
    opcoes: [
      { texto: "600 €", porque: "600 € é o valor base para dependentes com mais de 3 anos — para até 3 anos o valor é superior (726 €)." },
      { texto: "726 €", porque: "Por dependente até 3 anos, a dedução à coleta é de 726 € (Art. 78.º-A CIRS), superior ao valor base de 600 €." },
      { texto: "800 €", porque: "800 € não corresponde a esta dedução — o valor correto é 726 €." },
      { texto: "900 €", porque: "900 € é a dedução majorada a partir do 2.º dependente até 6 anos, e não o valor para dependentes até 3 anos em geral." },
    ],
    correta: 1,
    legalBasis: "Art. 78.º-A CIRS — por dependente até 3 anos",
    fonte: fonte("art78aCirs"),
  },
  {
    id: "esc-7",
    categoria: "escaloes_deducoes",
    dificuldade: 1,
    pergunta: "A dedução à coleta de despesas de saúde corresponde a 15% da despesa, até que limite?",
    opcoes: [
      { texto: "800 €", porque: "800 € corresponde ao limite da dedução de despesas de educação, não de saúde." },
      { texto: "900 €", porque: "900 € corresponde ao limite da dedução de rendas de habitação permanente em 2026, não de saúde." },
      { texto: "1.000 €", porque: "A dedução de despesas de saúde é de 15%, com um limite de 1.000 € (Art. 78.º-C CIRS)." },
      { texto: "1.200 €", porque: "1.200 € não corresponde ao limite legal — o limite da dedução de saúde é 1.000 €." },
    ],
    correta: 2,
    legalBasis: "Art. 78.º-C CIRS — saúde: 15% até 1.000 €",
    fonte: fonte("art78aCirs"),
  },
  {
    id: "esc-8",
    categoria: "escaloes_deducoes",
    dificuldade: 1,
    pergunta: "A dedução à coleta de despesas de educação corresponde a 30% da despesa, até que limite?",
    opcoes: [
      { texto: "600 €", porque: "600 € não corresponde ao limite legal da dedução de educação — o valor correto é 800 €." },
      { texto: "700 €", porque: "700 € era o limite da dedução de rendas em 2025 (atualizado para 900 € em 2026) — não corresponde à dedução de educação." },
      { texto: "800 €", porque: "A dedução de despesas de educação é de 30%, com um limite de 800 € (Art. 78.º-D CIRS)." },
      { texto: "1.000 €", porque: "1.000 € corresponde ao limite da dedução de saúde, não de educação." },
    ],
    correta: 2,
    legalBasis: "Art. 78.º-D CIRS — educação: 30% até 800 €",
    fonte: fonte("art78aCirs"),
  },
  {
    id: "esc-9",
    categoria: "escaloes_deducoes",
    dificuldade: 3,
    pergunta: "Em 2026, a dedução à coleta de rendas de habitação permanente é de 15%, até que limite (Lei 36/2024)?",
    opcoes: [
      { texto: "700 €", porque: "700 € era o limite aplicável em 2025 — em 2026 o limite subiu para 900 €." },
      { texto: "900 €", porque: "Pela Lei 36/2024, o limite da dedução de rendas para 2026 é de 900 € (a subir para 1.000 € em 2027)." },
      { texto: "1.000 €", porque: "1.000 € é o limite previsto a partir de 2027, não para 2026 (que é 900 €)." },
      { texto: "1.200 €", porque: "1.200 € não corresponde a nenhum dos limites previstos pela Lei 36/2024 (700 € / 900 € / 1.000 €)." },
    ],
    correta: 1,
    legalBasis: "Art. 78.º-E CIRS — rendas de habitação permanente: 15% até 900 € (Lei 36/2024, rendimentos de 2026)",
    fonte: fonte("art78aCirs"),
  },
];
