import { fonte, type QuizPergunta } from "./types";

export const PERGUNTAS_CATF: QuizPergunta[] = [
  {
    id: "catf-5",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Os rendimentos prediais (rendas de imóveis arrendados) enquadram-se em que categoria de IRS?",
    opcoes: [
      { texto: "Categoria A", porque: "A Categoria A abrange rendimentos do trabalho dependente (salários), não rendas de imóveis." },
      { texto: "Categoria B", porque: "A Categoria B abrange rendimentos empresariais e profissionais, não rendas de arrendamento tradicional." },
      { texto: "Categoria F", porque: "Os rendimentos prediais (rendas de imóveis arrendados) enquadram-se na Categoria F do IRS (Art. 8.º CIRS)." },
      { texto: "Categoria G", porque: "A Categoria G abrange incrementos patrimoniais (mais-valias), não rendimentos de arrendamento." },
    ],
    correta: 2,
    legalBasis: "Art. 8.º CIRS — Categoria F (rendimentos prediais)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-6",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "O senhorio que arrenda um apartamento para habitação paga IVA sobre as rendas recebidas?",
    opcoes: [
      { texto: "Sim, à taxa normal de 23%.", porque: "O arrendamento de imóveis para habitação está isento de IVA (Art. 9.º, n.º 29 CIVA)." },
      { texto: "Sim, à taxa reduzida de 6%.", porque: "O arrendamento de imóveis para habitação está isento de IVA, não se aplicando nenhuma taxa." },
      { texto: "Não, as rendas de arrendamento estão isentas de IVA.", porque: "O arrendamento de imóveis está isento de IVA nos termos do Art. 9.º, n.º 29 do CIVA." },
      { texto: "Depende do valor da renda mensal.", porque: "A isenção de IVA no arrendamento não depende do valor da renda — é uma isenção geral." },
    ],
    correta: 2,
    legalBasis: "Art. 9.º, n.º 29 CIVA — isenção de IVA no arrendamento",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-7",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Um senhorio que obtém rendimentos exclusivamente de arrendamento (Categoria F) tem de pagar contribuições para a Seguranca Social sobre essas rendas?",
    opcoes: [
      { texto: "Sim, a uma taxa de 21,4%.", porque: "Os rendimentos da Categoria F não estao sujeitos a contribuições para a Seguranca Social — esta taxa aplica-se a trabalhadores independentes (Categoria B)." },
      { texto: "Não, os rendimentos prediais não estao sujeitos a Seguranca Social.", porque: "Os rendimentos prediais (Categoria F) não estao sujeitos a contribuições para a Seguranca Social, ao contrário dos rendimentos profissionais (Categoria B)." },
      { texto: "Sim, mas apenas acima de 12 500 EUR anuais.", porque: "Não existe limiar a partir do qual incida Seguranca Social sobre rendimentos da Categoria F — estas rendas estao totalmente isentas." },
      { texto: "Sim, a uma taxa reduzida de 10%.", porque: "Não existe taxa de Seguranca Social sobre rendimentos prediais, independentemente do valor." },
    ],
    correta: 1,
    legalBasis: "Código Contributivo — rendimentos prediais fora do âmbito da Segurança Social",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-8",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Em que anexo da declaração Modelo 3 de IRS se declaram os rendimentos prediais?",
    opcoes: [
      { texto: "Anexo B", porque: "O Anexo B destina-se aos rendimentos empresariais e profissionais (Categoria B), não aos prediais." },
      { texto: "Anexo F", porque: "Os rendimentos prediais (Categoria F) são declarados no Anexo F da declaração Modelo 3 de IRS." },
      { texto: "Anexo E", porque: "O Anexo E destina-se aos rendimentos de capitais (Categoria E), não aos prediais." },
      { texto: "Anexo G", porque: "O Anexo G destina-se a mais-valias e outros incrementos patrimoniais (Categoria G)." },
    ],
    correta: 1,
    legalBasis: "Modelo 3 — Anexo F para rendimentos prediais",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-9",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "A taxa autónoma de IRS sobre rendas de arrendamento habitacional é de:",
    opcoes: [
      { texto: "25%", porque: "A taxa autónoma sobre rendimentos de arrendamento habitacional é de 25% (Art. 72.º, n.º 1 CIRS)." },
      { texto: "28%", porque: "28% é a taxa para arrendamento NÃO habitacional (comércio, escritórios). Para habitação, a taxa é 25%." },
      { texto: "20%", porque: "20% não corresponde a nenhuma taxa autónoma da Categoria F prevista no Art. 72.º CIRS." },
      { texto: "15%", porque: "15% é a taxa efetiva após redução por contrato de 5 a 10 anos, não a taxa base." },
    ],
    correta: 0,
    legalBasis: "Art. 72.º, n.º 1 CIRS — taxa especial dos rendimentos prediais (habitação)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-10",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "A taxa autónoma de IRS sobre rendas de arrendamento não habitacional (escritórios, lojas) é de:",
    opcoes: [
      { texto: "23%", porque: "23% é a taxa normal de IVA, não se aplica à tributação autónoma de rendas." },
      { texto: "25%", porque: "25% é a taxa para arrendamento habitacional. Para arrendamento não habitacional, a taxa é 28%." },
      { texto: "30%", porque: "30% não corresponde à taxa em vigor para arrendamento não habitacional." },
      { texto: "28%", porque: "A taxa autónoma para arrendamento não habitacional (lojas, escritórios) é de 28% (Art. 72.º CIRS)." },
    ],
    correta: 3,
    legalBasis: "Art. 72.º CIRS — rendimentos prediais de arrendamento não habitacional",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-11",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Qual das seguintes despesas é dedutível aos rendimentos prediais da Categoria F?",
    opcoes: [
      { texto: "Mobília adquirida para o imóvel arrendado.", porque: "As despesas com mobiliário não são dedutíveis na Categoria F (Art. 41.º CIRS)." },
      { texto: "Juros do empréstimo bancário do imóvel.", porque: "Os juros de empréstimo hipotecário não são dedutíveis aos rendimentos prediais da Categoria F." },
      { texto: "Imposto Municipal sobre Imóveis (IMI).", porque: "O IMI é uma despesa dedutível aos rendimentos prediais (Art. 41.º CIRS)." },
      { texto: "Obras de ampliação que aumentam o valor do imóvel.", porque: "Obras que aumentem o valor do imóvel (melhoramentos) não são dedutíveis — apenas conservação e manutenção." },
    ],
    correta: 2,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis aos rendimentos prediais",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-12",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "O que acontece se o senhorio não declarar os rendimentos prediais no IRS?",
    opcoes: [
      { texto: "Não tem consequências se o valor for inferior a 10 000 EUR.", porque: "Todos os rendimentos prediais devem ser declarados, independentemente do valor — a omissão constitui infração fiscal." },
      { texto: "Pode ser alvo de coima e liquidação adicional de imposto pela AT.", porque: "A não declaração de rendimentos prediais constitui infração fiscal, podendo originar coimas e liquidação adicional de IRS." },
      { texto: "Apenas tem de pagar uma multa simbólica.", porque: "As consequências podem ir muito além de uma multa simbólica, incluindo coimas significativas e juros compensatórios." },
      { texto: "Nada, porque as rendas são automaticamente comunicadas.", porque: "Mesmo havendo comunicação automática de contratos, o senhorio é obrigado a declarar os rendimentos no Modelo 3, Anexo F." },
    ],
    correta: 1,
    legalBasis: "Art. 57.º RGIT — infração por omissão de rendimentos",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-13",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Quem é responsável por entregar o recibo de renda eletrónico no Portal das Finanças?",
    opcoes: [
      { texto: "O inquilino.", porque: "A emissão do recibo de renda eletrónico é obrigação do senhorio, não do inquilino." },
      { texto: "O senhorio.", porque: "O senhorio é obrigado a emitir o recibo de renda eletrónico através do Portal das Finanças (e-fatura)." },
      { texto: "O contabilista certificado.", porque: "O senhorio pode ter apoio de um contabilista, mas a obrigação é do próprio senhorio." },
      { texto: "Ambos, senhorio e inquilino.", porque: "A obrigação de emitir o recibo de renda eletrónico é exclusivamente do senhorio." },
    ],
    correta: 1,
    legalBasis: "Portaria 98-A/2015 — recibo de renda eletrónico",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-14",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Para efeitos fiscais, o alojamento local (Airbnb, booking) enquadra-se na Categoria F?",
    opcoes: [
      { texto: "Sim, porque envolve arrendamento de imóveis.", porque: "O alojamento local não é considerado arrendamento — é uma atividade empresarial enquadrada na Categoria B." },
      { texto: "Não, enquadra-se na Categoria B (rendimentos empresariais).", porque: "O alojamento local é uma atividade de prestação de serviços de alojamento, tributada como rendimento empresarial na Categoria B." },
      { texto: "Depende da duração da estadia.", porque: "O alojamento local enquadra-se sempre na Categoria B, independentemente da duração da estadia." },
      { texto: "Sim, mas apenas se for em propriedade própria.", porque: "Mesmo em propriedade própria, o alojamento local é tributado na Categoria B, não na F." },
    ],
    correta: 1,
    legalBasis: "Art. 28.º CIRS — alojamento local como rendimento empresarial (Categoria B)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-15",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Os rendimentos prediais da Categoria F estão sujeitos a retenção na fonte?",
    opcoes: [
      { texto: "Sim, sempre que o inquilino seja uma empresa.", porque: "As rendas da Categoria F não estão sujeitas a retenção na fonte, mesmo quando pagas por empresas." },
      { texto: "Sim, a uma taxa de 25%.", porque: "Os rendimentos prediais (Categoria F) não estão sujeitos a retenção na fonte — o imposto é pago na liquidação anual ou por tributação autónoma." },
      { texto: "Não, não estão sujeitos a retenção na fonte.", porque: "Os rendimentos prediais da Categoria F não estão sujeitos a retenção na fonte (Art. 101.º CIRS aplica-se apenas à Categoria B)." },
      { texto: "Depende do valor da renda mensal.", porque: "A não sujeição a retenção na fonte dos rendimentos prediais não depende do valor da renda." },
    ],
    correta: 2,
    legalBasis: "Art. 101.º CIRS — retenção na fonte (não se aplica à Categoria F)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-16",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "É possível optar pelo englobamento dos rendimentos prediais na declaração de IRS?",
    opcoes: [
      { texto: "Não, os rendimentos prediais são sempre tributados por taxa autónoma.", porque: "O contribuinte pode optar pelo englobamento dos rendimentos prediais, sujeitando-os às taxas progressivas gerais." },
      { texto: "Sim, o contribuinte pode optar pelo englobamento dos rendimentos prediais.", porque: "O contribuinte pode optar pelo englobamento (Art. 72.º CIRS), sujeitando os rendimentos às taxas gerais progressivas em vez da taxa autónoma." },
      { texto: "O englobamento é automático se as rendas excederem 50 000 EUR.", porque: "O englobamento é sempre uma opção do contribuinte — não é obrigatório nem automático, independentemente do valor." },
      { texto: "Apenas para rendimentos acima de 10 000 EUR.", porque: "A opção de englobamento não depende de qualquer limiar de rendimentos." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — opção pelo englobamento dos rendimentos prediais",
    fonte: fonte("art72"),
  },
  {
    id: "catf-17",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Se um senhorio arrendar uma loja comercial, qual a taxa autónoma que incide sobre as rendas?",
    opcoes: [
      { texto: "25%", porque: "25% aplica-se ao arrendamento habitacional. Uma loja comercial é arrendamento não habitacional, tributado a 28%." },
      { texto: "28%", porque: "O arrendamento de espaços comerciais (não habitacionais) é tributado à taxa autónoma de 28% (Art. 72.º CIRS)." },
      { texto: "21%", porque: "21% não é uma taxa prevista no Art. 72.º CIRS para rendimentos prediais." },
      { texto: "35%", porque: "35% não corresponde a nenhuma taxa da Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxa autónoma sobre arrendamento não habitacional",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-18",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Os encargos de condomínio pagos pelo senhorio são dedutíveis aos rendimentos prediais?",
    opcoes: [
      { texto: "Não, apenas o IMI é dedutível.", porque: "Os encargos de condomínio suportados pelo senhorio são dedutíveis aos rendimentos prediais, tal como o IMI (Art. 41.º CIRS)." },
      { texto: "Sim, são despesas dedutíveis (Art. 41.º CIRS).", porque: "Os encargos de condomínio efetivamente suportados pelo senhorio são dedutíveis aos rendimentos prediais (Art. 41.º CIRS)." },
      { texto: "Apenas se o imóvel for para habitação.", porque: "Os encargos de condomínio são dedutíveis independentemente de o imóvel ser para habitação ou comércio." },
      { texto: "Só se ultrapassarem 500 EUR anuais.", porque: "Não existe limiar mínimo para a dedução dos encargos de condomínio aos rendimentos prediais." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (encargos de condomínio)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-19",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Um senhorio que arrende dois apartamentos diferentes declara cada um separadamente no Anexo F?",
    opcoes: [
      { texto: "Não, declara o valor total num único campo.", porque: "No Anexo F, cada imóvel arrendado deve ser identificado individualmente (com NIF do inquilino e dados do imóvel)." },
      { texto: "Sim, cada imóvel é declarado separadamente no Anexo F.", porque: "No Anexo F, o senhorio deve discriminar os rendimentos por cada imóvel arrendado, identificando-os individualmente." },
      { texto: "Apenas se os imóveis forem em concelhos diferentes.", porque: "Todos os imóveis arrendados devem ser declarados individualmente no Anexo F, independentemente da localização." },
      { texto: "Sim, mas apenas se tiver inquilinos diferentes.", porque: "A declaração individual por imóvel no Anexo F é sempre obrigatória, independentemente dos inquilinos." },
    ],
    correta: 1,
    legalBasis: "Instruções do Anexo F — Modelo 3 de IRS",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-20",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "O Imposto do Selo pago sobre o contrato de arrendamento é dedutível na Categoria F?",
    opcoes: [
      { texto: "Sim, é uma despesa dedutível.", porque: "O Imposto do Selo suportado pelo senhorio no contrato de arrendamento é dedutível aos rendimentos prediais (Art. 41.º CIRS)." },
      { texto: "Não, o Imposto do Selo nunca é dedutível.", porque: "O Imposto do Selo sobre o contrato de arrendamento é efetivamente dedutível na Categoria F." },
      { texto: "Apenas se o contrato for superior a 5 anos.", porque: "A dedução do Imposto do Selo não depende da duração do contrato." },
      { texto: "Apenas para contratos não habitacionais.", porque: "O Imposto do Selo é dedutível tanto em contratos habitacionais como não habitacionais." },
    ],
    correta: 0,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (Imposto do Selo)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-21",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "O seguro obrigatório do imóvel arrendado, suportado pelo senhorio, é dedutível na Categoria F?",
    opcoes: [
      { texto: "Não, os seguros não são despesas dedutíveis.", porque: "O seguro obrigatório do imóvel, quando suportado pelo senhorio, é dedutível aos rendimentos prediais (Art. 41.º CIRS)." },
      { texto: "Sim, se for seguro obrigatório.", porque: "Os prémios de seguro obrigatório (ex.: seguro de incêndio) suportados pelo senhorio são dedutíveis na Categoria F." },
      { texto: "Apenas seguros multirriscos.", porque: "É o seguro obrigatório (ex.: incêndio) que é expressamente dedutível, não todos os seguros." },
      { texto: "Sim, qualquer tipo de seguro.", porque: "Apenas os seguros obrigatórios (ex.: incêndio) são dedutíveis, não todos os seguros (Art. 41.º CIRS)." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (seguros obrigatórios)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-22",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Um senhorio pode ter rendimentos da Categoria B (trabalhador independente) e da Categoria F (rendas) em simultâneo?",
    opcoes: [
      { texto: "Não, tem de optar por uma categoria.", porque: "As categorias de IRS não são exclusivas — um contribuinte pode ter rendimentos de múltiplas categorias em simultâneo." },
      { texto: "Sim, as categorias são independentes.", porque: "Um contribuinte pode acumular rendimentos de diferentes categorias (ex.: B e F), declarando cada uma no respetivo anexo." },
      { texto: "Sim, mas os rendimentos são somados numa única categoria.", porque: "Os rendimentos de categorias diferentes são tributados separadamente segundo as regras de cada categoria." },
      { texto: "Apenas se abrir atividade como senhorio.", porque: "Não é necessário abrir atividade para receber rendimentos da Categoria F — basta declarar no Anexo F." },
    ],
    correta: 1,
    legalBasis: "Art. 1.º CIRS — incidência por categorias de rendimento",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-23",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Qual é o rendimento tributável da Categoria F?",
    opcoes: [
      { texto: "O valor bruto das rendas recebidas.", porque: "O rendimento tributável é o valor bruto das rendas MENOS as despesas dedutíveis (Art. 41.º CIRS), não o bruto total." },
      { texto: "As rendas brutas menos as despesas dedutíveis.", porque: "O rendimento líquido da Categoria F é o valor das rendas recebidas subtraído das despesas dedutíveis previstas no Art. 41.º CIRS." },
      { texto: "75% das rendas brutas.", porque: "Não existe coeficiente de 75% na Categoria F — esse mecanismo aplica-se ao regime simplificado da Categoria B." },
      { texto: "As rendas brutas menos 50% a título de despesas.", porque: "Na Categoria F não existe uma dedução forfetária de 50% — deduzem-se as despesas efetivamente suportadas." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — determinação do rendimento líquido da Categoria F",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-24",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Um imóvel rústico (terreno agrícola) arrendado gera rendimentos de que categoria?",
    opcoes: [
      { texto: "Categoria A", porque: "A Categoria A é para rendimentos do trabalho dependente, não para arrendamento de imóveis." },
      { texto: "Categoria B", porque: "O arrendamento de imóveis rústicos enquadra-se na Categoria F, não na B (salvo se integrado em atividade agrícola do proprietário)." },
      { texto: "Categoria F", porque: "O arrendamento de imóveis rústicos (terrenos) gera rendimentos da Categoria F (rendimentos prediais), tal como os urbanos." },
      { texto: "Categoria G", porque: "A Categoria G abrange mais-valias, não rendimentos de arrendamento de imóveis." },
    ],
    correta: 2,
    legalBasis: "Art. 8.º CIRS — rendimentos prediais (imóveis rústicos e urbanos)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-25",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um contrato de arrendamento habitacional permanente de 7 anos, comunicado à AT, beneficia de que redução na taxa autónoma?",
    opcoes: [
      { texto: "Nenhuma redução.", porque: "Os contratos entre 5 e 10 anos beneficiam de uma redução de 10 pontos percentuais." },
      { texto: "10 pontos percentuais.", porque: "Contratos de arrendamento habitacional permanente de 5 a 10 anos, comunicados à AT, beneficiam de uma redução de 10 p.p. (taxa efetiva de 15%)." },
      { texto: "15 pontos percentuais.", porque: "A redução de 15 p.p. aplica-se a contratos de 10 a 20 anos, não de 5 a 10 anos." },
      { texto: "20 pontos percentuais.", porque: "A redução de 20 p.p. aplica-se a contratos de 20 ou mais anos." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS (Lei 56/2023) — redução para 5-10 anos",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-26",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é a taxa efetiva de IRS sobre rendas habitacionais num contrato de 5 a 10 anos comunicado à AT?",
    opcoes: [
      { texto: "25%", porque: "25% é a taxa base, mas com a redução de 10 p.p. para contratos de 5-10 anos, a taxa efetiva é 15%." },
      { texto: "15%", porque: "Com a redução de 10 p.p. (para contratos habitacionais de 5-10 anos comunicados à AT), a taxa efetiva passa de 25% para 15%." },
      { texto: "10%", porque: "10% é a taxa efetiva para contratos de 10-20 anos, não de 5-10 anos." },
      { texto: "5%", porque: "5% é a taxa efetiva para contratos de 20 ou mais anos." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS — taxa efetiva após redução (5-10 anos)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-27",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é a taxa efetiva de IRS sobre rendas habitacionais num contrato de 10 a 20 anos comunicado à AT?",
    opcoes: [
      { texto: "15%", porque: "15% é a taxa efetiva para contratos de 5-10 anos. Para 10-20 anos, a redução é maior (15 p.p.), resultando em 10%." },
      { texto: "10%", porque: "Com a redução de 15 p.p. (para contratos de 10-20 anos comunicados à AT), a taxa efetiva passa de 25% para 10%." },
      { texto: "5%", porque: "5% é a taxa efetiva para contratos de 20 ou mais anos, não de 10-20 anos." },
      { texto: "20%", porque: "20% não corresponde a nenhuma taxa efetiva prevista após as reduções por duração do contrato." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS — taxa efetiva após redução (10-20 anos)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-28",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é a taxa efetiva de IRS sobre rendas habitacionais num contrato de 20 ou mais anos comunicado à AT?",
    opcoes: [
      { texto: "10%", porque: "10% é a taxa efetiva para contratos de 10-20 anos. Com 20 ou mais anos, a redução é de 20 p.p., resultando em 5%." },
      { texto: "0%", porque: "A taxa nunca chega a 0% — a redução máxima é de 20 p.p., resultando numa taxa efetiva de 5%." },
      { texto: "5%", porque: "Com a redução de 20 p.p. (para contratos de 20 ou mais anos comunicados à AT), a taxa efetiva é de apenas 5% (25% - 20 p.p.)." },
      { texto: "15%", porque: "15% é a taxa efetiva para contratos de 5-10 anos, não de 20 ou mais anos." },
    ],
    correta: 2,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS — taxa efetiva após redução (≥20 anos)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-29",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Cada renovação de um contrato de arrendamento habitacional permanente comunicado à AT dá direito a uma redução adicional de:",
    opcoes: [
      { texto: "1 ponto percentual.", porque: "A redução por renovação é de 2 pontos percentuais por cada renovação, não 1 p.p." },
      { texto: "2 pontos percentuais.", porque: "Cada renovação do contrato de arrendamento habitacional permanente dá uma redução adicional de 2 p.p. na taxa autónoma." },
      { texto: "5 pontos percentuais.", porque: "5 p.p. por renovação ultrapassa o previsto — a redução é de 2 p.p. por renovação." },
      { texto: "3 pontos percentuais.", porque: "A redução por renovação é de 2 p.p., não 3 p.p." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS (Lei 56/2023) — redução por renovação do contrato",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-30",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é o limite máximo de redução acumulada por renovações de contratos de arrendamento habitacional?",
    opcoes: [
      { texto: "5 pontos percentuais.", porque: "O limite máximo de redução acumulada por renovações é de 10 p.p., não 5 p.p." },
      { texto: "10 pontos percentuais.", porque: "A redução acumulada por renovações pode atingir no máximo 10 pontos percentuais (5 renovações x 2 p.p.)." },
      { texto: "15 pontos percentuais.", porque: "15 p.p. excede o limite máximo permitido por renovações, que é de 10 p.p." },
      { texto: "20 pontos percentuais.", porque: "20 p.p. é a redução máxima por duração do contrato (≥20 anos), não o limite por renovações." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS (Lei 56/2023) — limite de redução por renovações",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-31",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "As reduções de taxa por duração do contrato aplicam-se ao arrendamento não habitacional (lojas, escritórios)?",
    opcoes: [
      { texto: "Sim, nos mesmos termos que o habitacional.", porque: "As reduções por duração do contrato aplicam-se apenas ao arrendamento habitacional permanente, não ao não habitacional." },
      { texto: "Sim, mas com percentagens diferentes.", porque: "As reduções por duração do contrato não se aplicam ao arrendamento não habitacional." },
      { texto: "Não, aplicam-se apenas ao arrendamento habitacional permanente.", porque: "As reduções de taxa por duração do contrato (Art. 72.º CIRS) destinam-se exclusivamente ao arrendamento habitacional permanente." },
      { texto: "Sim, se o contrato for superior a 10 anos.", porque: "Independentemente da duração, as reduções não se aplicam ao arrendamento não habitacional." },
    ],
    correta: 2,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS — âmbito das reduções (habitacional permanente)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-32",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Para beneficiar das reduções de taxa por duração do contrato, o senhorio deve:",
    opcoes: [
      { texto: "Apenas celebrar o contrato por escrito.", porque: "Além de ter contrato escrito, é necessário comunicar o contrato à AT para beneficiar das reduções." },
      { texto: "Comunicar o contrato de arrendamento à AT.", porque: "Para beneficiar das reduções de taxa, o contrato de arrendamento habitacional permanente deve ser comunicado à Autoridade Tributária." },
      { texto: "Registar o contrato na Câmara Municipal.", porque: "O registo relevante é a comunicação à AT (Autoridade Tributária), não à Câmara Municipal." },
      { texto: "Não é necessário nenhum procedimento especial.", porque: "É necessário comunicar o contrato à AT para que as reduções sejam aplicadas." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — requisito de comunicação à AT para reduções",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-33",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "O englobamento dos rendimentos prediais é vantajoso quando:",
    opcoes: [
      { texto: "O rendimento coletável total coloca o contribuinte num escalão com taxa marginal superior a 25%.", porque: "Se a taxa marginal for superior a 25% (ou 28% para não habitacional), o englobamento não é vantajoso — a taxa autónoma é mais baixa." },
      { texto: "A taxa marginal de IRS do contribuinte é inferior a 25%.", porque: "O englobamento é vantajoso quando a taxa marginal é inferior à taxa autónoma (25% para habitação / 28% para não habitação)." },
      { texto: "O senhorio tem mais de 65 anos.", porque: "A idade do senhorio não é critério para determinar se o englobamento é vantajoso — depende da taxa marginal." },
      { texto: "O imóvel está localizado no interior do país.", porque: "A localização do imóvel não é critério para a vantagem do englobamento." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — englobamento vs. tributação autónoma",
    fonte: fonte("art72"),
  },
  {
    id: "catf-34",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se o senhorio optar pelo englobamento dos rendimentos prediais, que acontece às restantes categorias de rendimento sujeitas a taxas especiais?",
    opcoes: [
      { texto: "Nada, cada categoria é independente.", porque: "A opção pelo englobamento obriga a englobar todos os rendimentos sujeitos a taxas especiais (Art. 22.º, n.º 5 CIRS)." },
      { texto: "Deve englobar também todos os rendimentos sujeitos a taxas especiais.", porque: "A opção pelo englobamento é global — obriga a englobar todos os rendimentos sujeitos a taxas especiais/liberatórias (Art. 22.º, n.º 5 CIRS)." },
      { texto: "Pode escolher quais categorias englobar.", porque: "Não é possível englobar seletivamente — a opção pelo englobamento abrange todas as categorias sujeitas a taxas especiais." },
      { texto: "Apenas os rendimentos de capitais são também englobados.", porque: "O englobamento abrange todos os rendimentos sujeitos a taxas especiais, não apenas os de capitais." },
    ],
    correta: 1,
    legalBasis: "Art. 22.º, n.º 5 CIRS — obrigatoriedade de englobamento global",
    fonte: fonte("art72"),
  },
  {
    id: "catf-35",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Obras de conservação e manutenção do imóvel arrendado são dedutíveis na Categoria F?",
    opcoes: [
      { texto: "Sim, são despesas dedutíveis.", porque: "As despesas de conservação e manutenção do imóvel arrendado são dedutíveis aos rendimentos prediais (Art. 41.º CIRS)." },
      { texto: "Não, apenas o IMI é dedutível.", porque: "Além do IMI, as despesas de conservação e manutenção são também dedutíveis (Art. 41.º CIRS)." },
      { texto: "Apenas se forem inferiores a 5 000 EUR.", porque: "Não existe limite de valor para a dedução de despesas de conservação e manutenção." },
      { texto: "Apenas se o contrato for superior a 2 anos.", porque: "A dedutibilidade das despesas de conservação não depende da duração do contrato." },
    ],
    correta: 0,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (conservação e manutenção)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-36",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Os juros de um empréstimo bancário para aquisição do imóvel arrendado são dedutíveis na Categoria F?",
    opcoes: [
      { texto: "Sim, na totalidade.", porque: "Os juros de empréstimo hipotecário não são dedutíveis aos rendimentos prediais da Categoria F (Art. 41.º CIRS)." },
      { texto: "Sim, até 50% do valor dos juros.", porque: "Os juros de empréstimo não são dedutíveis na Categoria F, nem parcialmente." },
      { texto: "Não, os juros não são despesas dedutíveis na Categoria F.", porque: "Os juros de empréstimos bancários não constam das despesas dedutíveis previstas no Art. 41.º CIRS para a Categoria F." },
      { texto: "Apenas se o empréstimo for anterior a 2012.", porque: "Independentemente da data do empréstimo, os juros não são dedutíveis na Categoria F." },
    ],
    correta: 2,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (juros excluídos)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-37",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se o senhorio receber 800 EUR/mês de renda e pagar 600 EUR/ano de IMI, 200 EUR/ano de condomínio e 150 EUR/ano de seguro obrigatório, qual é o rendimento líquido tributável da Categoria F?",
    opcoes: [
      { texto: "9 600 EUR", porque: "9 600 EUR é o rendimento bruto (800 x 12). É necessário deduzir as despesas (IMI + condomínio + seguro = 950 EUR)." },
      { texto: "8 650 EUR", porque: "Rendimento bruto: 800 x 12 = 9 600 EUR. Despesas dedutíveis: 600 + 200 + 150 = 950 EUR. Rendimento líquido: 9 600 - 950 = 8 650 EUR." },
      { texto: "7 200 EUR", porque: "Este valor não resulta do cálculo correto: 9 600 - 950 = 8 650 EUR." },
      { texto: "8 000 EUR", porque: "Este valor não resulta do cálculo correto: 9 600 - 950 = 8 650 EUR." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — determinação do rendimento líquido da Categoria F",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-38",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "O senhorio de um apartamento habitacional com rendimento líquido de 10 000 EUR (sem reduções por duração) paga quanto de IRS autónomo?",
    opcoes: [
      { texto: "2 500 EUR", porque: "A taxa autónoma para arrendamento habitacional é 25%. Sobre 10 000 EUR: 10 000 x 25% = 2 500 EUR." },
      { texto: "2 800 EUR", porque: "2 800 EUR resultaria da taxa de 28% (não habitacional). Para habitação, a taxa é 25%, logo 2 500 EUR." },
      { texto: "2 000 EUR", porque: "2 000 EUR resultaria de uma taxa de 20%, que não é a taxa base para arrendamento habitacional." },
      { texto: "1 500 EUR", porque: "1 500 EUR resultaria de uma taxa de 15%, que é a taxa efetiva com redução por contrato de 5-10 anos, não a taxa base." },
    ],
    correta: 0,
    legalBasis: "Art. 72.º, n.º 1 CIRS — cálculo da tributação autónoma (habitação a 25%)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-39",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio arrenda uma garagem independente (sem estar associada a habitação). Qual é a taxa autónoma aplicável?",
    opcoes: [
      { texto: "25%", porque: "25% aplica-se ao arrendamento habitacional. Uma garagem independente é não habitacional, tributada a 28%." },
      { texto: "28%", porque: "Uma garagem arrendada de forma independente é classificada como arrendamento não habitacional, tributado à taxa de 28%." },
      { texto: "Isenta de imposto.", porque: "As rendas de garagens não estão isentas — são tributadas como rendimentos prediais." },
      { texto: "15%", porque: "15% é a taxa efetiva com redução por duração de contrato habitacional, não aplicável a garagens." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — arrendamento não habitacional (garagem independente)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-40",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um casal casado em comunhão de bens arrenda um apartamento. Como são declarados os rendimentos prediais?",
    opcoes: [
      { texto: "Totalmente pelo cônjuge que assinou o contrato.", porque: "Em comunhão de bens, os rendimentos prediais são imputados em partes iguais a ambos os cônjuges (50% cada)." },
      { texto: "50% para cada cônjuge.", porque: "Sendo o imóvel um bem comum (comunhão de bens), os rendimentos prediais são imputados em partes iguais (50/50) a cada cônjuge." },
      { texto: "70% para o titular e 30% para o cônjuge.", porque: "A repartição é sempre de 50/50 quando o imóvel pertence a ambos os cônjuges." },
      { texto: "Totalmente pelo cônjuge com maior rendimento.", porque: "A imputação não depende dos rendimentos de cada cônjuge — é sempre 50/50 em comunhão de bens." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º CIRS — imputação de rendimentos prediais (contitularidade)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-41",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "O senhorio que arrenda um imóvel mobilado paga mais imposto na Categoria F?",
    opcoes: [
      { texto: "Sim, a taxa sobe para 35% se o imóvel for mobilado.", porque: "Não existe taxa especial para imóveis mobilados — a taxa depende apenas de ser habitacional (25%) ou não (28%)." },
      { texto: "Não, a taxa autónoma é a mesma, mas as despesas com mobiliário não são dedutíveis.", porque: "A taxa autónoma não varia com o mobiliário. Contudo, as despesas com mobília não são dedutíveis na Categoria F (Art. 41.º CIRS)." },
      { texto: "Sim, paga IVA adicional sobre o mobiliário.", porque: "O arrendamento de imóveis está isento de IVA e o mobiliário incluído não altera esta isenção na Categoria F." },
      { texto: "Não, e as despesas com mobiliário são dedutíveis.", porque: "A taxa é efetivamente a mesma, mas as despesas com mobiliário NÃO são dedutíveis na Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — despesas não dedutíveis (mobiliário)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-42",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual a diferença fiscal entre arrendar um apartamento para habitação e para escritório?",
    opcoes: [
      { texto: "Não há diferença, ambos pagam 25%.", porque: "Existe diferença: habitação paga 25% e não habitacional (escritório) paga 28%." },
      { texto: "A habitação paga 25% e o escritório paga 28%.", porque: "A taxa autónoma é de 25% para arrendamento habitacional e 28% para não habitacional (Art. 72.º CIRS)." },
      { texto: "A habitação paga 28% e o escritório paga 25%.", porque: "É ao contrário: habitação tem taxa inferior (25%) e o escritório paga 28%." },
      { texto: "A única diferença é na dedução de despesas.", porque: "Além das possíveis diferenças nas deduções, a diferença principal é na taxa autónoma (25% vs. 28%)." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxas autónomas diferenciadas",
    fonte: fonte("art72"),
  },
  {
    id: "catf-43",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio não residente em Portugal que arrende um imóvel em território português está sujeito a IRS?",
    opcoes: [
      { texto: "Não, apenas residentes pagam IRS sobre rendas.", porque: "Os não residentes são tributados sobre rendimentos obtidos em Portugal, incluindo rendas de imóveis situados no território." },
      { texto: "Sim, os rendimentos prediais obtidos em Portugal são tributados.", porque: "Os não residentes são tributados sobre rendimentos prediais obtidos em Portugal, às mesmas taxas autónomas (25%/28%)." },
      { texto: "Sim, mas a uma taxa reduzida de 15%.", porque: "Não existe taxa reduzida para não residentes — aplicam-se as mesmas taxas autónomas (25%/28%)." },
      { texto: "Sim, mas apenas se tiver representante fiscal.", porque: "A tributação aplica-se independentemente de ter representante fiscal (embora o representante possa ser obrigatório)." },
    ],
    correta: 1,
    legalBasis: "Art. 18.º CIRS — rendimentos obtidos em território português (não residentes)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-44",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Quando o senhorio celebra um contrato de sublocação (subarrendamento), quem declara os rendimentos?",
    opcoes: [
      { texto: "Apenas o proprietário original.", porque: "No subarrendamento, o sublocador (inquilino original que subloca) também tem rendimentos a declarar." },
      { texto: "O sublocador declara a diferença entre a renda que recebe e a que paga.", porque: "O sublocador (quem subloca) declara como rendimento a diferença entre o que recebe do subinquilino e o que paga ao senhorio." },
      { texto: "Apenas o subinquilino.", porque: "O subinquilino não declara rendimentos — quem os obtém é o sublocador." },
      { texto: "Ninguém, o subarrendamento não gera obrigações fiscais.", porque: "O subarrendamento gera obrigações fiscais tanto para o senhorio como para o sublocador." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º, n.º 2, al. b) CIRS — rendimentos de sublocação",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-45",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se um imóvel estiver arrendado apenas durante 6 meses do ano, como são declarados os rendimentos?",
    opcoes: [
      { texto: "Declara-se o rendimento anual equivalente (extrapolação para 12 meses).", porque: "Declaram-se apenas os rendimentos efetivamente recebidos, não uma extrapolação para 12 meses." },
      { texto: "Declaram-se apenas os rendimentos efetivamente recebidos nos 6 meses.", porque: "Na Categoria F, declaram-se as rendas efetivamente recebidas — se o imóvel só esteve arrendado 6 meses, apenas se declaram essas rendas." },
      { texto: "Deve-se dividir o rendimento anual por 12 e declarar proporcionalmente.", porque: "Não há cálculo proporcional — declara-se o valor das rendas efetivamente recebidas." },
      { texto: "Os 6 meses sem arrendamento são tributados como rendimento presumido.", porque: "Não existe tributação sobre rendimento presumido por imóvel desocupado na Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º CIRS — rendimentos prediais efetivamente obtidos",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-46",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "As despesas de conservação realizadas nos 24 meses anteriores ao arrendamento podem ser deduzidas na Categoria F?",
    opcoes: [
      { texto: "Não, apenas despesas durante o período de arrendamento.", porque: "As despesas de conservação e manutenção realizadas nos 24 meses anteriores ao início do arrendamento podem ser deduzidas (Art. 41.º CIRS)." },
      { texto: "Sim, são dedutíveis se realizadas nos 24 meses anteriores ao arrendamento.", porque: "O Art. 41.º CIRS permite a dedução de despesas de conservação e manutenção realizadas nos 24 meses anteriores ao arrendamento." },
      { texto: "Sim, mas apenas até 1 000 EUR.", porque: "Não existe limite de valor para esta dedução — podem ser deduzidas na totalidade." },
      { texto: "Apenas se forem certificadas por um engenheiro.", porque: "Não é exigida certificação por engenheiro para a dedução destas despesas." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º, n.º 7 CIRS — despesas anteriores ao arrendamento (24 meses)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-47",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se o senhorio tiver despesas dedutíveis superiores às rendas num dado ano, o resultado negativo pode ser reportado?",
    opcoes: [
      { texto: "Não, o resultado negativo perde-se.", porque: "Na Categoria F, o resultado negativo (despesas > rendas) pode ser reportado para os 6 anos seguintes (Art. 55.º CIRS)." },
      { texto: "Sim, pode ser reportado para os 6 anos seguintes.", porque: "O Art. 55.º CIRS permite o reporte de resultados negativos da Categoria F para os 6 anos seguintes." },
      { texto: "Sim, mas apenas para o ano seguinte.", porque: "O reporte não se limita a 1 ano — pode ser feito para os 6 anos seguintes." },
      { texto: "Sim, sem limite de anos.", porque: "O reporte de resultados negativos da Categoria F tem um limite de 6 anos." },
    ],
    correta: 1,
    legalBasis: "Art. 55.º CIRS — reporte de resultados negativos da Categoria F",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-48",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio herda um imóvel e coloca-o a arrendar. Que custos pode deduzir na Categoria F?",
    opcoes: [
      { texto: "O Imposto do Selo da herança e as obras de conservação.", porque: "O Imposto do Selo da herança não é dedutível na Categoria F — apenas são dedutíveis as despesas previstas no Art. 41.º CIRS (IMI, condomínio, conservação, seguro, selo do contrato)." },
      { texto: "Apenas as despesas previstas no Art. 41.º CIRS (IMI, conservação, condomínio, seguro, selo do contrato).", porque: "Na Categoria F, apenas as despesas expressamente previstas no Art. 41.º CIRS são dedutíveis, independentemente de como o imóvel foi adquirido." },
      { texto: "Nenhuma, porque o imóvel foi adquirido por herança.", porque: "A forma de aquisição do imóvel (herança, compra) não afeta as deduções — aplicam-se as regras normais do Art. 41.º." },
      { texto: "O valor da herança dividido por 10 anos.", porque: "Não existe amortização do valor do imóvel herdado na Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (independentes da aquisição)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-49",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um contrato de arrendamento habitacional permanente de 4 anos, comunicado à AT, beneficia de redução na taxa?",
    opcoes: [
      { texto: "Sim, redução de 10 pontos percentuais.", porque: "A redução de 10 p.p. aplica-se a contratos de 5 ou mais anos. Com 4 anos, não há redução." },
      { texto: "Sim, redução de 5 pontos percentuais.", porque: "Não existe escalão de redução para contratos inferiores a 5 anos." },
      { texto: "Não, o contrato deve ter pelo menos 5 anos para beneficiar de redução.", porque: "As reduções de taxa por duração do contrato só se aplicam a contratos com 5 ou mais anos de duração." },
      { texto: "Sim, redução de 2 pontos percentuais.", porque: "2 p.p. é a redução por renovação, não por duração — e contratos com menos de 5 anos não têm redução por duração." },
    ],
    correta: 2,
    legalBasis: "Art. 72.º CIRS — duração mínima de 5 anos para redução",
    fonte: fonte("art72"),
  },
  {
    id: "catf-50",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio paga 400 EUR de IMI e 300 EUR de obras de conservação num imóvel que rende 6 000 EUR/ano. Qual o rendimento líquido?",
    opcoes: [
      { texto: "5 300 EUR", porque: "Rendimento bruto: 6 000 EUR. Despesas dedutíveis: 400 + 300 = 700 EUR. Rendimento líquido: 6 000 - 700 = 5 300 EUR." },
      { texto: "6 000 EUR", porque: "6 000 EUR é o rendimento bruto, sem dedução das despesas (IMI e conservação são dedutíveis)." },
      { texto: "4 500 EUR", porque: "Este valor não resulta do cálculo correto: 6 000 - 700 = 5 300 EUR." },
      { texto: "5 600 EUR", porque: "Este valor não resulta do cálculo correto: 6 000 - 700 = 5 300 EUR." },
    ],
    correta: 0,
    legalBasis: "Art. 41.º CIRS — cálculo do rendimento líquido da Categoria F",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-51",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio não residente na UE que arrende um imóvel em Portugal precisa de nomear representante fiscal?",
    opcoes: [
      { texto: "Não, basta declarar o rendimento no IRS.", porque: "Os não residentes fora da UE/EEE são obrigados a nomear um representante fiscal em Portugal." },
      { texto: "Sim, não residentes fora da UE/EEE devem nomear representante fiscal.", porque: "Os contribuintes não residentes fora da UE/EEE que obtenham rendimentos em Portugal devem nomear um representante fiscal." },
      { texto: "Apenas se as rendas excederem 25 000 EUR anuais.", porque: "A obrigação de representante fiscal não depende do valor das rendas, mas da residência fora da UE/EEE." },
      { texto: "Apenas se tiver mais de 3 imóveis.", porque: "O número de imóveis não é relevante — a obrigação depende da residência fiscal." },
    ],
    correta: 1,
    legalBasis: "Art. 130.º CIRS — representante fiscal para não residentes",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-52",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se o contrato de arrendamento habitacional for cessado antes de completar o período mínimo para a redução de taxa, o que acontece?",
    opcoes: [
      { texto: "Nada, a redução mantém-se.", porque: "Se o contrato cessar antes do prazo, as reduções devem ser corrigidas e o imposto recalculado." },
      { texto: "O senhorio deve devolver a diferença de imposto resultante da redução.", porque: "Se o contrato de arrendamento não cumprir a duração que fundamentou a redução, há lugar a correção e pagamento da diferença de imposto." },
      { texto: "Apenas paga uma coima de 500 EUR.", porque: "A consequência não é uma coima fixa, mas a devolução da diferença de imposto beneficiada com a redução." },
      { texto: "O inquilino assume a diferença de imposto.", porque: "A obrigação fiscal é do senhorio, não do inquilino." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — cessação antecipada e correção da redução",
    fonte: fonte("art72"),
  },
  {
    id: "catf-53",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio com rendimentos exclusivamente de arrendamento (Categoria F) é obrigado a ter contabilidade organizada?",
    opcoes: [
      { texto: "Sim, se as rendas excederem 200 000 EUR.", porque: "A Categoria F não está sujeita a contabilidade organizada — esta exigência aplica-se à Categoria B." },
      { texto: "Não, a Categoria F não exige contabilidade organizada.", porque: "A Categoria F não impõe contabilidade organizada — as despesas dedutíveis são determinadas pelo Art. 41.º CIRS." },
      { texto: "Sim, sempre.", porque: "A Categoria F nunca exige contabilidade organizada ao senhorio." },
      { texto: "Apenas se arrendar mais de 5 imóveis.", porque: "O número de imóveis não impõe contabilidade organizada na Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — Categoria F (sem obrigação de contabilidade organizada)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-54",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual das seguintes opções NÃO é uma despesa dedutível na Categoria F?",
    opcoes: [
      { texto: "IMI.", porque: "O IMI é uma despesa dedutível na Categoria F (Art. 41.º CIRS)." },
      { texto: "Condomínio.", porque: "Os encargos de condomínio são dedutíveis na Categoria F." },
      { texto: "Obras de ampliação que aumentam a área do imóvel.", porque: "Obras que aumentem o valor ou a área do imóvel (melhoramentos/ampliações) não são dedutíveis — apenas conservação e manutenção." },
      { texto: "Seguro obrigatório de incêndio.", porque: "O seguro obrigatório é uma despesa dedutível na Categoria F." },
    ],
    correta: 2,
    legalBasis: "Art. 41.º CIRS — despesas não dedutíveis (obras de valorização)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-55",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "O senhorio deve comunicar o contrato de arrendamento à AT no prazo de quantos dias após a celebração?",
    opcoes: [
      { texto: "15 dias.", porque: "O prazo de comunicação não é 15 dias — depende do tipo de contrato, mas geralmente são 30 dias." },
      { texto: "30 dias.", porque: "O contrato de arrendamento deve ser comunicado à AT até ao final do mês seguinte ao da celebração." },
      { texto: "60 dias.", porque: "60 dias excede o prazo previsto para comunicação do contrato à AT." },
      { texto: "Até ao final do mês seguinte ao da celebração.", porque: "O contrato deve ser comunicado à AT até ao final do mês seguinte ao da sua celebração." },
    ],
    correta: 3,
    legalBasis: "Art. 60.º do Código do Imposto do Selo — comunicação de contratos à AT",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-56",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "O que distingue um arrendamento de curta duração (alojamento local) de um arrendamento da Categoria F?",
    opcoes: [
      { texto: "A duração mínima do contrato.", porque: "Embora a duração seja um fator, a distinção principal é o tipo de serviço: alojamento local inclui serviços complementares e enquadra-se na Categoria B." },
      { texto: "O alojamento local inclui serviços de alojamento e está na Categoria B.", porque: "O alojamento local (AL) é uma atividade de prestação de serviços de alojamento (Categoria B), enquanto o arrendamento tradicional é Categoria F." },
      { texto: "Não há distinção fiscal.", porque: "A distinção é significativa: Categoria B (alojamento local) vs. Categoria F (arrendamento), com taxas e regras diferentes." },
      { texto: "O alojamento local paga menos imposto.", porque: "O alojamento local tem regras diferentes (Categoria B, com possível IVA e Segurança Social), podendo pagar mais imposto." },
    ],
    correta: 1,
    legalBasis: "Art. 28.º CIRS — alojamento local vs. arrendamento (Categoria B vs. F)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-57",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se o senhorio optar pelo englobamento e a sua taxa marginal de IRS for 45%, compensa face à taxa autónoma de 25%?",
    opcoes: [
      { texto: "Sim, o englobamento é sempre mais vantajoso.", porque: "Com taxa marginal de 45%, o englobamento é desvantajoso face à taxa autónoma de 25% (habitação) ou 28% (não habitação)." },
      { texto: "Não, a taxa marginal de 45% é muito superior à taxa autónoma de 25%.", porque: "Com taxa marginal de 45%, a tributação autónoma a 25% é claramente mais vantajosa do que o englobamento." },
      { texto: "Depende do número de imóveis.", porque: "A comparação relevante é entre a taxa marginal e a taxa autónoma, não o número de imóveis." },
      { texto: "Compensa se tiver deduções pessoais elevadas.", porque: "Mesmo com deduções elevadas, uma taxa marginal de 45% dificilmente tornará o englobamento vantajoso face a 25%." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — englobamento vs. tributação autónoma",
    fonte: fonte("art72"),
  },
  {
    id: "catf-58",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se dois irmãos forem comproprietários de um imóvel arrendado (50/50), como declaram os rendimentos?",
    opcoes: [
      { texto: "Apenas um dos irmãos declara a totalidade.", porque: "Cada comproprietário deve declarar a sua quota-parte dos rendimentos prediais." },
      { texto: "Cada irmão declara 50% dos rendimentos no seu Anexo F.", porque: "Na compropriedade, os rendimentos prediais são imputados a cada titular na proporção da sua quota (50% cada)." },
      { texto: "Um declara o rendimento e depois transfere metade ao outro.", porque: "Cada comproprietário declara diretamente a sua quota-parte — não há transferência entre eles." },
      { texto: "Devem criar uma empresa para arrendar o imóvel.", porque: "Não é obrigatório criar empresa — cada comproprietário declara a sua parte no Anexo F." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º CIRS — imputação de rendimentos (compropriedade)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-59",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio arrenda um T2 por 500 EUR/mês e o lugar de garagem associado por 50 EUR/mês. Ambos são tributados a 25%?",
    opcoes: [
      { texto: "Sim, se a garagem estiver incluída no contrato de arrendamento habitacional.", porque: "Se a garagem for arrendada conjuntamente com a habitação no mesmo contrato, ambas são tributadas à taxa habitacional de 25%." },
      { texto: "Não, a garagem é sempre tributada a 28%.", porque: "Se a garagem estiver incluída no mesmo contrato de arrendamento habitacional, é tributada à mesma taxa de 25%." },
      { texto: "Sim, independentemente de serem contratos separados.", porque: "Se forem contratos separados, a garagem pode ser considerada não habitacional (28%). A taxa de 25% só se aplica se incluída no contrato de habitação." },
      { texto: "A garagem é isenta de imposto.", porque: "As rendas de garagens não são isentas de imposto — são tributadas como rendimentos prediais." },
    ],
    correta: 0,
    legalBasis: "Art. 72.º CIRS — garagem incluída no contrato habitacional",
    fonte: fonte("art72"),
  },
  {
    id: "catf-60",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Qual é a taxa de Imposto do Selo sobre o valor da renda mensal de um novo contrato de arrendamento?",
    opcoes: [
      { texto: "10%", porque: "A taxa de Imposto do Selo sobre o arrendamento é inferior a 10%." },
      { texto: "5%", porque: "5% não é a taxa de Imposto do Selo aplicável ao arrendamento." },
      { texto: "10% sobre a renda de um mês.", porque: "A taxa de Imposto do Selo sobre o arrendamento é de 10% sobre o valor da renda mensal declarada." },
      { texto: "Não há Imposto do Selo sobre arrendamento.", porque: "O contrato de arrendamento está sujeito a Imposto do Selo." },
    ],
    correta: 2,
    legalBasis: "Tabela Geral do Imposto do Selo, verba 2 — arrendamento",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-61",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Se o senhorio tiver rendas em atraso (não recebidas), deve declará-las no IRS?",
    opcoes: [
      { texto: "Sim, todas as rendas devidas devem ser declaradas, mesmo que não recebidas.", porque: "Na Categoria F, declaram-se as rendas efetivamente recebidas ou postas à disposição, não as devidas e não pagas." },
      { texto: "Não, apenas se declaram as rendas efetivamente recebidas.", porque: "Os rendimentos prediais a declarar são os efetivamente recebidos ou colocados à disposição do senhorio." },
      { texto: "Sim, e depois pode pedir a devolução se não receber.", porque: "Não é necessário declarar rendas não recebidas — declara-se apenas o efetivamente recebido." },
      { texto: "Depende se foi instaurada ação de despejo.", porque: "Independentemente de ações judiciais, declaram-se apenas as rendas efetivamente recebidas." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º CIRS — rendimentos prediais (rendas efetivamente recebidas)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-62",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio pode deduzir na Categoria F os gastos com certificação energética do imóvel?",
    opcoes: [
      { texto: "Sim, enquadra-se como despesa de conservação.", porque: "A certificação energética pode não ser uma despesa de conservação em sentido estrito, mas sim uma despesa administrativa." },
      { texto: "Não, a certificação energética não está prevista no Art. 41.º CIRS.", porque: "A certificação energética não se enquadra diretamente nas despesas dedutíveis previstas no Art. 41.º CIRS (conservação, IMI, condomínio, seguro, selo)." },
      { texto: "Sim, se o certificado tiver classe A ou superior.", porque: "A classe energética do certificado não é critério para a dedutibilidade fiscal." },
      { texto: "Apenas para imóveis novos.", porque: "A questão da dedutibilidade não depende de o imóvel ser novo ou usado." },
    ],
    correta: 1,
    legalBasis: "Art. 41.º CIRS — despesas dedutíveis (lista taxativa)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-63",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um contrato de arrendamento habitacional permanente de 12 anos, comunicado à AT, com 2 renovações, tem uma taxa efetiva de:",
    opcoes: [
      { texto: "10%", porque: "A taxa base é 25%, com redução de 15 p.p. (10-20 anos) = 10%. Com 2 renovações, reduz-se mais 4 p.p. (2 x 2 p.p.), resultando em 6%." },
      { texto: "6%", porque: "Taxa base 25% - 15 p.p. (contrato 10-20 anos) = 10%. Renovações: 2 x 2 p.p. = 4 p.p. Total: 10% - 4% = 6%." },
      { texto: "8%", porque: "O cálculo correto é: 25% - 15 p.p. - 4 p.p. = 6%, não 8%." },
      { texto: "15%", porque: "15% seria a taxa para um contrato de 5-10 anos sem renovações — com 12 anos e renovações, a taxa é inferior." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxa efetiva com redução por duração + renovações",
    fonte: fonte("art72"),
  },
  {
    id: "catf-64",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um contrato habitacional de 22 anos comunicado à AT, com 3 renovações, tem uma taxa efetiva de:",
    opcoes: [
      { texto: "5%", porque: "A redução por duração (≥20 anos) é de 20 p.p. (taxa de 5%), mas há ainda 3 renovações x 2 p.p. = 6 p.p. adicionais, resultando em 0% (com mínimo de 0%)." },
      { texto: "0%", porque: "Taxa base 25% - 20 p.p. (≥20 anos) = 5%. Renovações: 3 x 2 p.p. = 6 p.p. Resultado: 5% - 6% = -1%, arredondado a 0%. A taxa não pode ser negativa." },
      { texto: "1%", porque: "O cálculo resulta em valor negativo (-1%), pelo que a taxa efetiva é de 0% (não pode ser negativa), não 1%." },
      { texto: "3%", porque: "O cálculo correto leva a um valor inferior a 3%: 25% - 20 p.p. - 6 p.p. = -1%, resultando em 0%." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxa efetiva mínima (não pode ser negativa)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-65",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio com rendimento coletável total de 8 000 EUR (incluindo rendas) fica no 1.º escalão de IRS (14,5%). Deve optar pelo englobamento?",
    opcoes: [
      { texto: "Não, a taxa autónoma de 25% é sempre preferível.", porque: "Com taxa marginal de 14,5%, o englobamento é vantajoso porque 14,5% < 25% (taxa autónoma habitacional)." },
      { texto: "Sim, o englobamento é vantajoso porque a taxa marginal (14,5%) é inferior a 25%.", porque: "Quando a taxa marginal de IRS é inferior à taxa autónoma (25% ou 28%), o englobamento reduz a carga fiscal." },
      { texto: "Depende do número de dependentes.", porque: "A comparação relevante é entre a taxa marginal e a taxa autónoma — o número de dependentes pode afetar a taxa marginal, mas a análise base é esta." },
      { texto: "Sim, mas só se não tiver outros rendimentos.", porque: "A decisão depende da taxa marginal resultante de TODOS os rendimentos englobados, não apenas dos prediais." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — englobamento vantajoso quando taxa marginal < 25%",
    fonte: fonte("art72"),
  },
  {
    id: "catf-66",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio opta pelo englobamento das rendas. A sua taxa marginal de IRS é 23%. Qual a poupança face à taxa autónoma de 25% sobre rendas habitacionais de 12 000 EUR líquidos?",
    opcoes: [
      { texto: "240 EUR", porque: "Diferença: 25% - 23% = 2 p.p. sobre 12 000 EUR = 240 EUR de poupança com o englobamento." },
      { texto: "360 EUR", porque: "360 EUR resultaria de uma diferença de 3 p.p., mas a diferença real é 2 p.p. (25% - 23%)." },
      { texto: "600 EUR", porque: "600 EUR resultaria de uma diferença de 5 p.p., que não corresponde ao cálculo correto." },
      { texto: "120 EUR", porque: "120 EUR resultaria de uma diferença de 1 p.p., mas a diferença é de 2 p.p." },
    ],
    correta: 0,
    legalBasis: "Art. 72.º CIRS — cálculo da vantagem do englobamento",
    fonte: fonte("art72"),
  },
  {
    id: "catf-67",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio arrenda 3 apartamentos: um habitacional (500 EUR/mês), um escritório (800 EUR/mês) e um armazém (600 EUR/mês). Sem deduções, qual o IRS total anual por tributação autónoma?",
    opcoes: [
      { texto: "6 528 EUR", porque: "Habitação: 6 000 x 25% = 1 500. Escritório: 9 600 x 28% = 2 688. Armazém: 7 200 x 28% = 2 016. Total: 1 500 + 2 688 + 2 016 = 6 204 EUR." },
      { texto: "6 204 EUR", porque: "Habitação: 500 x 12 x 25% = 1 500. Escritório: 800 x 12 x 28% = 2 688. Armazém: 600 x 12 x 28% = 2 016. Total: 6 204 EUR." },
      { texto: "5 700 EUR", porque: "Este valor não resulta do cálculo correto: 1 500 + 2 688 + 2 016 = 6 204 EUR." },
      { texto: "5 472 EUR", porque: "Este valor não resulta do cálculo correto: 1 500 + 2 688 + 2 016 = 6 204 EUR." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — tributação autónoma diferenciada por tipo de arrendamento",
    fonte: fonte("art72"),
  },
  {
    id: "catf-68",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Se o senhorio optar por transferir o arrendamento para a Categoria B (atividade de arrendamento como empresário em nome individual), que consequência fiscal principal surge?",
    opcoes: [
      { texto: "Passa a estar sujeito a contribuições para a Segurança Social.", porque: "Na Categoria B, os rendimentos ficam sujeitos a contribuições para a Segurança Social, ao contrário da Categoria F." },
      { texto: "Fica isento de IRS.", porque: "A transferência para a Categoria B não isenta de IRS — muda o regime de tributação." },
      { texto: "A taxa autónoma aumenta para 35%.", porque: "Na Categoria B, a tributação não é por taxa autónoma de 35% — aplica-se o regime simplificado ou contabilidade organizada." },
      { texto: "Não há consequências diferentes.", porque: "Há consequências significativas, nomeadamente a sujeição a Segurança Social e a diferentes regras de tributação." },
    ],
    correta: 0,
    legalBasis: "Código Contributivo — Segurança Social na Categoria B",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-69",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio realizou obras no valor de 15 000 EUR num imóvel que rende 10 000 EUR/ano. As obras geraram um resultado negativo de 5 000 EUR. Pode reportá-lo?",
    opcoes: [
      { texto: "Não, os resultados negativos da Categoria F perdem-se.", porque: "Os resultados negativos da Categoria F podem ser reportados para os 6 anos seguintes (Art. 55.º CIRS)." },
      { texto: "Sim, pode reportar os 5 000 EUR para os 6 anos seguintes.", porque: "O resultado negativo (despesas > rendas) pode ser reportado e deduzido aos rendimentos prediais dos 6 anos seguintes." },
      { texto: "Sim, mas apenas até 3 anos.", porque: "O prazo de reporte é de 6 anos, não 3." },
      { texto: "Sim, e pode deduzir a outros rendimentos (ex.: salário).", porque: "O resultado negativo da Categoria F só pode ser deduzido a rendimentos da mesma categoria, não a outros rendimentos." },
    ],
    correta: 1,
    legalBasis: "Art. 55.º CIRS — reporte de resultados negativos (6 anos)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-70",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um contrato habitacional de 6 anos comunicado à AT, com taxa efetiva de 15%, é renovado uma vez. Qual a nova taxa efetiva?",
    opcoes: [
      { texto: "15%", porque: "Com a renovação, a taxa reduz mais 2 p.p.: 15% - 2% = 13%." },
      { texto: "13%", porque: "A taxa efetiva de 15% (contrato 5-10 anos) com uma renovação (-2 p.p.) passa a 13%." },
      { texto: "10%", porque: "10% seria a taxa para contratos de 10-20 anos sem renovações — aqui é 15% - 2 p.p. = 13%." },
      { texto: "12%", porque: "12% não resulta do cálculo correto: 15% - 2 p.p. = 13%." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — redução adicional por renovação (-2 p.p.)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-71",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Para que as reduções por duração do contrato se apliquem, o arrendamento deve ser:",
    opcoes: [
      { texto: "Habitacional ou não habitacional, desde que comunicado à AT.", porque: "As reduções aplicam-se apenas ao arrendamento habitacional permanente, não ao não habitacional." },
      { texto: "Habitacional permanente, com contrato comunicado à AT.", porque: "As reduções exigem cumulativamente: arrendamento habitacional permanente e comunicação do contrato à AT." },
      { texto: "Qualquer tipo de arrendamento com duração superior a 5 anos.", porque: "Não basta a duração — deve ser arrendamento habitacional permanente e comunicado à AT." },
      { texto: "Habitacional temporário, desde que superior a 5 anos.", porque: "Deve ser arrendamento habitacional permanente (residência habitual), não temporário." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º, n.os 2 a 5 CIRS — requisitos para reduções de taxa",
    fonte: fonte("art72"),
  },
  {
    id: "catf-72",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Se um senhorio tiver simultaneamente rendas habitacionais (Categoria F) e rendimentos de alojamento local (Categoria B), como são tributados?",
    opcoes: [
      { texto: "Ambos na Categoria F.", porque: "O alojamento local é tributado na Categoria B, não na F — são categorias diferentes." },
      { texto: "Ambos na Categoria B.", porque: "As rendas de arrendamento tradicional mantêm-se na Categoria F — apenas o alojamento local é Categoria B." },
      { texto: "Cada um na respetiva categoria: F (arrendamento) e B (alojamento local).", porque: "O arrendamento tradicional é tributado na Categoria F e o alojamento local na Categoria B, cada um com as suas regras específicas." },
      { texto: "O senhorio deve escolher uma única categoria.", porque: "Não é necessário escolher — cada tipo de rendimento é automaticamente enquadrado na sua categoria respetiva." },
    ],
    correta: 2,
    legalBasis: "Art. 8.º e Art. 28.º CIRS — Categorias F e B (independentes)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-73",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio com 4 imóveis arrendados para habitação, cada um com contrato de 8 anos comunicado à AT, beneficia de redução em todos?",
    opcoes: [
      { texto: "Não, a redução aplica-se apenas ao primeiro imóvel.", porque: "A redução aplica-se a cada contrato individualmente — não há limite por número de imóveis." },
      { texto: "Sim, a redução aplica-se a cada contrato individualmente.", porque: "A redução de taxa por duração do contrato aplica-se individualmente a cada contrato habitacional permanente comunicado à AT, sem limite de imóveis." },
      { texto: "Apenas a 2 imóveis no máximo.", porque: "Não existe limite do número de imóveis que podem beneficiar das reduções." },
      { texto: "Sim, mas com uma redução global menor.", porque: "Não há redução progressiva — cada contrato beneficia da mesma redução independentemente do número de imóveis." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — reduções aplicáveis por contrato individual",
    fonte: fonte("art72"),
  },
  {
    id: "catf-74",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um imóvel é arrendado parte para habitação e parte para comércio (uso misto). Como são tributadas as rendas?",
    opcoes: [
      { texto: "Toda a renda à taxa de 25%.", porque: "Em uso misto, a renda deve ser repartida entre a parte habitacional (25%) e a parte não habitacional (28%)." },
      { texto: "Toda a renda à taxa de 28%.", porque: "Em uso misto, não se aplica a taxa mais alta a todo o rendimento — a renda é repartida proporcionalmente." },
      { texto: "A renda é repartida proporcionalmente: parte habitacional a 25% e parte comercial a 28%.", porque: "Em uso misto, a renda deve ser imputada proporcionalmente a cada utilização, aplicando-se a taxa respetiva." },
      { texto: "A taxa é a média ponderada: 26,5%.", porque: "Não se aplica uma taxa média — cada parte é tributada à taxa correspondente à sua utilização." },
    ],
    correta: 2,
    legalBasis: "Art. 72.º CIRS — tributação de uso misto",
    fonte: fonte("art72"),
  },
  {
    id: "catf-75",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio arrenda um imóvel rural (terreno agrícola) a um agricultor. Qual a taxa autónoma aplicável?",
    opcoes: [
      { texto: "25%", porque: "25% é a taxa para arrendamento habitacional. O arrendamento rural (não habitacional) é tributado a 28%." },
      { texto: "28%", porque: "O arrendamento de imóveis rústicos (terrenos agrícolas) é considerado não habitacional, sendo tributado à taxa de 28%." },
      { texto: "Isento de imposto.", porque: "O arrendamento de imóveis rústicos não é isento — está sujeito à taxa autónoma da Categoria F." },
      { texto: "10%", porque: "10% não é uma taxa base da Categoria F — seria a taxa efetiva para contratos habitacionais de 10-20 anos." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — arrendamento rural (não habitacional, taxa de 28%)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-76",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio recebe rendas em atraso de anos anteriores (rendas de 2024 recebidas em 2025). Em que ano declara?",
    opcoes: [
      { texto: "No ano a que as rendas dizem respeito (2024).", porque: "Na Categoria F, as rendas são declaradas no ano em que são efetivamente recebidas, não no ano a que respeitam." },
      { texto: "No ano em que são efetivamente recebidas (2025).", porque: "Os rendimentos prediais são tributados no ano em que são efetivamente recebidos ou postos à disposição do senhorio." },
      { texto: "Repartidas igualmente entre ambos os anos.", porque: "Não há repartição — as rendas são declaradas integralmente no ano do recebimento efetivo." },
      { texto: "Deve apresentar declaração de substituição para 2024.", porque: "Não é necessária declaração de substituição — as rendas declaram-se no ano do recebimento." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º CIRS — momento de tributação dos rendimentos prediais",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-77",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "O senhorio pode optar por incluir os rendimentos prediais na Categoria B em vez da Categoria F?",
    opcoes: [
      { texto: "Não, os rendimentos prediais são sempre Categoria F.", porque: "O senhorio pode optar por tributar os rendimentos prediais na Categoria B se exercer atividade de arrendamento como empresário." },
      { texto: "Sim, pode optar pela Categoria B, ficando sujeito às suas regras (incluindo Segurança Social).", porque: "O senhorio pode optar pela Categoria B, mas fica sujeito a Segurança Social e às regras do regime simplificado ou contabilidade organizada." },
      { texto: "Apenas se tiver mais de 10 imóveis.", porque: "A opção pela Categoria B não depende do número de imóveis." },
      { texto: "Apenas se faturar mais de 200 000 EUR/ano.", porque: "A opção pela Categoria B não depende do volume de faturação." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º e Art. 3.º CIRS — opção pela Categoria B",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-78",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio realiza obras de melhoria que aumentam o valor do imóvel em 20 000 EUR. Pode deduzir este custo na Categoria F?",
    opcoes: [
      { texto: "Sim, na totalidade.", porque: "Obras de melhoria/valorização não são dedutíveis na Categoria F — apenas conservação e manutenção." },
      { texto: "Sim, dividido por 5 anos.", porque: "Não existe amortização de obras de melhoria na Categoria F — estas despesas não são dedutíveis." },
      { texto: "Não, obras de melhoria/valorização não são dedutíveis na Categoria F.", porque: "Na Categoria F, apenas são dedutíveis despesas de conservação e manutenção, não obras que aumentem o valor do imóvel (Art. 41.º CIRS)." },
      { texto: "Apenas se as obras forem certificadas pela Câmara Municipal.", porque: "A certificação é irrelevante — obras de valorização simplesmente não são dedutíveis na Categoria F." },
    ],
    correta: 2,
    legalBasis: "Art. 41.º CIRS — obras de valorização (não dedutíveis)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-79",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Se o senhorio englobar os rendimentos prediais, pode deduzir as contribuições para a Segurança Social pagas como trabalhador independente?",
    opcoes: [
      { texto: "Sim, as contribuições são deduzidas ao rendimento global englobado.", porque: "As contribuições para a Segurança Social de trabalhador independente (Categoria B) são dedutíveis como dedução específica da Categoria B, mas não reduzem os rendimentos da Categoria F." },
      { texto: "Não, as contribuições de Segurança Social de Categoria B não reduzem os rendimentos de Categoria F.", porque: "As deduções específicas de cada categoria aplicam-se separadamente — as contribuições da Categoria B não reduzem rendimentos da Categoria F." },
      { texto: "Sim, até 50% das contribuições.", porque: "Não existe dedução parcial de contribuições da Categoria B aos rendimentos da Categoria F." },
      { texto: "Apenas se não optar pelo regime simplificado.", porque: "O regime de tributação da Categoria B não influencia a dedutibilidade de contribuições na Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 25.º e Art. 41.º CIRS — deduções específicas por categoria",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-80",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um contrato de arrendamento habitacional de 15 anos comunicado à AT beneficia de que taxa efetiva?",
    opcoes: [
      { texto: "15%", porque: "15% é a taxa para contratos de 5-10 anos. Com 15 anos (escalão 10-20), a redução é de 15 p.p., resultando em 10%." },
      { texto: "10%", porque: "Contratos de 10-20 anos beneficiam de redução de 15 p.p.: 25% - 15 p.p. = 10%." },
      { texto: "5%", porque: "5% aplica-se a contratos de 20 ou mais anos, não de 15 anos." },
      { texto: "25%", porque: "25% é a taxa base sem qualquer redução — com 15 anos, a taxa efetiva é inferior." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxa efetiva para contratos de 10-20 anos",
    fonte: fonte("art72"),
  },
  {
    id: "catf-81",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio recebe uma indemnização do inquilino pela rescisão antecipada do contrato. Esta indemnização é tributada na Categoria F?",
    opcoes: [
      { texto: "Não, indemnizações não são rendimentos prediais.", porque: "As indemnizações pagas pelo inquilino ao senhorio pela rescisão do contrato são consideradas rendimentos prediais (Art. 8.º CIRS)." },
      { texto: "Sim, é considerada rendimento predial e tributada na Categoria F.", porque: "A indemnização paga pelo inquilino ao senhorio pela cessação do contrato constitui rendimento predial (Art. 8.º, n.º 2, al. a) CIRS)." },
      { texto: "É tributada na Categoria G (incrementos patrimoniais).", porque: "Não é um incremento patrimonial — é rendimento predial da Categoria F." },
      { texto: "Apenas se exceder 6 meses de renda.", porque: "A tributação não depende do valor da indemnização — é sempre rendimento predial." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º, n.º 2, al. a) CIRS — indemnizações como rendimento predial",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-82",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "O senhorio que arrende a uma sociedade (pessoa coletiva) pode beneficiar das reduções por duração do contrato habitacional?",
    opcoes: [
      { texto: "Não, as reduções só se aplicam a contratos com pessoas singulares.", porque: "As reduções exigem arrendamento habitacional permanente — contratos com sociedades podem qualificar se a utilização for para habitação permanente (ex.: subarrendamento a funcionários para habitação)." },
      { texto: "Sim, desde que o imóvel seja destinado a habitação permanente dos trabalhadores da sociedade.", porque: "As reduções podem aplicar-se se o contrato for habitacional permanente e o destino efetivo for habitação, mesmo com sociedade como inquilina." },
      { texto: "Sim, independentemente do uso do imóvel.", porque: "As reduções exigem que o arrendamento seja efetivamente para habitação permanente, não bastando a mera celebração do contrato." },
      { texto: "Nunca, sociedades não podem celebrar contratos habitacionais.", porque: "Sociedades podem celebrar contratos de arrendamento habitacional (ex.: para alojamento de trabalhadores)." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — reduções por duração (habitação permanente)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-83",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio com rendas de 18 000 EUR/ano (habitação) e despesas dedutíveis de 3 000 EUR tem um contrato de 8 anos comunicado à AT. Quanto paga de IRS?",
    opcoes: [
      { texto: "2 250 EUR", porque: "Rendimento líquido: 18 000 - 3 000 = 15 000 EUR. Taxa efetiva (5-10 anos): 15%. IRS: 15 000 x 15% = 2 250 EUR." },
      { texto: "3 750 EUR", porque: "3 750 EUR resultaria da taxa de 25% sobre 15 000 EUR, sem considerar a redução por duração do contrato." },
      { texto: "1 500 EUR", porque: "1 500 EUR resultaria de uma taxa de 10%, que se aplica a contratos de 10-20 anos, não de 5-10." },
      { texto: "3 000 EUR", porque: "3 000 EUR resultaria da taxa de 20%, que não corresponde a nenhuma taxa efetiva prevista." },
    ],
    correta: 0,
    legalBasis: "Art. 72.º CIRS — cálculo do IRS com redução por duração (5-10 anos)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-84",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Qual a consequência se o senhorio não comunicar o contrato de arrendamento à AT mas tiver um contrato de longa duração?",
    opcoes: [
      { texto: "Perde o direito às reduções por duração do contrato.", porque: "A comunicação à AT é requisito essencial para beneficiar das reduções — sem comunicação, aplica-se a taxa base (25% ou 28%)." },
      { texto: "As reduções são aplicadas automaticamente.", porque: "As reduções NÃO são automáticas — exigem a comunicação do contrato à AT." },
      { texto: "Pode comunicar a qualquer momento e obter as reduções retroativamente.", porque: "A comunicação tardia pode não dar direito a reduções retroativas — deve ser feita nos prazos legais." },
      { texto: "Nenhuma, a comunicação é facultativa.", porque: "A comunicação é obrigatória para beneficiar das reduções de taxa." },
    ],
    correta: 0,
    legalBasis: "Art. 72.º CIRS — requisito de comunicação para reduções",
    fonte: fonte("art72"),
  },
  {
    id: "catf-85",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Se um senhorio tiver prejuízos na Categoria F num ano, pode deduzir esses prejuízos a rendimentos do trabalho (Categoria A)?",
    opcoes: [
      { texto: "Sim, os prejuízos podem ser deduzidos a qualquer categoria.", porque: "Os prejuízos da Categoria F só podem ser deduzidos a rendimentos da mesma Categoria F nos anos seguintes." },
      { texto: "Não, os prejuízos da Categoria F só são dedutíveis a rendimentos da mesma categoria.", porque: "O reporte de prejuízos da Categoria F (Art. 55.º CIRS) só permite a dedução a rendimentos futuros da mesma Categoria F." },
      { texto: "Sim, mas apenas até 50% dos rendimentos da Categoria A.", porque: "Não existe possibilidade de deduzir prejuízos da Categoria F a rendimentos de outra categoria." },
      { texto: "Apenas se optar pelo englobamento.", porque: "Mesmo com englobamento, os prejuízos de uma categoria não compensam automaticamente rendimentos de outra." },
    ],
    correta: 1,
    legalBasis: "Art. 55.º CIRS — reporte de prejuízos (apenas dentro da mesma categoria)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-86",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio celebra um contrato habitacional de 5 anos e 1 dia comunicado à AT. Beneficia da redução de 10 p.p.?",
    opcoes: [
      { texto: "Não, o contrato deve ter exatamente 5 anos ou mais anos completos.", porque: "O requisito é que a duração seja igual ou superior a 5 anos — 5 anos e 1 dia cumpre este critério." },
      { texto: "Sim, o contrato tem duração igual ou superior a 5 anos.", porque: "Um contrato de 5 anos e 1 dia cumpre o requisito de duração mínima de 5 anos, beneficiando da redução de 10 p.p." },
      { texto: "Depende da interpretação da AT.", porque: "O critério legal é claro: duração igual ou superior a 5 anos — 5 anos e 1 dia cumpre." },
      { texto: "Só a partir de 6 anos completos.", porque: "O limiar é 5 anos, não 6 — um contrato de 5 anos e 1 dia qualifica." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — duração mínima de 5 anos para primeira redução",
    fonte: fonte("art72"),
  },
  {
    id: "catf-87",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "No cálculo do rendimento líquido da Categoria F, existe uma dedução específica automática (como os 4 104 EUR da Categoria A)?",
    opcoes: [
      { texto: "Sim, existe uma dedução automática de 4 104 EUR.", porque: "A Categoria F não tem dedução específica automática — deduzem-se apenas as despesas efetivas previstas no Art. 41.º." },
      { texto: "Sim, existe uma dedução automática de 2 500 EUR.", porque: "Não existe qualquer dedução específica automática na Categoria F." },
      { texto: "Não, na Categoria F deduzem-se apenas as despesas efetivas (Art. 41.º CIRS).", porque: "Ao contrário da Categoria A, a Categoria F não prevê dedução específica automática — deduzem-se apenas as despesas efetivamente suportadas." },
      { texto: "Sim, 10% do rendimento bruto.", porque: "Não existe dedução percentual automática na Categoria F." },
    ],
    correta: 2,
    legalBasis: "Art. 41.º CIRS — Categoria F (despesas efetivas, sem dedução automática)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-88",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio celebra contratos de arrendamento habitacional com duração de 5 anos. Após 3 renovações (2 p.p. cada), qual a taxa efetiva?",
    opcoes: [
      { texto: "15%", porque: "Taxa base 25% - 10 p.p. (5-10 anos) = 15%. Com 3 renovações: 3 x 2 p.p. = 6 p.p. Taxa: 15% - 6% = 9%." },
      { texto: "9%", porque: "Taxa base 25% - 10 p.p. (contrato 5-10 anos) = 15%. Renovações: 3 x 2 p.p. = 6 p.p. Taxa efetiva: 15% - 6% = 9%." },
      { texto: "11%", porque: "O cálculo correto é 15% - 6 p.p. = 9%, não 11%." },
      { texto: "12%", porque: "O cálculo correto é 15% - 6 p.p. = 9%, não 12%." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxa efetiva com renovações cumuladas",
    fonte: fonte("art72"),
  },
  {
    id: "catf-89",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um não residente na UE arrenda um imóvel em Portugal. A taxa autónoma sobre rendas habitacionais é diferente da de um residente?",
    opcoes: [
      { texto: "Sim, os não residentes pagam uma taxa majorada de 35%.", porque: "Não existe taxa majorada para não residentes — aplicam-se as mesmas taxas autónomas (25%/28%)." },
      { texto: "Não, aplica-se a mesma taxa autónoma (25% para habitação, 28% para não habitação).", porque: "As taxas autónomas da Categoria F são as mesmas para residentes e não residentes (25% habitacional, 28% não habitacional)." },
      { texto: "Os não residentes estão isentos.", porque: "Os não residentes não estão isentos — são tributados sobre rendimentos obtidos em Portugal." },
      { texto: "Sim, os não residentes pagam uma taxa reduzida de 15%.", porque: "Não existe taxa reduzida para não residentes na Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — taxas iguais para residentes e não residentes",
    fonte: fonte("art72"),
  },
  {
    id: "catf-90",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Se o senhorio não emitir recibo de renda eletrónico, pode ser sancionado?",
    opcoes: [
      { texto: "Não, o recibo eletrónico é opcional.", porque: "O recibo de renda eletrónico é obrigatório e a não emissão pode originar coimas." },
      { texto: "Sim, a não emissão do recibo eletrónico constitui infração e pode originar coimas.", porque: "A emissão do recibo de renda eletrónico é obrigatória e o incumprimento pode resultar em coimas (RGIT)." },
      { texto: "Apenas se o inquilino reclamar.", porque: "A obrigação de emissão é independente de qualquer reclamação do inquilino." },
      { texto: "Não, desde que declare as rendas no IRS.", porque: "A declaração no IRS não dispensa a obrigação de emitir o recibo eletrónico." },
    ],
    correta: 1,
    legalBasis: "Portaria 98-A/2015 e RGIT — obrigação de recibo eletrónico",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-91",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Se um senhorio tiver apenas rendimentos de arrendamento (Categoria F), é obrigado a entregar a declaração de IRS?",
    opcoes: [
      { texto: "Não, os rendimentos prediais são tributados automaticamente.", porque: "A tributação não é automática — o senhorio deve entregar a declaração Modelo 3 com Anexo F." },
      { texto: "Sim, deve entregar a Modelo 3 com o Anexo F.", porque: "O senhorio com rendimentos prediais é obrigado a entregar a declaração de IRS (Modelo 3) com o Anexo F." },
      { texto: "Apenas se as rendas excederem 8 500 EUR anuais.", porque: "Não existe limiar mínimo para a obrigação de declarar rendimentos prediais." },
      { texto: "Não, se optar pela tributação autónoma.", porque: "Mesmo com tributação autónoma, o senhorio deve entregar a declaração de IRS com Anexo F." },
    ],
    correta: 1,
    legalBasis: "Art. 57.º CIRS — obrigação de entrega da declaração de IRS",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-92",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Qual das seguintes afirmações é verdadeira sobre a Categoria F?",
    opcoes: [
      { texto: "Os rendimentos prediais estão sujeitos a IVA.", porque: "O arrendamento de imóveis está isento de IVA (Art. 9.º CIVA)." },
      { texto: "Os rendimentos prediais estão sujeitos a Segurança Social.", porque: "Os rendimentos da Categoria F não estão sujeitos a Segurança Social." },
      { texto: "Os rendimentos prediais não estão sujeitos a IVA nem a Segurança Social.", porque: "Na Categoria F, não incide IVA (isento) nem Segurança Social sobre os rendimentos prediais." },
      { texto: "Os rendimentos prediais estão sujeitos a IVA mas não a Segurança Social.", porque: "Os rendimentos prediais estão isentos de IVA — nenhuma das duas cargas se aplica." },
    ],
    correta: 2,
    legalBasis: "Art. 9.º CIVA e Código Contributivo — isenções da Categoria F",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-93",
    categoria: "categoria_f",
    dificuldade: 1,
    pergunta: "Quanto é a diferença entre a taxa autónoma para arrendamento habitacional e não habitacional?",
    opcoes: [
      { texto: "5 pontos percentuais.", porque: "A diferença é de apenas 3 p.p. (28% - 25% = 3 p.p.)." },
      { texto: "3 pontos percentuais.", porque: "A taxa habitacional é 25% e a não habitacional é 28%, resultando numa diferença de 3 pontos percentuais." },
      { texto: "10 pontos percentuais.", porque: "10 p.p. é a redução por contrato de 5-10 anos, não a diferença entre taxas." },
      { texto: "Não há diferença.", porque: "Existe uma diferença: 25% (habitação) vs. 28% (não habitação) = 3 p.p." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — diferença entre taxas habitacional e não habitacional",
    fonte: fonte("art72"),
  },
  {
    id: "catf-94",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio arrenda um andar para habitação e a cave do mesmo prédio como armazém. Quantos anexos F deve preencher?",
    opcoes: [
      { texto: "Dois, um por cada contrato.", porque: "Preenche-se um único Anexo F, mas com linhas separadas para cada imóvel/contrato." },
      { texto: "Um, mas com linhas separadas para cada imóvel.", porque: "O Anexo F é único por declaração, mas cada imóvel arrendado é identificado numa linha própria." },
      { texto: "Nenhum, porque são no mesmo prédio.", porque: "Cada contrato de arrendamento deve ser declarado individualmente no Anexo F, mesmo no mesmo prédio." },
      { texto: "Depende do valor total das rendas.", porque: "O número de linhas no Anexo F depende do número de contratos/imóveis, não do valor." },
    ],
    correta: 1,
    legalBasis: "Instruções do Anexo F — declaração por imóvel",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-95",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "Um senhorio está no 2.º escalão de IRS (taxa marginal de 21%). Deve englobar as rendas habitacionais (taxa autónoma de 25%)?",
    opcoes: [
      { texto: "Não, 21% < 25% mas o englobamento obriga a englobar TODOS os rendimentos sujeitos a taxas especiais.", porque: "É verdade que o englobamento é global, mas se 21% < 25%, a poupança nas rendas pode compensar — a análise global é necessária." },
      { texto: "Sim, a taxa marginal de 21% é inferior à taxa autónoma de 25%, pelo que o englobamento pode ser vantajoso.", porque: "Com taxa marginal de 21% < 25% (autónoma), o englobamento pode ser vantajoso, mas deve considerar-se o impacto global (englobamento obrigatório de todos os rendimentos com taxas especiais)." },
      { texto: "Nunca, a tributação autónoma é sempre preferível.", porque: "Quando a taxa marginal é inferior à taxa autónoma, o englobamento pode reduzir o imposto total." },
      { texto: "Depende exclusivamente do concelho do imóvel.", porque: "A localização do imóvel não é relevante para esta decisão — o que importa é a comparação entre taxa marginal e taxa autónoma." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — englobamento vantajoso quando taxa marginal < taxa autónoma",
    fonte: fonte("art72"),
  },
  {
    id: "catf-96",
    categoria: "categoria_f",
    dificuldade: 2,
    pergunta: "As rendas recebidas por um usufruto de imóvel são tributadas na Categoria F?",
    opcoes: [
      { texto: "Não, o usufrutuário não é o proprietário.", porque: "As rendas obtidas pelo usufrutuário são rendimentos prediais da Categoria F (Art. 8.º CIRS), mesmo não sendo proprietário pleno." },
      { texto: "Sim, o usufrutuário declara as rendas na Categoria F.", porque: "O usufrutuário que arrende o imóvel obtém rendimentos prediais da Categoria F, declarando-os no Anexo F." },
      { texto: "As rendas são declaradas pelo proprietário de raiz.", porque: "É o usufrutuário (e não o proprietário de raiz) que declara as rendas, pois é ele quem as recebe." },
      { texto: "Depende se o usufruto está registado.", porque: "O registo do usufruto é uma questão civil — para efeitos fiscais, o usufrutuário declara as rendas que recebe." },
    ],
    correta: 1,
    legalBasis: "Art. 8.º CIRS — rendimentos prediais do usufrutuário",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-97",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio com contrato de 10 anos comunicado à AT (redução de 15 p.p.) e 5 renovações (máximo de -10 p.p.) tem uma taxa efetiva de:",
    opcoes: [
      { texto: "10%", porque: "A taxa base é 25% - 15 p.p. = 10%. Com 5 renovações x 2 p.p. = 10 p.p. (limite máximo). Taxa: 10% - 10% = 0%." },
      { texto: "5%", porque: "O cálculo correto é: 25% - 15 p.p. - 10 p.p. = 0%, não 5%." },
      { texto: "0%", porque: "Taxa base: 25%. Redução por duração (10-20 anos): -15 p.p. = 10%. Redução por renovações: 5 x 2 p.p. = 10 p.p. (teto atingido). Taxa: 10% - 10% = 0%." },
      { texto: "2%", porque: "O cálculo correto resulta em 0%, não 2%." },
    ],
    correta: 2,
    legalBasis: "Art. 72.º CIRS — taxa efetiva com reduções máximas cumuladas",
    fonte: fonte("art72"),
  },
  {
    id: "catf-98",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio celebra um contrato habitacional de 20 anos, comunicado à AT, e o imóvel está em zona de reabilitação urbana (ARU). Pode acumular benefícios?",
    opcoes: [
      { texto: "Não, os benefícios são mutuamente exclusivos.", porque: "Em princípio, os benefícios fiscais de ARU e as reduções por duração podem coexistir, mas com regras específicas de articulação." },
      { texto: "Sim, pode acumular a redução por duração com os benefícios de ARU.", porque: "Os benefícios fiscais de imóveis em ARU podem, em princípio, acumular-se com as reduções do Art. 72.º, desde que respeitadas as regras de articulação." },
      { texto: "Sim, e a taxa efetiva pode ser 0%.", porque: "Embora a acumulação seja possível, os limites e regras de articulação podem impedir uma taxa de 0%." },
      { texto: "Apenas se o imóvel tiver sido reabilitado nos últimos 3 anos.", porque: "O prazo de reabilitação pode ser relevante para os benefícios de ARU, mas não é condição para a acumulação em si." },
    ],
    correta: 1,
    legalBasis: "EBF e Art. 72.º CIRS — acumulação de benefícios (ARU + duração)",
    fonte: fonte("art72"),
  },
  {
    id: "catf-99",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Um senhorio que tenha 3 imóveis com resultados negativos na Categoria F pode reportar o prejuízo total ou deve fazê-lo por imóvel?",
    opcoes: [
      { texto: "O reporte é feito por imóvel, separadamente.", porque: "O resultado da Categoria F é calculado globalmente (todos os imóveis) — o reporte de prejuízos é sobre o total." },
      { texto: "O reporte é sobre o resultado global da Categoria F (todos os imóveis somados).", porque: "O resultado líquido da Categoria F é calculado globalmente — somam-se rendas e despesas de todos os imóveis, e o prejuízo total é reportável." },
      { texto: "Apenas o imóvel com maior prejuízo pode ser reportado.", porque: "Não há seleção por imóvel — o resultado é global e o prejuízo total pode ser reportado." },
      { texto: "O reporte não é permitido com mais de 2 imóveis.", porque: "Não existe limite de imóveis para o reporte de prejuízos da Categoria F." },
    ],
    correta: 1,
    legalBasis: "Art. 55.º CIRS — resultado global da Categoria F (reporte de prejuízos)",
    fonte: fonte("rendasPrediais"),
  },
  {
    id: "catf-100",
    categoria: "categoria_f",
    dificuldade: 3,
    pergunta: "Se o senhorio optar pelo englobamento num ano e não optar no seguinte, há alguma restrição?",
    opcoes: [
      { texto: "Sim, uma vez escolhido o englobamento, é obrigatório durante 3 anos.", porque: "A opção pelo englobamento é feita anualmente — o contribuinte pode escolher englobar ou não em cada declaração." },
      { texto: "Não, a opção pelo englobamento é feita anualmente, sem restrição de continuidade.", porque: "O contribuinte pode optar livremente pelo englobamento em cada ano fiscal, sem obrigação de manter a opção." },
      { texto: "Sim, é obrigatório durante 5 anos consecutivos.", porque: "Não existe obrigação de manter o englobamento durante vários anos — a opção é anual." },
      { texto: "A AT pode rejeitar a alternância frequente.", porque: "A alternância entre englobamento e tributação autónoma é um direito do contribuinte, exercido anualmente." },
    ],
    correta: 1,
    legalBasis: "Art. 72.º CIRS — opção anual pelo englobamento",
    fonte: fonte("art72"),
  },
];
