import type { LegalLocator, LegalSource } from "../core/model";

const reviewed = "2026-07-22" as const;
/** Levantamento patronal do relatório de 31 de agosto de 2026. */
const verifiedEmployer2026 = "2026-08-31" as const;

export const LEGAL_SOURCES = {
  cirs2: {
    id: "pt.at.cirs.2",
    authority: "AT",
    title: "CIRS — artigo 2.º, rendimentos da categoria A",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs2.aspx",
    effective: { from: "2025-01-01" },
    expectedAnchors: ["Artigo 2.º", "Rendimentos da categoria A", "subsídio de refeição"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs24: {
    id: "pt.at.cirs.24",
    authority: "AT",
    title: "CIRS — artigo 24.º, rendimentos em espécie",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs24.aspx",
    effective: { from: "2015-01-01" },
    expectedAnchors: ["Artigo 24.º", "Rendimentos em espécie", "0,75 %"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  oe2026: {
    id: "pt.dr.lei-73-a-2025",
    authority: "DR",
    title: "Lei n.º 73-A/2025 — Orçamento do Estado para 2026",
    url: "https://diariodarepublica.pt/dr/detalhe/lei/73-a-2025-993270096",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Lei n.º 73-A/2025", "Orçamento do Estado para 2026"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs12b: {
    id: "pt.at.cirs.12-b",
    authority: "AT",
    title: "CIRS — artigo 12.º-B, IRS Jovem",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs12b.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 12.º-B", "até 35 anos", "10 primeiros anos"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs31: {
    id: "pt.at.cirs.31",
    authority: "AT",
    title: "CIRS — artigo 31.º, regime simplificado",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs31.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 31.º", "Regime simplificado"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs68: {
    id: "pt.at.cirs.68",
    authority: "AT",
    title: "CIRS — artigo 68.º, taxas gerais",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs68.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 68.º", "Taxas gerais"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs68a: {
    id: "pt.at.cirs.68-a",
    authority: "AT",
    title: "CIRS — artigo 68.º-A, taxa adicional de solidariedade",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs68a.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 68.º-A", "Taxa adicional de solidariedade"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs70: {
    id: "pt.at.cirs.70",
    authority: "AT",
    title: "CIRS — artigo 70.º, mínimo de existência",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs70.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 70.º", "Mínimo de existência", "1,5 × 14 × IAS"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs81: {
    id: "pt.at.cirs.81",
    authority: "AT",
    title: "CIRS — artigo 81.º, dupla tributação jurídica internacional",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs81.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 81.º", "dupla tributação jurídica internacional"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs99c: {
    id: "pt.at.cirs.99-c",
    authority: "AT",
    title: "CIRS — artigo 99.º-C, retenção na fonte da categoria A",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs99c.aspx",
    effective: { from: "2025-01-01" },
    expectedAnchors: ["Artigo 99.º-C", "retenção autónoma", "trabalho suplementar"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cirs99f: {
    id: "pt.at.cirs.99-f",
    authority: "AT",
    title: "CIRS — artigo 99.º-F, tabelas de retenção e IRS Jovem",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs99f.aspx",
    effective: { from: "2025-01-01" },
    expectedAnchors: ["Artigo 99.º-F", "Tabelas de retenção na fonte", "rendimentos que não esteja isenta"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  withholding2026Mainland: {
    id: "pt.dr.despacho-233-a-2026",
    authority: "DR",
    title: "Despacho n.º 233-A/2026 — retenção na fonte 2026, Continente",
    url: "https://diariodarepublica.pt/dr/detalhe/despacho/233-a-2026-998488151",
    effective: { from: "2026-01-01", to: "2026-12-31" },
    expectedAnchors: ["Despacho n.º 233-A/2026", "trabalho suplementar", "três ou mais dependentes"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  labourCode: {
    id: "pt.dr.codigo-trabalho.current",
    authority: "DR",
    title: "Código do Trabalho — versão consolidada",
    url: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2009-34546475",
    effective: { from: "2009-02-17" },
    expectedAnchors: ["Código do Trabalho", "Artigo 268.º", "Artigo 271.º"],
    forbiddenAnchors: ["REVOGADO pelo/a Artigo 12.º do/a Lei n.º 7/2009"],
    lastHumanReview: reviewed,
    status: "active",
  },
  socialSecurityCode: {
    id: "pt.dr.codigo-contributivo.current",
    authority: "DR",
    title: "Código dos Regimes Contributivos — versão consolidada",
    url: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2009-34514575",
    effective: { from: "2011-01-01" },
    expectedAnchors: ["Delimitação da base de incidência contributiva", "Artigo 46.º", "Artigo 53.º"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  mealAllowance2026: {
    id: "pt.dr.portaria-51-b-2026",
    authority: "DR",
    title: "Portaria n.º 51-B/2026/1 — subsídio de refeição 2026",
    url: "https://diariodarepublica.pt/dr/detalhe/portaria/51-b-2026-1031110274",
    effective: { from: "2026-01-01", to: "2026-12-31" },
    expectedAnchors: ["Portaria n.º 51-B/2026/1", "6,15 €", "1 de janeiro de 2026"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  minimumWage2026: {
    id: "pt.dr.decreto-lei-139-2025",
    authority: "DR",
    title: "Decreto-Lei n.º 139/2025 — RMMG de 2026",
    url: "https://diariodarepublica.pt/dr/detalhe/decreto-lei/139-2025-992879809",
    effective: { from: "2026-01-01", to: "2026-12-31" },
    expectedAnchors: ["Decreto-Lei n.º 139/2025", "920", "1 de janeiro de 2026"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  civilProcedure738: {
    id: "pt.dr.cpc.738",
    authority: "DR",
    title: "Código de Processo Civil — artigo 738.º, penhora de rendimentos",
    url: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2013-34580575",
    effective: { from: "2013-09-01" },
    expectedAnchors: ["Artigo 738.º", "dois terços", "salário mínimo nacional"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  sicknessBenefit2026: {
    id: "pt.ss.guia-subsidio-doenca-2026",
    authority: "SEGURANCA_SOCIAL",
    title: "Segurança Social — Guia Prático do Subsídio de Doença 2026",
    url: "https://www.seg-social.pt/ptss/pssd/documento/cmdde8gsx000qi12yzi40plc6",
    effective: { from: "2026-01-01", to: "2026-12-31" },
    expectedAnchors: ["Subsídio de Doença", "remuneração de referência", "dias de espera"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  parentalBenefit2026: {
    id: "pt.ss.guia-parental-inicial-2026",
    authority: "SEGURANCA_SOCIAL",
    title: "Segurança Social — Guia Prático do Subsídio Parental Inicial 2026",
    url: "https://www.seg-social.pt/ptss/pssd/documento/cmc1ynbn400fskl2y5g278wvp",
    effective: { from: "2026-01-01", to: "2026-12-31" },
    expectedAnchors: ["Subsídio Parental Inicial", "remuneração de referência", "537,13"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  civa53: {
    id: "pt.at.civa.53",
    authority: "AT",
    title: "CIVA — artigo 53.º, regime especial de isenção",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/Pages/artigo-53-o-do-civa.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 53.º", "15 000"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  circ87: {
    id: "pt.at.circ.87.current",
    authority: "AT",
    title: "CIRC atual — artigo 87.º, taxas",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/CIRC_2R/Pages/irc87.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 87.º", "2026"],
    forbiddenAnchors: ["VERSÃO até 2013"],
    lastHumanReview: reviewed,
    status: "active",
  },
  circ88: {
    id: "pt.at.circ.88.current",
    authority: "AT",
    title: "CIRC atual — artigo 88.º, tributação autónoma",
    url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/CIRC_2R/Pages/irc88.aspx",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Artigo 88.º", "Taxas de tributação autónoma", "62 500"],
    forbiddenAnchors: ["VERSÃO até 2013"],
    lastHumanReview: reviewed,
    status: "active",
  },
  cfi: {
    id: "pt.dr.cfi.consolidated",
    authority: "DR",
    title: "Código Fiscal do Investimento",
    url: "https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-59423292",
    effective: { from: "2014-11-03" },
    expectedAnchors: ["Código Fiscal do Investimento", "Decreto-Lei n.º 162/2014"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  sifideAuthorisation2026: {
    id: "pt.dr.lei-13-2026",
    authority: "DR",
    title: "Lei n.º 13/2026 — autorização legislativa SIFIDE II",
    url: "https://diariodarepublica.pt/dr/detalhe/lei/13-2026-1086140529",
    effective: { from: "2026-04-17" },
    expectedAnchors: ["Lei n.º 13/2026", "autoriza o Governo", "SIFIDE II"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  socialSecurityIndependent: {
    id: "pt.ss.independent-workers",
    authority: "SEGURANCA_SOCIAL",
    title: "Segurança Social — trabalhadores independentes",
    url: "https://www.seg-social.pt/ptss/pssd/menu/trabalho/remuneracoes-contribuicoes/trabalhadores-independentes",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Trabalhadores independentes"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  cdtPortugalBrasil: {
    id: "pt.dr.cdt.portugal-brasil",
    authority: "DR",
    title: "Convenção Portugal–Brasil para evitar a dupla tributação",
    url: "https://diariodarepublica.pt/dr/detalhe/resolucao-assembleia-republica/33-2001-165237",
    effective: { from: "2001-04-27" },
    expectedAnchors: ["República Portuguesa", "República Federativa do Brasil", "dupla tributação"],
    forbiddenAnchors: [],
    lastHumanReview: reviewed,
    status: "active",
  },
  minimumWageMadeira2026: {
    id: "pt.dr.decreto-legislativo-regional-1-2026-m",
    authority: "JORAM",
    title: "Decreto Legislativo Regional n.º 1/2026/M — RMMG na Madeira",
    url: "https://diariodarepublica.pt/dr/detalhe/decreto-legislativo-regional/1-2026-1033291312",
    effective: { from: "2026-01-01", to: "2026-12-31" },
    expectedAnchors: ["1/2026/M", "980", "Região Autónoma da Madeira"],
    forbiddenAnchors: [],
    lastHumanReview: verifiedEmployer2026,
    status: "active",
  },
  minimumWageAzores: {
    id: "pt.dr.decreto-legislativo-regional-8-2002-a",
    authority: "JO_ACORES",
    title: "Decreto Legislativo Regional n.º 8/2002/A — acréscimo regional de 5%",
    url: "https://diariodarepublica.pt/dr/detalhe/decreto-legislativo-regional/8-2002-546201",
    effective: { from: "2002-03-01" },
    expectedAnchors: ["8/2002/A", "Região Autónoma dos Açores", "5 %"],
    forbiddenAnchors: [],
    lastHumanReview: verifiedEmployer2026,
    status: "active",
  },
  iefpMaisEmprego2026: {
    id: "pt.iefp.mais-emprego.2026",
    authority: "IEFP",
    title: "IEFP — Medida +Emprego, período de candidaturas de 2026",
    url: "https://iefponline.iefp.pt/IEFP/medida/mais-emprego.do?action=overview",
    effective: { from: "2026-07-15", to: "2026-12-15" },
    expectedAnchors: ["+Emprego", "15 de dezembro de 2026", "6.445,56"],
    forbiddenAnchors: [],
    lastHumanReview: verifiedEmployer2026,
    status: "active",
  },
  iefpEmpregoMaisTalento2026: {
    id: "pt.iefp.emprego-mais-talento.2026",
    authority: "IEFP",
    title: "IEFP — Medida Emprego +Talento, período de candidaturas de 2026",
    url: "https://iefponline.iefp.pt/IEFP/medida/emprego-mais-talento.do?action=overview",
    effective: { from: "2026-07-15", to: "2026-12-15" },
    expectedAnchors: ["+Talento", "15 de dezembro de 2026", "9.668,34"],
    forbiddenAnchors: [],
    lastHumanReview: verifiedEmployer2026,
    status: "active",
  },
  iefpApoiosContratacao: {
    id: "pt.iefp.apoios-a-contratacao",
    authority: "IEFP",
    title: "IEFP — catálogo de apoios à contratação",
    url: "https://www.iefp.pt/apoios-a-contratacao",
    effective: { from: "2026-01-01" },
    expectedAnchors: ["Apoios à contratação"],
    forbiddenAnchors: [],
    lastHumanReview: verifiedEmployer2026,
    status: "active",
  },
  workAccidentInsurance: {
    id: "pt.dr.lei-98-2009",
    authority: "DR",
    title: "Lei n.º 98/2009 — reparação de acidentes de trabalho",
    url: "https://diariodarepublica.pt/dr/detalhe/lei/98-2009-489505",
    effective: { from: "2010-01-01" },
    expectedAnchors: ["Lei n.º 98/2009", "Artigo 79.º", "seguro"],
    forbiddenAnchors: [],
    lastHumanReview: verifiedEmployer2026,
    status: "active",
  },
} as const satisfies Record<string, LegalSource>;

export type LegalSourceKey = keyof typeof LEGAL_SOURCES;

export const LEGAL_SOURCE_LIST: readonly LegalSource[] = Object.freeze(
  Object.values(LEGAL_SOURCES),
);

export function legalSourceById(id: string): LegalSource | undefined {
  return LEGAL_SOURCE_LIST.find((source) => source.id === id);
}

// ─── Localizadores ─────────────────────────────────────────────────────────

const ct = (article: string, label: string): LegalLocator => ({
  id: `pt.dr.codigo-trabalho.artigo-${article}`,
  sourceId: LEGAL_SOURCES.labourCode.id,
  article: `Artigo ${article}.º`,
  label,
});

/**
 * Cada citação do motor aponta para um artigo concreto de um diploma
 * concreto. Sem isto, «citations: [pt.dr.codigo-trabalho.current]» dizia
 * apenas que a regra vem de algum sítio de 400 artigos.
 */
export const LEGAL_LOCATORS: readonly LegalLocator[] = Object.freeze([
  ct("155", "Tempo parcial: proporcionalidade da retribuição"),
  ct("203", "Período normal de trabalho: 8 h diárias e 40 h semanais"),
  ct("204", "Adaptabilidade por regulamentação coletiva"),
  ct("205", "Adaptabilidade individual"),
  ct("207", "Período de referência"),
  ct("211", "Duração média do trabalho semanal: limite de 48 h"),
  ct("234", "Feriados obrigatórios"),
  ct("237", "Direito a férias"),
  ct("238", "Duração do período de férias: 22 dias úteis"),
  ct("239", "Férias no ano da admissão e no ano seguinte"),
  ct("263", "Subsídio de Natal"),
  ct("264", "Retribuição do período de férias e subsídio de férias"),
  ct("131", "Formação contínua: 40 horas anuais"),
  ct("132", "Crédito de horas: a formação não dada em dois anos converte-se"),
  ct("134", "Cessação do contrato: a formação por dar é paga em dinheiro"),
  ct("246", "Violação do direito a férias: compensação do triplo da retribuição"),
  {
    id: "pt.dr.lei-98-2009.artigo-79",
    sourceId: LEGAL_SOURCES.workAccidentInsurance.id,
    article: "Artigo 79.º",
    label: "Obrigação de transferir a responsabilidade para seguradora",
  },
  {
    id: "pt.dr.codigo-contributivo.artigo-46",
    sourceId: LEGAL_SOURCES.socialSecurityCode.id,
    article: "Artigo 46.º",
    label: "Delimitação da base de incidência contributiva",
  },
  {
    id: "pt.dr.codigo-contributivo.artigo-53",
    sourceId: LEGAL_SOURCES.socialSecurityCode.id,
    article: "Artigo 53.º",
    label: "Taxa contributiva do regime geral",
  },
]);

export function legalLocatorById(id: string): LegalLocator | undefined {
  return LEGAL_LOCATORS.find((locator) => locator.id === id);
}

/**
 * Resolve uma citação — fonte inteira ou localizador dentro dela. Uma citação
 * que não resolve é um erro de integridade, não um aviso de estilo.
 */
export function resolveCitation(
  id: string,
): { source: LegalSource; locator?: LegalLocator } | undefined {
  const direct = legalSourceById(id);
  if (direct) return { source: direct };
  const locator = legalLocatorById(id);
  if (!locator) return undefined;
  const source = legalSourceById(locator.sourceId);
  return source ? { source, locator } : undefined;
}
