// ═══════════════════════════════════════════════════════════════════════
//  CATÁLOGO DE FONTES DA EXPANSÃO EDITORIAL 2026
//  ---------------------------------------------------------------------
//  As fontes acrescentadas pelo pacote de expansão dos Guias (112 guias
//  novos). Vivem num módulo próprio — e não no meio de `legal-sources.ts` —
//  por duas razões:
//
//    1. PROVENIÊNCIA. As chaves são as do pacote ("CIMI-112", "CT", ...),
//       para que qualquer fonte no site seja rastreável até à entrada do
//       catálogo verificado. Os rótulos e as epígrafes foram EXTRAÍDOS do
//       texto publicado pela autoridade, não redigidos: copiam-se, não se
//       reescrevem.
//    2. VERIFICAÇÃO. Todas foram testadas por HTTP a 06/08/2026 e
//       devolveram 200. `lastCheckedAt` diz exatamente isso e mais nada.
//
//  As fontes cujo URL JÁ existia em `legal-sources.ts` não estão aqui: são
//  reutilizadas pela chave antiga (ver `RESOLUCAO_FONTES`). URL duplicado
//  falha `assertLegalSourcesIntegrity()` — e duas chaves para a mesma
//  página são duas coisas para manter em vez de uma.
//
//  Sobre `renderMode`: declara o que o monitor CONSEGUE validar no corpo da
//  resposta, não a tecnologia do servidor. Os artigos do Portal das
//  Finanças expõem "Artigo N.º" e são verificáveis; o Diário da República
//  serve um shell vazio; e as páginas de portal foram verificadas só quanto
//  a disponibilidade — nenhuma âncora foi extraída delas, e escrever uma de
//  memória é exatamente o que este projeto não faz.
// ═══════════════════════════════════════════════════════════════════════

import { FISCAL_YEAR } from "@/lib/fiscal-year";
import type { LegalSource, ComplementaryReading } from "../legal-sources";

/** Data em que o pacote de expansão testou todos os URL por HTTP. */
export const VERIFICADO_EXPANSAO = "2026-08-06";

const ANO = `${FISCAL_YEAR}-01-01`;

// ─── Fontes oficiais novas ─────────────────────────────────────────────

export const FONTES_EXPANSAO = {
  "AT-CDT": { id: "AT-CDT", authority: "AT", title: "Convenções para evitar a dupla tributação — lista e textos", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/convencoes_evitar_dupla_tributacao/Pages/default.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-CERT-RES": { id: "AT-CERT-RES", authority: "AT", title: "Certificados de residência fiscal — perguntas frequentes", url: "https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/questoes_frequentes/pages/faqs-00454.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-CIVA-PDF": { id: "AT-CIVA-PDF", authority: "AT", title: "Código do IVA — texto integral consolidado (PDF oficial)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/Cod_download/Documents/CIVA.pdf", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "pdf", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-COIMAS": { id: "AT-COIMAS", authority: "AT", title: "Dívidas e coimas — informação ao contribuinte", url: "https://info.portaldasfinancas.gov.pt/pt/apoio_ao_contribuinte/Dividas_e_coimas/Coimas/Paginas/default.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-DOACAO": { id: "AT-DOACAO", authority: "AT", title: "Doação — informação ao contribuinte", url: "https://info.portaldasfinancas.gov.pt/pt/apoio_ao_contribuinte/Cidadaos/Dados_pessoais_familia/Familia/Doacao/Paginas/default.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-ESTRANG": { id: "AT-ESTRANG", authority: "AT", title: "IRS — rendimentos obtidos no estrangeiro (FAQ)", url: "https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/questoes_frequentes/Pages/faqs-00653.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-MOD3": { id: "AT-MOD3", authority: "AT", title: "IRS — Declaração Modelo 3", url: "https://info.portaldasfinancas.gov.pt/pt/apoio_ao_contribuinte/Cidadaos/Rendimentos/Declaracao/Modelo_3/Paginas/default.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-PORTAL": { id: "AT-PORTAL", authority: "AT", title: "Portal das Finanças", url: "https://www.portaldasfinancas.gov.pt/at/html/index.html", jurisdiction: "PT", sourceType: "service", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "AT-RFI": { id: "AT-RFI", authority: "AT", title: "Formulários RFI — convenções para evitar a dupla tributação", url: "https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/modelos_formularios/convencoes_dupla_trib_internacional/Pages/default.aspx", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-112": { id: "CIMI-112", authority: "AT", title: "Art. 112.º CIMI — Taxas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi112.aspx", jurisdiction: "PT", sourceType: "code_article", article: "112.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 112.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-113": { id: "CIMI-113", authority: "AT", title: "Art. 113.º CIMI — Competência e prazo da liquidação", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi113.aspx", jurisdiction: "PT", sourceType: "code_article", article: "113.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 113.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-11A": { id: "CIMI-11A", authority: "AT", title: "Art. 11.º-A CIMI — Prédios de reduzido valor patrimonial de sujeitos passivos de baixos rendimentos", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi11a.aspx", jurisdiction: "PT", sourceType: "code_article", article: "11.º-A", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 11.º-A"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-120": { id: "CIMI-120", authority: "AT", title: "Art. 120.º CIMI — Prazo de pagamento", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi120.aspx", jurisdiction: "PT", sourceType: "code_article", article: "120.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 120.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-130": { id: "CIMI-130", authority: "AT", title: "Art. 130.º CIMI — Reclamação das matrizes", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi130.aspx", jurisdiction: "PT", sourceType: "code_article", article: "130.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 130.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-135A": { id: "CIMI-135A", authority: "AT", title: "Art. 135.º-A CIMI — Incidência subjetiva (AIMI)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135a.aspx", jurisdiction: "PT", sourceType: "code_article", article: "135.º-A", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 135.º-A"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-135B": { id: "CIMI-135B", authority: "AT", title: "Art. 135.º-B CIMI — Incidência objetiva (AIMI)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135b.aspx", jurisdiction: "PT", sourceType: "code_article", article: "135.º-B", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 135.º-B"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-135C": { id: "CIMI-135C", authority: "AT", title: "Art. 135.º-C CIMI — Regras de determinação do valor tributável (AIMI)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135c.aspx", jurisdiction: "PT", sourceType: "code_article", article: "135.º-C", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 135.º-C"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-135F": { id: "CIMI-135F", authority: "AT", title: "Art. 135.º-F CIMI — Taxa (AIMI)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135f.aspx", jurisdiction: "PT", sourceType: "code_article", article: "135.º-F", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 135.º-F"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-135G": { id: "CIMI-135G", authority: "AT", title: "Art. 135.º-G CIMI — Forma e prazo da liquidação (AIMI)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135g.aspx", jurisdiction: "PT", sourceType: "code_article", article: "135.º-G", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 135.º-G"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-135H": { id: "CIMI-135H", authority: "AT", title: "Art. 135.º-H CIMI — Pagamento (AIMI)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135h.aspx", jurisdiction: "PT", sourceType: "code_article", article: "135.º-H", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 135.º-H"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMI-38": { id: "CIMI-38", authority: "AT", title: "Art. 38.º CIMI — Determinação do valor patrimonial tributário", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi38.aspx", jurisdiction: "PT", sourceType: "code_article", article: "38.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 38.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMT-12": { id: "CIMT-12", authority: "AT", title: "Art. 12.º CIMT — Valor tributável", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimt/Pages/cimt12.aspx", jurisdiction: "PT", sourceType: "code_article", article: "12.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 12.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMT-17": { id: "CIMT-17", authority: "AT", title: "Art. 17.º CIMT — Taxas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimt/Pages/cimt17.aspx", jurisdiction: "PT", sourceType: "code_article", article: "17.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 17.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMT-19": { id: "CIMT-19", authority: "AT", title: "Art. 19.º CIMT — Iniciativa da liquidação", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimt/Pages/cimt19.aspx", jurisdiction: "PT", sourceType: "code_article", article: "19.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 19.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMT-36": { id: "CIMT-36", authority: "AT", title: "Art. 36.º CIMT — Prazos para pagamento", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimt/Pages/cimt36.aspx", jurisdiction: "PT", sourceType: "code_article", article: "36.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 36.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIMT-9": { id: "CIMT-9", authority: "AT", title: "Art. 9.º CIMT — Isenção pela aquisição de prédios destinados exclusivamente a habitação", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimt/Pages/cimt9.aspx", jurisdiction: "PT", sourceType: "code_article", article: "9.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 9.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRC-106": { id: "CIRC-106", authority: "AT", title: "Art. 106.º CIRC — Pagamento especial por conta", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/CIRC_2R/Pages/irc106.aspx", jurisdiction: "PT", sourceType: "code_article", article: "106.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 106.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRC-117": { id: "CIRC-117", authority: "AT", title: "Art. 117.º CIRC — Obrigações declarativas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/CIRC_2R/Pages/irc117.aspx", jurisdiction: "PT", sourceType: "code_article", article: "117.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 117.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-11": { id: "CIRS-11", authority: "AT", title: "Art. 11.º CIRS — Rendimentos da categoria H", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs11.aspx", jurisdiction: "PT", sourceType: "code_article", article: "11.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 11.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-112": { id: "CIRS-112", authority: "AT", title: "Art. 112.º CIRS — Declaração de início de atividade, de alterações e de cessação", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs112.aspx", jurisdiction: "PT", sourceType: "code_article", article: "112.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 112.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-119": { id: "CIRS-119", authority: "AT", title: "Art. 119.º CIRS — Comunicação de rendimentos e retenções", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs119.aspx", jurisdiction: "PT", sourceType: "code_article", article: "119.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 119.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-12": { id: "CIRS-12", authority: "AT", title: "Art. 12.º CIRS — Delimitação negativa de incidência", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs12.aspx", jurisdiction: "PT", sourceType: "code_article", article: "12.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 12.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-15": { id: "CIRS-15", authority: "AT", title: "Art. 15.º CIRS — Âmbito da sujeição", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs15.aspx", jurisdiction: "PT", sourceType: "code_article", article: "15.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 15.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-151": { id: "CIRS-151", authority: "AT", title: "Art. 151.º CIRS — Classificação das atividades", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs151.aspx", jurisdiction: "PT", sourceType: "code_article", article: "151.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 151.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-16": { id: "CIRS-16", authority: "AT", title: "Art. 16.º CIRS — Residência", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs16.aspx", jurisdiction: "PT", sourceType: "code_article", article: "16.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 16.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-20": { id: "CIRS-20", authority: "AT", title: "Art. 20.º CIRS — Imputação especial", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs20.aspx", jurisdiction: "PT", sourceType: "code_article", article: "20.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 20.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-22": { id: "CIRS-22", authority: "AT", title: "Art. 22.º CIRS — Englobamento", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs22.aspx", jurisdiction: "PT", sourceType: "code_article", article: "22.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 22.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-41": { id: "CIRS-41", authority: "AT", title: "Art. 41.º CIRS — Deduções", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs41.aspx", jurisdiction: "PT", sourceType: "code_article", article: "41.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 41.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-44": { id: "CIRS-44", authority: "AT", title: "Art. 44.º CIRS — Valor de realização", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs44.aspx", jurisdiction: "PT", sourceType: "code_article", article: "44.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 44.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-5": { id: "CIRS-5", authority: "AT", title: "Art. 5.º CIRS — Rendimentos da categoria E", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs5.aspx", jurisdiction: "PT", sourceType: "code_article", article: "5.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 5.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-51": { id: "CIRS-51", authority: "AT", title: "Art. 51.º CIRS — Despesas e encargos", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs51.aspx", jurisdiction: "PT", sourceType: "code_article", article: "51.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 51.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-53": { id: "CIRS-53", authority: "AT", title: "Art. 53.º CIRS — Pensões", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs53.aspx", jurisdiction: "PT", sourceType: "code_article", article: "53.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 53.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-55": { id: "CIRS-55", authority: "AT", title: "Art. 55.º CIRS — Dedução de perdas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs55.aspx", jurisdiction: "PT", sourceType: "code_article", article: "55.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 55.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-57": { id: "CIRS-57", authority: "AT", title: "Art. 57.º CIRS — Declaração de rendimentos", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs57.aspx", jurisdiction: "PT", sourceType: "code_article", article: "57.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 57.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-8": { id: "CIRS-8", authority: "AT", title: "Art. 8.º CIRS — Rendimentos da categoria F", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs8.aspx", jurisdiction: "PT", sourceType: "code_article", article: "8.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 8.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-81": { id: "CIRS-81", authority: "AT", title: "Art. 81.º CIRS — Eliminação da dupla tributação jurídica internacional", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs81.aspx", jurisdiction: "PT", sourceType: "code_article", article: "81.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 81.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-83A": { id: "CIRS-83A", authority: "AT", title: "Art. 83.º-A CIRS — Importâncias respeitantes a pensões de alimentos", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs83a.aspx", jurisdiction: "PT", sourceType: "code_article", article: "83.º-A", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 83.º-A"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-9": { id: "CIRS-9", authority: "AT", title: "Art. 9.º CIRS — Rendimentos da categoria G", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs9.aspx", jurisdiction: "PT", sourceType: "code_article", article: "9.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 9.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIRS-99": { id: "CIRS-99", authority: "AT", title: "Art. 99.º CIRS — Retenção sobre rendimentos das categorias A e H", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs99.aspx", jurisdiction: "PT", sourceType: "code_article", article: "99.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 99.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-1": { id: "CIS-1", authority: "AT", title: "Art. 1.º CIS — Incidência objectiva", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo1.aspx", jurisdiction: "PT", sourceType: "code_article", article: "1.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 1.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-2": { id: "CIS-2", authority: "AT", title: "Art. 2.º CIS — Incidência subjectiva", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo2.aspx", jurisdiction: "PT", sourceType: "code_article", article: "2.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 2.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-23": { id: "CIS-23", authority: "AT", title: "Art. 23.º CIS — Competência para a liquidação", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo23.aspx", jurisdiction: "PT", sourceType: "code_article", article: "23.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 23.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-26": { id: "CIS-26", authority: "AT", title: "Art. 26.º CIS — Participação da transmissão de bens", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo26.aspx", jurisdiction: "PT", sourceType: "code_article", article: "26.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 26.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-28": { id: "CIS-28", authority: "AT", title: "Art. 28.º CIS — Obrigação de prestar declarações e relacionar os bens", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo28.aspx", jurisdiction: "PT", sourceType: "code_article", article: "28.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 28.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-44": { id: "CIS-44", authority: "AT", title: "Art. 44.º CIS — Prazo e local de pagamento", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo44.aspx", jurisdiction: "PT", sourceType: "code_article", article: "44.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 44.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-6": { id: "CIS-6", authority: "AT", title: "Art. 6.º CIS — Isenções subjectivas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo6.aspx", jurisdiction: "PT", sourceType: "code_article", article: "6.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 6.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-63": { id: "CIS-63", authority: "AT", title: "Art. 63.º CIS — Obrigações de fiscalização", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo63.aspx", jurisdiction: "PT", sourceType: "code_article", article: "63.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 63.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIS-9": { id: "CIS-9", authority: "AT", title: "Art. 9.º CIS — Valor tributável", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/selo/Pages/selo9.aspx", jurisdiction: "PT", sourceType: "code_article", article: "9.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 9.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-1": { id: "CIVA-1", authority: "AT", title: "Art. 1.º CIVA — Incidência objectiva", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva1.aspx", jurisdiction: "PT", sourceType: "code_article", article: "1.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 1.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-18": { id: "CIVA-18", authority: "AT", title: "Art. 18.º CIVA — Taxas do imposto", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva18.aspx", jurisdiction: "PT", sourceType: "code_article", article: "18.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 18.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-27": { id: "CIVA-27", authority: "AT", title: "Art. 27.º CIVA — Pagamento do imposto apurado pelo sujeito passivo", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva27.aspx", jurisdiction: "PT", sourceType: "code_article", article: "27.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 27.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-29": { id: "CIVA-29", authority: "AT", title: "Art. 29.º CIVA — Obrigações em geral", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva29.aspx", jurisdiction: "PT", sourceType: "code_article", article: "29.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 29.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-30": { id: "CIVA-30", authority: "AT", title: "Art. 30.º CIVA — Representante fiscal", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva30.aspx", jurisdiction: "PT", sourceType: "code_article", article: "30.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 30.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-32": { id: "CIVA-32", authority: "AT", title: "Art. 32.º CIVA — Declaração de alterações", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva32.aspx", jurisdiction: "PT", sourceType: "code_article", article: "32.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 32.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-33": { id: "CIVA-33", authority: "AT", title: "Art. 33.º CIVA — Declaração de cessação de actividade", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva33.aspx", jurisdiction: "PT", sourceType: "code_article", article: "33.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 33.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-36": { id: "CIVA-36", authority: "AT", title: "Art. 36.º CIVA — Prazo de emissão e formalidades das faturas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva36.aspx", jurisdiction: "PT", sourceType: "code_article", article: "36.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 36.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-41": { id: "CIVA-41", authority: "AT", title: "Art. 41.º CIVA — Prazo de entrega da declaração periódica", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva41.aspx", jurisdiction: "PT", sourceType: "code_article", article: "41.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 41.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-44": { id: "CIVA-44", authority: "AT", title: "Art. 44.º CIVA — Requisitos da contabilidade", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva44.aspx", jurisdiction: "PT", sourceType: "code_article", article: "44.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 44.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-53": { id: "CIVA-53", authority: "AT", title: "Art. 53.º CIVA — Âmbito de aplicação no território nacional", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva53.aspx", jurisdiction: "PT", sourceType: "code_article", article: "53.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 53.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-54": { id: "CIVA-54", authority: "AT", title: "Art. 54.º CIVA — Passagem dos regimes de tributação ao regime especial de isenção", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva54.aspx", jurisdiction: "PT", sourceType: "code_article", article: "54.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 54.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-55": { id: "CIVA-55", authority: "AT", title: "Art. 55.º CIVA — Opção pelo regime de tributação", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva55.aspx", jurisdiction: "PT", sourceType: "code_article", article: "55.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 55.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-58": { id: "CIVA-58", authority: "AT", title: "Art. 58.º CIVA — Cessação do regime de isenção e período em que passa a ser devido o imposto", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva58.aspx", jurisdiction: "PT", sourceType: "code_article", article: "58.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 58.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-6": { id: "CIVA-6", authority: "AT", title: "Art. 6.º CIVA — Localização das operações", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva6.aspx", jurisdiction: "PT", sourceType: "code_article", article: "6.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 6.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-78": { id: "CIVA-78", authority: "AT", title: "Art. 78.º CIVA — Regularizações", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva78.aspx", jurisdiction: "PT", sourceType: "code_article", article: "78.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 78.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CIVA-9": { id: "CIVA-9", authority: "AT", title: "Art. 9.º CIVA — Isenções nas operações internas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa/Pages/iva9.aspx", jurisdiction: "PT", sourceType: "code_article", article: "9.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 9.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CPPT-189": { id: "CPPT-189", authority: "AT", title: "Art. 189.º CPPT — Efeitos e função das citações", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cppt/Pages/cppt189.aspx", jurisdiction: "PT", sourceType: "code_article", article: "189.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 189.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CPPT-68": { id: "CPPT-68", authority: "AT", title: "Art. 68.º CPPT — Procedimento de reclamação graciosa", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cppt/Pages/cppt68.aspx", jurisdiction: "PT", sourceType: "code_article", article: "68.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 68.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "CPPT-78": { id: "CPPT-78", authority: "AT", title: "Art. 78.º CPPT — Modalidades da cobrança", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cppt/Pages/cppt78.aspx", jurisdiction: "PT", sourceType: "code_article", article: "78.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 78.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "EBF-21": { id: "EBF-21", authority: "AT", title: "Art. 21.º EBF — Produtos individuais de reforma", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/bf_rep/Pages/ebf-artigo-21-ordm-.aspx", jurisdiction: "PT", sourceType: "code_article", article: "21.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 21.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "EBF-43": { id: "EBF-43", authority: "AT", title: "Art. 43.º EBF — Benefícios fiscais relativos à interioridade", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/bf_rep/Pages/ebf-artigo-43-ordm-.aspx", jurisdiction: "PT", sourceType: "code_article", article: "43.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 43.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "EBF-43D": { id: "EBF-43D", authority: "AT", title: "Art. 43.º-D EBF — Incentivo fiscal à capitalização das empresas (ICE)", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/bf_rep/Pages/ebf43d.aspx", jurisdiction: "PT", sourceType: "code_article", article: "43.º-D", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 43.º-D"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "EBF-58": { id: "EBF-58", authority: "AT", title: "Art. 58.º EBF — Propriedade intelectual", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/bf_rep/Pages/ebf-artigo-58-ordm-.aspx", jurisdiction: "PT", sourceType: "code_article", article: "58.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 58.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "LGT-19": { id: "LGT-19", authority: "AT", title: "Art. 19.º LGT — Domicílio fiscal", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/lgt/Pages/lgt19.aspx", jurisdiction: "PT", sourceType: "code_article", article: "19.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 19.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "LGT-22": { id: "LGT-22", authority: "AT", title: "Art. 22.º LGT — Responsabilidade tributária", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/lgt/Pages/lgt22.aspx", jurisdiction: "PT", sourceType: "code_article", article: "22.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 22.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "LGT-59": { id: "LGT-59", authority: "AT", title: "Art. 59.º LGT — Princípio da colaboração", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/lgt/Pages/lgt59.aspx", jurisdiction: "PT", sourceType: "code_article", article: "59.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 59.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "LGT-63": { id: "LGT-63", authority: "AT", title: "Art. 63.º LGT — Inspecção", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/lgt/Pages/lgt63.aspx", jurisdiction: "PT", sourceType: "code_article", article: "63.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 63.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "LGT-78": { id: "LGT-78", authority: "AT", title: "Art. 78.º LGT — Revisão dos actos tributários", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/lgt/Pages/lgt78.aspx", jurisdiction: "PT", sourceType: "code_article", article: "78.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 78.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "RGIT-114": { id: "RGIT-114", authority: "AT", title: "Art. 114.º RGIT — Falta de entrega da prestação tributária", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/rgit/Pages/rgit114.aspx", jurisdiction: "PT", sourceType: "code_article", article: "114.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 114.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "RGIT-116": { id: "RGIT-116", authority: "AT", title: "Art. 116.º RGIT — Falta ou atraso de declarações", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/rgit/Pages/rgit116.aspx", jurisdiction: "PT", sourceType: "code_article", article: "116.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 116.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "RGIT-117": { id: "RGIT-117", authority: "AT", title: "Art. 117.º RGIT — Falta ou atraso na apresentação ou exibição de documentos ou de declarações e de comunicações", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/rgit/Pages/rgit117.aspx", jurisdiction: "PT", sourceType: "code_article", article: "117.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 117.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "RGIT-119": { id: "RGIT-119", authority: "AT", title: "Art. 119.º RGIT — Omissões e inexactidões nas declarações ou em outros documentos fiscalmente relevantes", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/rgit/Pages/rgit119.aspx", jurisdiction: "PT", sourceType: "code_article", article: "119.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 119.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "RGIT-29": { id: "RGIT-29", authority: "AT", title: "Art. 29.º RGIT — Dispensa das coimas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/rgit/Pages/rgit29.aspx", jurisdiction: "PT", sourceType: "code_article", article: "29.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 29.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "RGIT-30": { id: "RGIT-30", authority: "AT", title: "Art. 30.º RGIT — Direito à redução das coimas", url: "https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/rgit/Pages/rgit30.aspx", jurisdiction: "PT", sourceType: "code_article", article: "30.º", effectiveFrom: ANO, consolidada: true, renderMode: "html", expectedAnchors: ["Artigo 30.º"], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  CIRE: { id: "CIRE", authority: "DR", title: "Código da Insolvência e da Recuperação de Empresas (Decreto-Lei n.º 53/2004, de 18 de março)", url: "https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2004-34529075", jurisdiction: "PT", sourceType: "law", effectiveFrom: ANO, consolidada: true, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  CRC: { id: "CRC", authority: "DR", title: "Código dos Regimes Contributivos do Sistema Previdencial de Segurança Social (Lei n.º 110/2009, de 16 de setembro)", url: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2009-34514575", jurisdiction: "PT", sourceType: "law", effectiveFrom: ANO, consolidada: true, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  DL128: { id: "DL128", authority: "DR", title: "Regime jurídico da exploração dos estabelecimentos de alojamento local (Decreto-Lei n.º 128/2014, de 29 de agosto)", url: "https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-56917875", jurisdiction: "PT", sourceType: "law", effectiveFrom: ANO, consolidada: true, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  DL28: { id: "DL28", authority: "DR", title: "Obrigações de faturação e conservação de documentos (Decreto-Lei n.º 28/2019, de 15 de fevereiro)", url: "https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2019-119662485", jurisdiction: "PT", sourceType: "law", effectiveFrom: ANO, consolidada: true, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  L21: { id: "L21", authority: "DR", title: "Regime aplicável às startups e scaleups (Lei n.º 21/2023, de 25 de maio)", url: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2023-213498858", jurisdiction: "PT", sourceType: "law", effectiveFrom: ANO, consolidada: true, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  L98: { id: "L98", authority: "DR", title: "Regime de reparação de acidentes de trabalho e de doenças profissionais (Lei n.º 98/2009, de 4 de setembro)", url: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2009-58661980", jurisdiction: "PT", sourceType: "law", effectiveFrom: ANO, consolidada: true, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  EPORTUGAL: { id: "EPORTUGAL", authority: "GOV", title: "ePortugal — serviços públicos", url: "https://eportugal.gov.pt/", jurisdiction: "PT", sourceType: "service", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "GOV-IMI": { id: "GOV-IMI", authority: "GOV", title: "Pagar o Imposto Municipal sobre Imóveis (IMI)", url: "https://www.gov.pt/servicos/pagar-o-imposto-municipal-sobre-imoveis-imi-", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "GOV-PARENT": { id: "GOV-PARENT", authority: "GOV", title: "Pedir o subsídio parental", url: "https://www2.gov.pt/servicos/requerer-o-subsidio-inicial", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "GOV-SS-TRIM": { id: "GOV-SS-TRIM", authority: "GOV", title: "Declaração trimestral para a Segurança Social", url: "https://www2.gov.pt/-/texto-declara%C3%A7%C3%A3o-trimestral-para-a-seguran%C3%A7a-social", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "IEFP-APOIOS": { id: "IEFP-APOIOS", authority: "OTHER_OFFICIAL", title: "Apoios à contratação", url: "https://www.iefp.pt/apoios-a-contratacao", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "SS-PARENT": { id: "SS-PARENT", authority: "SS", title: "Parentalidade — Segurança Social", url: "https://www.seg-social.pt/parentalidade", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
  "SS-TI-GUIA": { id: "SS-TI-GUIA", authority: "SS", title: "Guia prático — Regime dos trabalhadores independentes", url: "https://www.seg-social.pt/documents/10152/13326/Regime+dos+trabalhadores+independentes", jurisdiction: "PT", sourceType: "official_guide", effectiveFrom: ANO, renderMode: "spa", expectedAnchors: [], lastCheckedAt: VERIFICADO_EXPANSAO, status: "active" },
} as const satisfies Record<string, LegalSource>;

// ─── Leitura complementar nova ─────────────────────────────────────────
//  Explicam, não fundamentam. O bloco que as mostra leva sempre a frase
//  fixa: «Publicações de terceiros que ajudam a compreender o tema. Não
//  são fonte de direito.»

export const LEITURAS_EXPANSAO = {
  "DECO-ACOES": { id: "DECO-ACOES", publisher: "DECO PROTeste Investe", title: "Como declarar ações no IRS", url: "https://www.deco.proteste.pt/investe/investimentos/impostos/dossie/fiscalidade-acoes/como-declarar-acoes-irs", lastCheckedAt: VERIFICADO_EXPANSAO },
  "DECO-EFAT": { id: "DECO-EFAT", publisher: "DECO PROTeste", title: "Despesas no e-Fatura: recuperar deduções após o prazo", url: "https://www.deco.proteste.pt/dinheiro/impostos/noticias/despesas-efatura-recuperar-deducoes-irs-apos-prazo", lastCheckedAt: VERIFICADO_EXPANSAO },
  "DECO-INSOLV": { id: "DECO-INSOLV", publisher: "DECO", title: "Insolvência: exoneração do passivo restante", url: "https://deco.pt/explorar/insolvencia-exoneracao-do-passivo-restante/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "DF-CAL26": { id: "DF-CAL26", publisher: "Doutor Finanças", title: "Calendário fiscal de 2026", url: "https://www.doutorfinancas.pt/impostos/calendario-fiscal-de-2026-as-datas-que-nao-pode-mesmo-falhar/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "DF-CRIADOR": { id: "DF-CRIADOR", publisher: "Doutor Finanças", title: "Criadores de conteúdo e IRS: como declarar rendimentos", url: "https://www.doutorfinancas.pt/impostos/irs/criadores-de-conteudo-e-irs-como-declarar-rendimentos/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "ECO-INFLU": { id: "ECO-INFLU", publisher: "ECO", title: "É influencer e recebe produtos de marcas? Tem de declarar no IRS", url: "https://eco.sapo.pt/2026/06/28/e-influencer-e-recebe-produtos-de-marcas-tem-de-declarar-no-irs/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "IDEALISTA-IMI": { id: "IDEALISTA-IMI", publisher: "idealista/news", title: "Calendário do IMI 2026", url: "https://www.idealista.pt/news/financas/fiscalidade/2026/02/20/73971-calendario-do-imi-2026-tudo-o-que-precisas-de-saber", lastCheckedAt: VERIFICADO_EXPANSAO },
  "IX-FAT26": { id: "IX-FAT26", publisher: "InvoiceXpress", title: "Regras de faturação e contabilidade que mudam em 2026", url: "https://invoicexpress.com/blog/regras-faturacao-contabilidade-2026/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "MV-OE": { id: "MV-OE", publisher: "Macedo Vitorino", title: "Orçamento do Estado 2026 — Medidas Fiscais", url: "https://www.macedovitorino.com/conhecimento/insights/Orcamento-do-Estado-2026-Medidas-Fiscais/6862/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "OCC-AL": { id: "OCC-AL", publisher: "OCC", title: "IRS — rendimentos de alojamento local", url: "https://www.occ.pt/noticias/irs-rendimentos-de-alojamento-local-nao-residentes/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "OCC-FATURA": { id: "OCC-FATURA", publisher: "OCC", title: "IVA — erros na faturação", url: "https://www.occ.pt/pt-pt/noticias/iva-erros-na-faturacao", lastCheckedAt: VERIFICADO_EXPANSAO },
  "OCC-RFI": { id: "OCC-RFI", publisher: "OCC", title: "Formulário 21-RFI", url: "https://www.occ.pt/pt-pt/noticias/formulario-21-rfi", lastCheckedAt: VERIFICADO_EXPANSAO },
  "OCC-TI-SS": { id: "OCC-TI-SS", publisher: "OCC", title: "Trabalhador independente — Segurança Social", url: "https://occ.pt/pt-pt/noticias/trabalhador-independente-seguranca-social-0", lastCheckedAt: VERIFICADO_EXPANSAO },
  "OE-GOV": { id: "OE-GOV", publisher: "Governo de Portugal — oe.gov.pt", title: "Principais novidades fiscais em 2026", url: "https://www.oe.gov.pt/noticias/sabe-quais-sao-as-principais-novidades-fiscais-em-2026/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "PWC-IMT": { id: "PWC-IMT", publisher: "PwC", title: "Guia Fiscal 2026 — IMT", url: "https://www.pwc.pt/pt/pwcinforfisco/guia-fiscal/2026/imt.html", lastCheckedAt: VERIFICADO_EXPANSAO },
  "PWC-OE": { id: "PWC-OE", publisher: "PwC", title: "Orçamento do Estado — alterações fiscais", url: "https://www.pwc.pt/pt/pwcinforfisco/orcamentoestado.html", lastCheckedAt: VERIFICADO_EXPANSAO },
  "SAGE-SSTRIM": { id: "SAGE-SSTRIM", publisher: "Sage", title: "Como fazer a declaração trimestral à Segurança Social", url: "https://www.sage.com/pt-pt/blog/como-fazer-a-declaracao-trimestral-seguranca-social/", lastCheckedAt: VERIFICADO_EXPANSAO },
  "SANT-IRS": { id: "SANT-IRS", publisher: "Santander", title: "Prazos IRS 2026 — calendário completo", url: "https://www.santander.pt/salto/prazos-irs-2026", lastCheckedAt: VERIFICADO_EXPANSAO },
  "SP-AL": { id: "SP-AL", publisher: "CGD Saldo Positivo", title: "Alojamento local e obrigações fiscais", url: "https://www.cgd.pt/Site/Saldo-Positivo/leis-e-impostos/Pages/alojamento-local-obrigacoes-fiscais.aspx", lastCheckedAt: VERIFICADO_EXPANSAO },
  "SP-CRIPTO": { id: "SP-CRIPTO", publisher: "CGD Saldo Positivo", title: "Declarar criptomoedas em Portugal: como preencher o IRS?", url: "https://www.cgd.pt/Site/Saldo-Positivo/leis-e-impostos/Pages/declarar-criptomoedas-irs-portugal.aspx", lastCheckedAt: VERIFICADO_EXPANSAO },
  "SP-SEGURO": { id: "SP-SEGURO", publisher: "CGD Saldo Positivo", title: "Seguro do trabalhador independente: para quem é obrigatório", url: "https://www.cgd.pt/Site/Saldo-Positivo/trabalho/Pages/seguro-trabalhador-independente.aspx", lastCheckedAt: VERIFICADO_EXPANSAO },
  "SUP-STARTUP": { id: "SUP-STARTUP", publisher: "Startup Portugal", title: "Novo regime de stock options para startups", url: "https://startupportugal.com/pt/legal-bites-01-novo-regime-de-stock-options-para-startups/", lastCheckedAt: VERIFICADO_EXPANSAO },
} as const satisfies Record<string, ComplementaryReading>;
