// ═══════════════════════════════════════════════════════════════════════
//  CAPACIDADES — a ponte entre o que a pessoa tem e o que consegue atacar
//  ---------------------------------------------------------------------
//  Sem esta camada, o motor teria de ligar «logística» diretamente a
//  «entregas B2B» e perdia a razão pela qual a ligação existe: ter
//  carrinha, carta e disponibilidade de rota. É aqui que a carrinha do
//  exemplo do pedido deixa de ser decoração e passa a mudar o resultado.
//
//  `ativosNecessarios` é uma exigência DURA: sem o ativo, a capacidade não
//  existe e todos os problemas que dependem só dela desaparecem. É por
//  isto que «não tenho carro» elimina rotas em vez de as penalizar.
// ═══════════════════════════════════════════════════════════════════════
import type { Capacidade } from "../tipos";

export const CAPACIDADES: readonly Capacidade[] = Object.freeze([
  {
    id: "rota-recolha-entrega",
    rotulo: "Fazer rotas de recolha e entrega",
    descricao: "Passar por vários pontos no mesmo dia com um horário que se cumpre.",
    competenciasNecessarias: ["logistica"],
    competenciasUteis: ["organizacao", "atendimento"],
    ativosNecessarios: ["carta-conducao"],
    ativosUteis: ["veiculo-ligeiro", "veiculo-carga"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "transporte-carga",
    rotulo: "Transportar volume e carga",
    descricao: "Mover coisas pesadas ou volumosas entre sítios, com meios próprios.",
    competenciasNecessarias: ["logistica"],
    competenciasUteis: ["organizacao"],
    ativosNecessarios: ["veiculo-carga", "carta-conducao"],
    ativosUteis: ["armazem"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "operar-no-local",
    rotulo: "Operar em casa ou instalações do cliente",
    descricao: "Trabalho presencial no espaço de outra pessoa, com chave e confiança.",
    competenciasNecessarias: ["organizacao"],
    competenciasUteis: ["limpeza", "atendimento"],
    ativosNecessarios: [],
    ativosUteis: ["veiculo-ligeiro", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "limpar-e-repor",
    rotulo: "Limpar, repor e preparar espaços",
    descricao: "Deixar um espaço pronto a usar, com padrão constante e prazo curto.",
    competenciasNecessarias: ["limpeza"],
    competenciasUteis: ["organizacao", "logistica"],
    ativosNecessarios: [],
    ativosUteis: ["veiculo-ligeiro", "ferramentas"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "organizar-processos",
    rotulo: "Organizar processos e informação",
    descricao: "Pôr pedidos, prazos, documentos e respostas num sistema que se aguenta.",
    competenciasNecessarias: ["organizacao"],
    competenciasUteis: ["dados", "escrita", "burocracia"],
    ativosNecessarios: ["computador"],
    ativosUteis: [],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "montar-ferramentas-digitais",
    rotulo: "Montar e manter ferramentas digitais",
    descricao: "Escolher, configurar e ensinar software a quem o vai usar todos os dias.",
    competenciasNecessarias: ["informatica"],
    competenciasUteis: ["organizacao", "ensinar", "dados"],
    ativosNecessarios: ["computador"],
    ativosUteis: [],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "tratar-dados",
    rotulo: "Limpar, cruzar e migrar dados",
    descricao: "Pegar em informação desarrumada e entregá-la utilizável, com o que ficou de fora listado.",
    competenciasNecessarias: ["dados"],
    competenciasUteis: ["programacao", "organizacao"],
    ativosNecessarios: ["computador"],
    ativosUteis: [],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "construir-software",
    rotulo: "Construir e manter software",
    descricao: "Escrever, publicar e continuar a manter aquilo que se escreveu.",
    competenciasNecessarias: ["programacao"],
    competenciasUteis: ["design", "dados"],
    ativosNecessarios: ["computador"],
    ativosUteis: [],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "instalar-configurar",
    rotulo: "Instalar e configurar equipamento",
    descricao: "Pôr equipamento a funcionar em casa ou empresa de outra pessoa, e explicá-lo.",
    competenciasNecessarias: ["informatica"],
    competenciasUteis: ["tecnica-equipamento", "ensinar", "eletrica"],
    ativosNecessarios: ["ferramentas"],
    ativosUteis: ["veiculo-ligeiro", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "reparar-equipamento",
    rotulo: "Diagnosticar e reparar equipamento",
    descricao: "Perceber o que avariou, dizer se compensa reparar, e reparar.",
    competenciasNecessarias: ["tecnica-equipamento"],
    competenciasUteis: ["informatica", "organizacao"],
    ativosNecessarios: ["ferramentas", "equipamento-tecnico"],
    ativosUteis: ["oficina"],
    esforcoFisico: false,
    presencial: true,
  },
  {
    id: "intervencao-eletrica",
    rotulo: "Intervir em instalações elétricas",
    descricao: "Trabalho elétrico com habilitação e responsabilidade técnica declarada.",
    competenciasNecessarias: ["eletrica"],
    competenciasUteis: ["tecnica-equipamento", "coordenacao"],
    ativosNecessarios: ["ferramentas", "equipamento-tecnico"],
    ativosUteis: ["veiculo-carga", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "executar-obra",
    rotulo: "Executar obra e acabamentos",
    descricao: "Trabalho de construção, remodelação ou acabamento feito por si.",
    competenciasNecessarias: ["construcao"],
    competenciasUteis: ["coordenacao", "eletrica"],
    ativosNecessarios: ["ferramentas"],
    ativosUteis: ["veiculo-carga", "armazem", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "coordenar-fornecedores",
    rotulo: "Coordenar fornecedores e calendários",
    descricao: "Pôr várias empresas a cumprir o mesmo prazo sem o cliente ter de as perseguir.",
    competenciasNecessarias: ["coordenacao"],
    competenciasUteis: ["organizacao", "vendas", "construcao"],
    ativosNecessarios: [],
    ativosUteis: ["veiculo-ligeiro", "carteira-clientes", "carta-conducao"],
    esforcoFisico: false,
    presencial: true,
  },
  {
    id: "acompanhar-pessoas",
    rotulo: "Acompanhar pessoas",
    descricao: "Estar presente com regularidade para quem precisa de apoio, com limites escritos.",
    competenciasNecessarias: ["cuidar"],
    competenciasUteis: ["organizacao", "ensinar", "informatica"],
    ativosNecessarios: [],
    ativosUteis: ["veiculo-ligeiro", "carta-conducao"],
    esforcoFisico: false,
    presencial: true,
  },
  {
    id: "ensinar-e-treinar",
    rotulo: "Ensinar e treinar",
    descricao: "Levar alguém de não sabe a sabe, com programa e com prova disso.",
    competenciasNecessarias: ["ensinar"],
    competenciasUteis: ["escrita", "linguas", "design"],
    ativosNecessarios: [],
    ativosUteis: ["computador", "camara-video"],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "cuidar-animais",
    rotulo: "Cuidar de animais",
    descricao: "Acompanhar animais de outras pessoas com rotina e responsabilidade.",
    competenciasNecessarias: ["animais"],
    competenciasUteis: ["organizacao", "cuidar"],
    ativosNecessarios: [],
    ativosUteis: ["veiculo-ligeiro", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "produzir-alimentos",
    rotulo: "Produzir alimentos com regularidade",
    descricao: "Produção repetível, com regras de segurança alimentar e rótulo conforme.",
    competenciasNecessarias: ["cozinha"],
    competenciasUteis: ["organizacao", "vendas"],
    ativosNecessarios: ["cozinha-licenciada"],
    ativosUteis: ["veiculo-ligeiro", "stock", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "trabalhar-terreno",
    rotulo: "Trabalhar e manter terreno",
    descricao: "Cultivo, limpeza e manutenção de terreno, próprio ou de terceiros.",
    competenciasNecessarias: ["agricultura"],
    competenciasUteis: ["logistica", "vendas"],
    ativosNecessarios: ["ferramentas"],
    ativosUteis: ["terreno", "veiculo-carga", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "receber-e-guiar",
    rotulo: "Receber e guiar visitantes",
    descricao: "Estar à frente de pessoas que não conhecem o sítio e fazer valer a pena.",
    competenciasNecessarias: ["atendimento"],
    competenciasUteis: ["linguas", "cuidar", "vendas"],
    ativosNecessarios: [],
    ativosUteis: ["veiculo-ligeiro", "carta-conducao"],
    esforcoFisico: true,
    presencial: true,
  },
  {
    id: "vender-para-empresas",
    rotulo: "Vender a empresas",
    descricao: "Chegar a quem decide numa empresa e conduzir uma venda que demora semanas.",
    competenciasNecessarias: ["vendas"],
    competenciasUteis: ["escrita", "gestao", "linguas"],
    ativosNecessarios: [],
    ativosUteis: ["carteira-clientes", "computador"],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "produzir-conteudo",
    rotulo: "Produzir conteúdo e imagem",
    descricao: "Fotografia, vídeo e texto com ritmo de publicação que não se esgota.",
    competenciasNecessarias: ["design"],
    competenciasUteis: ["escrita", "vendas"],
    ativosNecessarios: ["computador"],
    ativosUteis: ["camara-video"],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "escrever-para-vender",
    rotulo: "Escrever para vender",
    descricao: "Textos comerciais, propostas e páginas que convertem sem prometer o que não há.",
    competenciasNecessarias: ["escrita"],
    competenciasUteis: ["vendas", "design"],
    ativosNecessarios: ["computador"],
    ativosUteis: [],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "tratar-requisitos-formais",
    rotulo: "Tratar requisitos formais e prazos",
    descricao: "Ler peças, cruzar requisitos, montar dossiers e não perder datas.",
    competenciasNecessarias: ["burocracia"],
    competenciasUteis: ["organizacao", "escrita", "dados"],
    ativosNecessarios: ["computador"],
    ativosUteis: [],
    esforcoFisico: false,
    presencial: false,
  },
  {
    id: "gerir-operacao",
    rotulo: "Gerir uma operação com equipa",
    descricao: "Escalas, substituições, custo real do trabalho e alguém que aparece ao sábado.",
    competenciasNecessarias: ["gestao"],
    competenciasUteis: ["coordenacao", "vendas", "cuidar"],
    ativosNecessarios: [],
    ativosUteis: ["computador"],
    esforcoFisico: false,
    presencial: true,
  },
  {
    id: "atender-balcao",
    rotulo: "Atender e vender ao público",
    descricao: "Estar à frente de clientes finais, com stock e horário.",
    competenciasNecessarias: ["atendimento"],
    competenciasUteis: ["vendas", "linguas"],
    ativosNecessarios: [],
    ativosUteis: ["espaco-comercial", "stock"],
    esforcoFisico: true,
    presencial: true,
  },
] as const);

export const CAPACIDADE_POR_ID = new Map(CAPACIDADES.map((item) => [item.id, item]));
