// ═══════════════════════════════════════════════════════════════════════
//  OS 308 CONCELHOS — GERADO, NÃO ESCRITO
//  ---------------------------------------------------------------------
//  ⚠️ Não editar à mão. `node scripts/gen-concelhos.mjs` reescreve este
//  ficheiro a partir da metainformação do INE, e `--check` falha o build
//  se ele divergir da fonte.
//
//  ── PORQUE O CONCELHO E NÃO A NUTS II ──────────────────────────────
//  «Que negócio abrir» varia ao concelho. Em NUTS II, Lisboa e Mafra são
//  a mesma célula, e Idanha-a-Nova e Coimbra também — o que faz a leitura
//  de oferta descrever um território que não é o de ninguém. Os dois
//  indicadores que o motor usa publicam aos 308 concelhos; era só a
//  ferramenta que pedia menos.
//
//  ── PORQUE A LISTA É FECHADA, E ISSO É PRIVACIDADE ─────────────────
//  Uma lista fechada de 308 entradas escolhe-se no cliente e chega para
//  decidir onde testar. Não recolhe morada, código postal nem GPS, e a
//  escolha nunca sai do dispositivo — é a regra 8 das fronteiras, e é
//  anterior à barreira de PII.
//
//  ── O CÓDIGO É QUE MANDA, NÃO O DISTRITO ───────────────────────────
//  O código territorial do INE é hierárquico e os primeiros caracteres
//  SÃO a NUTS II. Distritos atravessam regiões — Sines e Grândola são
//  Alentejo apesar de Setúbal, Torres Vedras é Oeste apesar de Lisboa,
//  Alcobaça e Peniche são Oeste apesar de Leiria — e o prefixo resolve
//  todos sem uma exceção escrita.
//
//  Concelhos por região:
//  · acores: 19
//  · alentejo: 47
//  · algarve: 16
//  · centro: 77
//  · grande-lisboa: 9
//  · madeira: 11
//  · norte: 86
//  · oeste-vale-tejo: 34
//  · peninsula-setubal: 9
//
//  Fonte: INE, metainformação dos indicadores 0014449 e 0012918
//  (dimensão «Localização geográfica (NUTS - 2024)», nível 5).
//  Gerado em 2026-08-23.
// ═══════════════════════════════════════════════════════════════════════

import type { MarketRegion } from "./geografia";

export interface Concelho {
  /** Código territorial do INE, sete caracteres. É a chave nos dois indicadores. */
  codigo: string;
  nome: string;
  /** Derivada do prefixo do código, nunca do distrito. */
  regiao: MarketRegion;
}

/** Os 308, por ordem alfabética portuguesa. */
export const CONCELHOS: readonly Concelho[] = Object.freeze([
  { codigo: "1D21401", nome: "Abrantes", regiao: "oeste-vale-tejo" },
  { codigo: "1910101", nome: "Águeda", regiao: "centro" },
  { codigo: "1940901", nome: "Aguiar da Beira", regiao: "centro" },
  { codigo: "1C40701", nome: "Alandroal", regiao: "alentejo" },
  { codigo: "1910102", nome: "Albergaria-a-Velha", regiao: "centro" },
  { codigo: "1500801", nome: "Albufeira", regiao: "algarve" },
  { codigo: "1C11501", nome: "Alcácer do Sal", regiao: "alentejo" },
  { codigo: "1D21402", nome: "Alcanena", regiao: "oeste-vale-tejo" },
  { codigo: "1D11001", nome: "Alcobaça", regiao: "oeste-vale-tejo" },
  { codigo: "1B01502", nome: "Alcochete", regiao: "peninsula-setubal" },
  { codigo: "1500802", nome: "Alcoutim", regiao: "algarve" },
  { codigo: "1D11101", nome: "Alenquer", regiao: "oeste-vale-tejo" },
  { codigo: "11E0401", nome: "Alfândega da Fé", regiao: "norte" },
  { codigo: "11D1701", nome: "Alijó", regiao: "norte" },
  { codigo: "1500803", nome: "Aljezur", regiao: "algarve" },
  { codigo: "1C20201", nome: "Aljustrel", regiao: "alentejo" },
  { codigo: "1B01503", nome: "Almada", regiao: "peninsula-setubal" },
  { codigo: "1960902", nome: "Almeida", regiao: "centro" },
  { codigo: "1D31403", nome: "Almeirim", regiao: "oeste-vale-tejo" },
  { codigo: "1C20202", nome: "Almodôvar", regiao: "alentejo" },
  { codigo: "1D31404", nome: "Alpiarça", regiao: "oeste-vale-tejo" },
  { codigo: "1C31201", nome: "Alter do Chão", regiao: "alentejo" },
  { codigo: "1931002", nome: "Alvaiázere", regiao: "centro" },
  { codigo: "1C20203", nome: "Alvito", regiao: "alentejo" },
  { codigo: "1A01115", nome: "Amadora", regiao: "grande-lisboa" },
  { codigo: "11C1301", nome: "Amarante", regiao: "norte" },
  { codigo: "1120301", nome: "Amares", regiao: "norte" },
  { codigo: "1910103", nome: "Anadia", regiao: "centro" },
  { codigo: "2004301", nome: "Angra do Heroísmo", regiao: "acores" },
  { codigo: "1931003", nome: "Ansião", regiao: "centro" },
  { codigo: "1111601", nome: "Arcos de Valdevez", regiao: "norte" },
  { codigo: "1920601", nome: "Arganil", regiao: "centro" },
  { codigo: "11D1801", nome: "Armamar", regiao: "norte" },
  { codigo: "11A0104", nome: "Arouca", regiao: "norte" },
  { codigo: "1C40702", nome: "Arraiolos", regiao: "alentejo" },
  { codigo: "1C31202", nome: "Arronches", regiao: "alentejo" },
  { codigo: "1D11102", nome: "Arruda dos Vinhos", regiao: "oeste-vale-tejo" },
  { codigo: "1910105", nome: "Aveiro", regiao: "centro" },
  { codigo: "1C31203", nome: "Avis", regiao: "alentejo" },
  { codigo: "1D31103", nome: "Azambuja", regiao: "oeste-vale-tejo" },
  { codigo: "11C1302", nome: "Baião", regiao: "norte" },
  { codigo: "1120302", nome: "Barcelos", regiao: "norte" },
  { codigo: "1C20204", nome: "Barrancos", regiao: "alentejo" },
  { codigo: "1B01504", nome: "Barreiro", regiao: "peninsula-setubal" },
  { codigo: "1931004", nome: "Batalha", regiao: "centro" },
  { codigo: "1C20205", nome: "Beja", regiao: "alentejo" },
  { codigo: "1960501", nome: "Belmonte", regiao: "centro" },
  { codigo: "1D31405", nome: "Benavente", regiao: "oeste-vale-tejo" },
  { codigo: "1D11005", nome: "Bombarral", regiao: "oeste-vale-tejo" },
  { codigo: "1C40703", nome: "Borba", regiao: "alentejo" },
  { codigo: "11B1702", nome: "Boticas", regiao: "norte" },
  { codigo: "1120303", nome: "Braga", regiao: "norte" },
  { codigo: "11E0402", nome: "Bragança", regiao: "norte" },
  { codigo: "1190304", nome: "Cabeceiras de Basto", regiao: "norte" },
  { codigo: "1D11104", nome: "Cadaval", regiao: "oeste-vale-tejo" },
  { codigo: "1D11006", nome: "Caldas da Rainha", regiao: "oeste-vale-tejo" },
  { codigo: "2004501", nome: "Calheta (R.A.A.)", regiao: "acores" },
  { codigo: "3003101", nome: "Calheta (R.A.M.)", regiao: "madeira" },
  { codigo: "3003102", nome: "Câmara de Lobos", regiao: "madeira" },
  { codigo: "1111602", nome: "Caminha", regiao: "norte" },
  { codigo: "1C31204", nome: "Campo Maior", regiao: "alentejo" },
  { codigo: "1920602", nome: "Cantanhede", regiao: "centro" },
  { codigo: "11D0403", nome: "Carrazeda de Ansiães", regiao: "norte" },
  { codigo: "1941802", nome: "Carregal do Sal", regiao: "centro" },
  { codigo: "1D31406", nome: "Cartaxo", regiao: "oeste-vale-tejo" },
  { codigo: "1A01105", nome: "Cascais", regiao: "grande-lisboa" },
  { codigo: "1931007", nome: "Castanheira de Pêra", regiao: "centro" },
  { codigo: "1950502", nome: "Castelo Branco", regiao: "centro" },
  { codigo: "11C0106", nome: "Castelo de Paiva", regiao: "norte" },
  { codigo: "1C31205", nome: "Castelo de Vide", regiao: "alentejo" },
  { codigo: "1941803", nome: "Castro Daire", regiao: "centro" },
  { codigo: "1500804", nome: "Castro Marim", regiao: "algarve" },
  { codigo: "1C20206", nome: "Castro Verde", regiao: "alentejo" },
  { codigo: "1960903", nome: "Celorico da Beira", regiao: "centro" },
  { codigo: "11C0305", nome: "Celorico de Basto", regiao: "norte" },
  { codigo: "1D31407", nome: "Chamusca", regiao: "oeste-vale-tejo" },
  { codigo: "11B1703", nome: "Chaves", regiao: "norte" },
  { codigo: "11C1804", nome: "Cinfães", regiao: "norte" },
  { codigo: "1920603", nome: "Coimbra", regiao: "centro" },
  { codigo: "1920604", nome: "Condeixa-a-Nova", regiao: "centro" },
  { codigo: "1D21408", nome: "Constância", regiao: "oeste-vale-tejo" },
  { codigo: "1D31409", nome: "Coruche", regiao: "oeste-vale-tejo" },
  { codigo: "2004901", nome: "Corvo", regiao: "acores" },
  { codigo: "1960503", nome: "Covilhã", regiao: "centro" },
  { codigo: "1C31206", nome: "Crato", regiao: "alentejo" },
  { codigo: "1C20207", nome: "Cuba", regiao: "alentejo" },
  { codigo: "1C31207", nome: "Elvas", regiao: "alentejo" },
  { codigo: "1D21410", nome: "Entroncamento", regiao: "oeste-vale-tejo" },
  { codigo: "11A0107", nome: "Espinho", regiao: "norte" },
  { codigo: "1120306", nome: "Esposende", regiao: "norte" },
  { codigo: "1910108", nome: "Estarreja", regiao: "centro" },
  { codigo: "1C40704", nome: "Estremoz", regiao: "alentejo" },
  { codigo: "1C40705", nome: "Évora", regiao: "alentejo" },
  { codigo: "1190307", nome: "Fafe", regiao: "norte" },
  { codigo: "1500805", nome: "Faro", regiao: "algarve" },
  { codigo: "11C1303", nome: "Felgueiras", regiao: "norte" },
  { codigo: "1C20208", nome: "Ferreira do Alentejo", regiao: "alentejo" },
  { codigo: "1D21411", nome: "Ferreira do Zêzere", regiao: "oeste-vale-tejo" },
  { codigo: "1920605", nome: "Figueira da Foz", regiao: "centro" },
  { codigo: "1960904", nome: "Figueira de Castelo Rodrigo", regiao: "centro" },
  { codigo: "1931008", nome: "Figueiró dos Vinhos", regiao: "centro" },
  { codigo: "1960905", nome: "Fornos de Algodres", regiao: "centro" },
  { codigo: "11D0404", nome: "Freixo de Espada à Cinta", regiao: "norte" },
  { codigo: "1C31208", nome: "Fronteira", regiao: "alentejo" },
  { codigo: "3003103", nome: "Funchal", regiao: "madeira" },
  { codigo: "1960504", nome: "Fundão", regiao: "centro" },
  { codigo: "1C31209", nome: "Gavião", regiao: "alentejo" },
  { codigo: "1920606", nome: "Góis", regiao: "centro" },
  { codigo: "1D31412", nome: "Golegã", regiao: "oeste-vale-tejo" },
  { codigo: "11A1304", nome: "Gondomar", regiao: "norte" },
  { codigo: "1960906", nome: "Gouveia", regiao: "centro" },
  { codigo: "1C11505", nome: "Grândola", regiao: "alentejo" },
  { codigo: "1960907", nome: "Guarda", regiao: "centro" },
  { codigo: "1190308", nome: "Guimarães", regiao: "norte" },
  { codigo: "2004701", nome: "Horta", regiao: "acores" },
  { codigo: "1950505", nome: "Idanha-a-Nova", regiao: "centro" },
  { codigo: "1910110", nome: "Ílhavo", regiao: "centro" },
  { codigo: "1500806", nome: "Lagoa", regiao: "algarve" },
  { codigo: "2004201", nome: "Lagoa (R.A.A.)", regiao: "acores" },
  { codigo: "1500807", nome: "Lagos", regiao: "algarve" },
  { codigo: "2004801", nome: "Lajes das Flores", regiao: "acores" },
  { codigo: "2004601", nome: "Lajes do Pico", regiao: "acores" },
  { codigo: "11D1805", nome: "Lamego", regiao: "norte" },
  { codigo: "1931009", nome: "Leiria", regiao: "centro" },
  { codigo: "1A01106", nome: "Lisboa", regiao: "grande-lisboa" },
  { codigo: "1500808", nome: "Loulé", regiao: "algarve" },
  { codigo: "1A01107", nome: "Loures", regiao: "grande-lisboa" },
  { codigo: "1D11108", nome: "Lourinhã", regiao: "oeste-vale-tejo" },
  { codigo: "1920607", nome: "Lousã", regiao: "centro" },
  { codigo: "11C1305", nome: "Lousada", regiao: "norte" },
  { codigo: "1D21413", nome: "Mação", regiao: "oeste-vale-tejo" },
  { codigo: "11E0405", nome: "Macedo de Cavaleiros", regiao: "norte" },
  { codigo: "3003104", nome: "Machico", regiao: "madeira" },
  { codigo: "2004602", nome: "Madalena", regiao: "acores" },
  { codigo: "1A01109", nome: "Mafra", regiao: "grande-lisboa" },
  { codigo: "11A1306", nome: "Maia", regiao: "norte" },
  { codigo: "1941806", nome: "Mangualde", regiao: "centro" },
  { codigo: "1960908", nome: "Manteigas", regiao: "centro" },
  { codigo: "11C1307", nome: "Marco de Canaveses", regiao: "norte" },
  { codigo: "1931010", nome: "Marinha Grande", regiao: "centro" },
  { codigo: "1C31210", nome: "Marvão", regiao: "alentejo" },
  { codigo: "11A1308", nome: "Matosinhos", regiao: "norte" },
  { codigo: "1920111", nome: "Mealhada", regiao: "centro" },
  { codigo: "1960909", nome: "Mêda", regiao: "centro" },
  { codigo: "1111603", nome: "Melgaço", regiao: "norte" },
  { codigo: "1C20209", nome: "Mértola", regiao: "alentejo" },
  { codigo: "11D1704", nome: "Mesão Frio", regiao: "norte" },
  { codigo: "1920608", nome: "Mira", regiao: "centro" },
  { codigo: "1920609", nome: "Miranda do Corvo", regiao: "centro" },
  { codigo: "11E0406", nome: "Miranda do Douro", regiao: "norte" },
  { codigo: "11E0407", nome: "Mirandela", regiao: "norte" },
  { codigo: "11E0408", nome: "Mogadouro", regiao: "norte" },
  { codigo: "11D1807", nome: "Moimenta da Beira", regiao: "norte" },
  { codigo: "1B01506", nome: "Moita", regiao: "peninsula-setubal" },
  { codigo: "1111604", nome: "Monção", regiao: "norte" },
  { codigo: "1500809", nome: "Monchique", regiao: "algarve" },
  { codigo: "1191705", nome: "Mondim de Basto", regiao: "norte" },
  { codigo: "1C31211", nome: "Monforte", regiao: "alentejo" },
  { codigo: "11B1706", nome: "Montalegre", regiao: "norte" },
  { codigo: "1C40706", nome: "Montemor-o-Novo", regiao: "alentejo" },
  { codigo: "1920610", nome: "Montemor-o-Velho", regiao: "centro" },
  { codigo: "1B01507", nome: "Montijo", regiao: "peninsula-setubal" },
  { codigo: "1C40707", nome: "Mora", regiao: "alentejo" },
  { codigo: "1921808", nome: "Mortágua", regiao: "centro" },
  { codigo: "1C20210", nome: "Moura", regiao: "alentejo" },
  { codigo: "1C40708", nome: "Mourão", regiao: "alentejo" },
  { codigo: "11D1707", nome: "Murça", regiao: "norte" },
  { codigo: "1910112", nome: "Murtosa", regiao: "centro" },
  { codigo: "1D11011", nome: "Nazaré", regiao: "oeste-vale-tejo" },
  { codigo: "1941809", nome: "Nelas", regiao: "centro" },
  { codigo: "1C31212", nome: "Nisa", regiao: "alentejo" },
  { codigo: "2004202", nome: "Nordeste", regiao: "acores" },
  { codigo: "1D11012", nome: "Óbidos", regiao: "oeste-vale-tejo" },
  { codigo: "1C10211", nome: "Odemira", regiao: "alentejo" },
  { codigo: "1A01116", nome: "Odivelas", regiao: "grande-lisboa" },
  { codigo: "1A01110", nome: "Oeiras", regiao: "grande-lisboa" },
  { codigo: "1950506", nome: "Oleiros", regiao: "centro" },
  { codigo: "1500810", nome: "Olhão", regiao: "algarve" },
  { codigo: "11A0113", nome: "Oliveira de Azeméis", regiao: "norte" },
  { codigo: "1941810", nome: "Oliveira de Frades", regiao: "centro" },
  { codigo: "1910114", nome: "Oliveira do Bairro", regiao: "centro" },
  { codigo: "1920611", nome: "Oliveira do Hospital", regiao: "centro" },
  { codigo: "1D21421", nome: "Ourém", regiao: "oeste-vale-tejo" },
  { codigo: "1C20212", nome: "Ourique", regiao: "alentejo" },
  { codigo: "1910115", nome: "Ovar", regiao: "centro" },
  { codigo: "11C1309", nome: "Paços de Ferreira", regiao: "norte" },
  { codigo: "1B01508", nome: "Palmela", regiao: "peninsula-setubal" },
  { codigo: "1920612", nome: "Pampilhosa da Serra", regiao: "centro" },
  { codigo: "11A1310", nome: "Paredes", regiao: "norte" },
  { codigo: "1111605", nome: "Paredes de Coura", regiao: "norte" },
  { codigo: "1931013", nome: "Pedrógão Grande", regiao: "centro" },
  { codigo: "1920613", nome: "Penacova", regiao: "centro" },
  { codigo: "11C1311", nome: "Penafiel", regiao: "norte" },
  { codigo: "1941811", nome: "Penalva do Castelo", regiao: "centro" },
  { codigo: "1950507", nome: "Penamacor", regiao: "centro" },
  { codigo: "11D1812", nome: "Penedono", regiao: "norte" },
  { codigo: "1920614", nome: "Penela", regiao: "centro" },
  { codigo: "1D11014", nome: "Peniche", regiao: "oeste-vale-tejo" },
  { codigo: "11D1708", nome: "Peso da Régua", regiao: "norte" },
  { codigo: "1960910", nome: "Pinhel", regiao: "centro" },
  { codigo: "1931015", nome: "Pombal", regiao: "centro" },
  { codigo: "2004203", nome: "Ponta Delgada", regiao: "acores" },
  { codigo: "3003105", nome: "Ponta do Sol", regiao: "madeira" },
  { codigo: "1111606", nome: "Ponte da Barca", regiao: "norte" },
  { codigo: "1111607", nome: "Ponte de Lima", regiao: "norte" },
  { codigo: "1C31213", nome: "Ponte de Sor", regiao: "alentejo" },
  { codigo: "1C31214", nome: "Portalegre", regiao: "alentejo" },
  { codigo: "1C40709", nome: "Portel", regiao: "alentejo" },
  { codigo: "1500811", nome: "Portimão", regiao: "algarve" },
  { codigo: "11A1312", nome: "Porto", regiao: "norte" },
  { codigo: "1931016", nome: "Porto de Mós", regiao: "centro" },
  { codigo: "3003106", nome: "Porto Moniz", regiao: "madeira" },
  { codigo: "3003201", nome: "Porto Santo", regiao: "madeira" },
  { codigo: "1190309", nome: "Póvoa de Lanhoso", regiao: "norte" },
  { codigo: "11A1313", nome: "Póvoa de Varzim", regiao: "norte" },
  { codigo: "2004204", nome: "Povoação", regiao: "acores" },
  { codigo: "1950508", nome: "Proença-a-Nova", regiao: "centro" },
  { codigo: "1C40710", nome: "Redondo", regiao: "alentejo" },
  { codigo: "1C40711", nome: "Reguengos de Monsaraz", regiao: "alentejo" },
  { codigo: "11C1813", nome: "Resende", regiao: "norte" },
  { codigo: "3003107", nome: "Ribeira Brava", regiao: "madeira" },
  { codigo: "11B1709", nome: "Ribeira de Pena", regiao: "norte" },
  { codigo: "2004205", nome: "Ribeira Grande", regiao: "acores" },
  { codigo: "1D31414", nome: "Rio Maior", regiao: "oeste-vale-tejo" },
  { codigo: "11D1710", nome: "Sabrosa", regiao: "norte" },
  { codigo: "1960911", nome: "Sabugal", regiao: "centro" },
  { codigo: "1D31415", nome: "Salvaterra de Magos", regiao: "oeste-vale-tejo" },
  { codigo: "1941814", nome: "Santa Comba Dão", regiao: "centro" },
  { codigo: "3003108", nome: "Santa Cruz", regiao: "madeira" },
  { codigo: "2004401", nome: "Santa Cruz da Graciosa", regiao: "acores" },
  { codigo: "2004802", nome: "Santa Cruz das Flores", regiao: "acores" },
  { codigo: "11A0109", nome: "Santa Maria da Feira", regiao: "norte" },
  { codigo: "11D1711", nome: "Santa Marta de Penaguião", regiao: "norte" },
  { codigo: "3003109", nome: "Santana", regiao: "madeira" },
  { codigo: "1D31416", nome: "Santarém", regiao: "oeste-vale-tejo" },
  { codigo: "1C11509", nome: "Santiago do Cacém", regiao: "alentejo" },
  { codigo: "11A1314", nome: "Santo Tirso", regiao: "norte" },
  { codigo: "1500812", nome: "São Brás de Alportel", regiao: "algarve" },
  { codigo: "11A0116", nome: "São João da Madeira", regiao: "norte" },
  { codigo: "11D1815", nome: "São João da Pesqueira", regiao: "norte" },
  { codigo: "1941816", nome: "São Pedro do Sul", regiao: "centro" },
  { codigo: "2004603", nome: "São Roque do Pico", regiao: "acores" },
  { codigo: "3003110", nome: "São Vicente", regiao: "madeira" },
  { codigo: "1D21417", nome: "Sardoal", regiao: "oeste-vale-tejo" },
  { codigo: "1941817", nome: "Sátão", regiao: "centro" },
  { codigo: "1960912", nome: "Seia", regiao: "centro" },
  { codigo: "1B01510", nome: "Seixal", regiao: "peninsula-setubal" },
  { codigo: "11D1818", nome: "Sernancelhe", regiao: "norte" },
  { codigo: "1C20213", nome: "Serpa", regiao: "alentejo" },
  { codigo: "1950509", nome: "Sertã", regiao: "centro" },
  { codigo: "1B01511", nome: "Sesimbra", regiao: "peninsula-setubal" },
  { codigo: "1B01512", nome: "Setúbal", regiao: "peninsula-setubal" },
  { codigo: "1910117", nome: "Sever do Vouga", regiao: "centro" },
  { codigo: "1500813", nome: "Silves", regiao: "algarve" },
  { codigo: "1C11513", nome: "Sines", regiao: "alentejo" },
  { codigo: "1A01111", nome: "Sintra", regiao: "grande-lisboa" },
  { codigo: "1D11112", nome: "Sobral de Monte Agraço", regiao: "oeste-vale-tejo" },
  { codigo: "1920615", nome: "Soure", regiao: "centro" },
  { codigo: "1C31215", nome: "Sousel", regiao: "alentejo" },
  { codigo: "1920616", nome: "Tábua", regiao: "centro" },
  { codigo: "11D1819", nome: "Tabuaço", regiao: "norte" },
  { codigo: "11D1820", nome: "Tarouca", regiao: "norte" },
  { codigo: "1500814", nome: "Tavira", regiao: "algarve" },
  { codigo: "1120310", nome: "Terras de Bouro", regiao: "norte" },
  { codigo: "1D21418", nome: "Tomar", regiao: "oeste-vale-tejo" },
  { codigo: "1941821", nome: "Tondela", regiao: "centro" },
  { codigo: "11D0409", nome: "Torre de Moncorvo", regiao: "norte" },
  { codigo: "1D21419", nome: "Torres Novas", regiao: "oeste-vale-tejo" },
  { codigo: "1D11113", nome: "Torres Vedras", regiao: "oeste-vale-tejo" },
  { codigo: "1960913", nome: "Trancoso", regiao: "centro" },
  { codigo: "11A1318", nome: "Trofa", regiao: "norte" },
  { codigo: "1910118", nome: "Vagos", regiao: "centro" },
  { codigo: "11A0119", nome: "Vale de Cambra", regiao: "norte" },
  { codigo: "1111608", nome: "Valença", regiao: "norte" },
  { codigo: "11A1315", nome: "Valongo", regiao: "norte" },
  { codigo: "11B1712", nome: "Valpaços", regiao: "norte" },
  { codigo: "2004502", nome: "Velas", regiao: "acores" },
  { codigo: "1C40712", nome: "Vendas Novas", regiao: "alentejo" },
  { codigo: "1C40713", nome: "Viana do Alentejo", regiao: "alentejo" },
  { codigo: "1111609", nome: "Viana do Castelo", regiao: "norte" },
  { codigo: "1C20214", nome: "Vidigueira", regiao: "alentejo" },
  { codigo: "1190311", nome: "Vieira do Minho", regiao: "norte" },
  { codigo: "2004302", nome: "Vila da Praia da Vitória", regiao: "acores" },
  { codigo: "1950510", nome: "Vila de Rei", regiao: "centro" },
  { codigo: "1500815", nome: "Vila do Bispo", regiao: "algarve" },
  { codigo: "11A1316", nome: "Vila do Conde", regiao: "norte" },
  { codigo: "2004101", nome: "Vila do Porto", regiao: "acores" },
  { codigo: "11E0410", nome: "Vila Flor", regiao: "norte" },
  { codigo: "1A01114", nome: "Vila Franca de Xira", regiao: "grande-lisboa" },
  { codigo: "2004206", nome: "Vila Franca do Campo", regiao: "acores" },
  { codigo: "1D21420", nome: "Vila Nova da Barquinha", regiao: "oeste-vale-tejo" },
  { codigo: "1111610", nome: "Vila Nova de Cerveira", regiao: "norte" },
  { codigo: "1190312", nome: "Vila Nova de Famalicão", regiao: "norte" },
  { codigo: "11D0914", nome: "Vila Nova de Foz Côa", regiao: "norte" },
  { codigo: "11A1317", nome: "Vila Nova de Gaia", regiao: "norte" },
  { codigo: "1941822", nome: "Vila Nova de Paiva", regiao: "centro" },
  { codigo: "1920617", nome: "Vila Nova de Poiares", regiao: "centro" },
  { codigo: "11B1713", nome: "Vila Pouca de Aguiar", regiao: "norte" },
  { codigo: "11D1714", nome: "Vila Real", regiao: "norte" },
  { codigo: "1500816", nome: "Vila Real de Santo António", regiao: "algarve" },
  { codigo: "1950511", nome: "Vila Velha de Ródão", regiao: "centro" },
  { codigo: "1120313", nome: "Vila Verde", regiao: "norte" },
  { codigo: "1C40714", nome: "Vila Viçosa", regiao: "alentejo" },
  { codigo: "11E0411", nome: "Vimioso", regiao: "norte" },
  { codigo: "11E0412", nome: "Vinhais", regiao: "norte" },
  { codigo: "1941823", nome: "Viseu", regiao: "centro" },
  { codigo: "1190314", nome: "Vizela", regiao: "norte" },
  { codigo: "1941824", nome: "Vouzela", regiao: "centro" },
] as const);

export const CONCELHO_POR_CODIGO: ReadonlyMap<string, Concelho> = new Map(
  CONCELHOS.map((item) => [item.codigo, item]),
);

/** Os concelhos de uma NUTS II, por ordem alfabética. */
export function concelhosDaRegiao(regiao: MarketRegion): readonly Concelho[] {
  return CONCELHOS.filter((item) => item.regiao === regiao);
}
